/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Ideal.Operations
public import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# Additive generators of products of ideals

This file relates additive generators of two ideals to additive generators of their product. If
the underlying additive groups of ideals `I` and `J` are generated by sets `S` and `T`, then the
underlying additive group of `I * J` is generated by the pairwise products `S * T`.

The point is that this is stronger than the familiar identity
`Ideal.span S * Ideal.span T = Ideal.span (S * T)`: the coefficients in an ideal span need not
preserve a proposed set of additive generators. Here that stability is supplied by the hypotheses
that the additive closures already are ideals.

## Main result

* `Ideal.toAddSubgroup_mul_eq_closure_mul`: additive generators of a product of ideals.
-/

public section

open scoped Pointwise

namespace AddSubgroup

variable {R : Type*} [CommRing R] {S T : Set R} {x y : R}

/-- The product of elements from two additive closures belongs to the additive closure of the
pairwise products. -/
theorem mul_mem_closure_mul (hx : x ∈ closure S) (hy : y ∈ closure T) :
    x * y ∈ closure (S * T) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
      induction hy using AddSubgroup.closure_induction with
      | mem y hy => exact AddSubgroup.subset_closure ⟨x, hx, y, hy, rfl⟩
      | zero => simp
      | add y z _ _ hy hz => simpa [mul_add] using add_mem hy hz
      | neg y _ hy => simpa using neg_mem hy
  | zero => simp
  | add x z _ _ hx hz => simpa [add_mul] using add_mem hx hz
  | neg x _ hx => simpa using neg_mem hx

end AddSubgroup

namespace Ideal

variable {R : Type*} [CommRing R] {I J : Ideal R} {S T : Set R}

/-- If `S` and `T` additively generate the ideals `I` and `J`, then their pairwise products
additively generate `I * J`. -/
theorem toAddSubgroup_mul_eq_closure_mul
    (hI : I.toAddSubgroup = AddSubgroup.closure S)
    (hJ : J.toAddSubgroup = AddSubgroup.closure T) :
    (I * J).toAddSubgroup = AddSubgroup.closure (S * T) := by
  apply le_antisymm
  · intro z hz
    refine Submodule.mul_induction_on hz ?_ fun _ _ => add_mem
    intro x hx y hy
    change x ∈ I.toAddSubgroup at hx
    change y ∈ J.toAddSubgroup at hy
    rw [hI] at hx
    rw [hJ] at hy
    exact AddSubgroup.mul_mem_closure_mul hx hy
  · rw [AddSubgroup.closure_le]
    rintro z ⟨x, hx, y, hy, rfl⟩
    apply Ideal.mul_mem_mul
    · change x ∈ I.toAddSubgroup
      rw [hI]
      exact AddSubgroup.subset_closure hx
    · change y ∈ J.toAddSubgroup
      rw [hJ]
      exact AddSubgroup.subset_closure hy

end Ideal
