/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.RingTheory.Ideal.Operations

/-!
# Descending a finitely generated ideal to a subring it lies inside

Let `S` be a subring of `R` and let `I = Ideal.span G` be an ideal of `R` generated by a set `G`
that lies inside `S`. If `I` itself lies inside `S`, then

```text
I * I ≤ Submodule.span S G,
```

that is, the *square* of `I` is already spanned by `G` over the small ring `S`, even though `I`
generally is not.

## Why the square, and why this is not automatic

`I` need not be generated by `G` over `S`: an element `Σ bᵢ gᵢ` of `I` has its coefficients `bᵢ`
in `R`, and there is no reason for them to lie in `S`. What rescues the square is that the
coefficients can be **moved onto the other factor**: for `x ∈ I`,

```text
x * (Σ bᵢ gᵢ) = Σ (x * bᵢ) gᵢ,
```

and each `x * bᵢ` lies in `I`, hence in `S`. So the new coefficients are in `S` even though the
old ones were not. This is the same absorption trick as in
`Valuation.map_le_pow_of_mem_span_pow_succ`, used there to bound a valuation on a power of an
ideal.

Consequently `I * I` is a finitely generated `S`-submodule whenever `G` is finite, which is what
makes a *smaller* subring inherit an ideal of definition — the situation the intersection of two
rings of definition presents, and where `Ideal.map` is unavailable because the inclusion runs the
wrong way.

## Main results

* `Ideal.restrictScalars_mul_self_le_span`

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Corollary 6.4.
-/

public section

namespace Ideal

variable {R : Type*} [CommRing R] (S : Subring R) {G : Set R}

/-- Multiplying by an element of the ideal moves the coefficients into `S`: if every element of
`Ideal.span G` lies in `S`, then `x * y` lies in the `S`-span of `G` for `x` and `y` in the ideal.

The coefficient `x` is quantified **inside** the induction, because the scalar-multiplication case
has to feed `x * c` back in — which is legitimate exactly because `Ideal.span G` is an `R`-ideal
and so absorbs `c`. -/
private theorem mul_mem_span_of_mem_span (hIS : ∀ x ∈ Ideal.span G, x ∈ S) :
    ∀ y ∈ Ideal.span G, ∀ x ∈ Ideal.span G, x * y ∈ Submodule.span S G := by
  intro y hy
  induction hy using Submodule.span_induction with
  | mem g hg =>
    intro x hx
    exact Submodule.smul_mem _ (⟨x, hIS x hx⟩ : S) (Submodule.subset_span hg)
  | zero => intro x _; simp
  | add y₁ y₂ _ _ ih₁ ih₂ =>
    intro x hx
    rw [mul_add]
    exact Submodule.add_mem _ (ih₁ x hx) (ih₂ x hx)
  | smul c y _ ih =>
    intro x hx
    rw [smul_eq_mul, ← mul_assoc]
    exact ih _ (Ideal.mul_mem_right c _ hx)

/-- **The square of an ideal contained in a subring is spanned over that subring by any generating
set.** If `I = Ideal.span G` lies inside a subring `S` of `R`, then `I * I` is contained in the
`S`-span of `G` — so for finite `G` it is a finitely generated `S`-submodule, even though `I`
itself need not be.

The generators are not assumed to lie in `S` separately: that follows, since `G ⊆ I ⊆ S`. -/
theorem restrictScalars_mul_self_le_span (hIS : ∀ x ∈ Ideal.span G, x ∈ S) :
    Submodule.restrictScalars S (Ideal.span G * Ideal.span G) ≤ Submodule.span S G := by
  intro a ha
  have ha' : a ∈ (Ideal.span G * Ideal.span G : Ideal R) := ha
  refine Submodule.mul_induction_on ha' (fun x hx y hy ↦ ?_) fun x y hx hy ↦ ?_
  · exact mul_mem_span_of_mem_span S hIS y hy x hx
  · exact Submodule.add_mem _ hx hy

end Ideal
