/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.AlgebraicGeometry.WeilDivisor.FractionalIdealDivisor.Basic
public import TauCeti.RingTheory.ClassGroup.Basic

/-!
# Ideal classes of the height one primes

`TauCeti/AlgebraicGeometry/WeilDivisor/FractionalIdealDivisor/Basic.lean` identifies the invertible
fractional ideals of a Dedekind domain `R` with the Weil divisors of its height one spectrum, and
notes that the quotient-level comparison with the class group is not proved there. This file takes
the first step of that comparison, on the side the `S`-unit arguments need.

Writing `IsDedekindDomain.HeightOneSpectrum.classGroupMk v` for the class `[v]` of a height one
prime (`TauCeti.RingTheory.ClassGroup.Basic`, which carries the part of this development that
does not mention Weil divisors), the two results here are localisation statements about which
classes a set `T` of primes generates: if the `v`-adic multiplicities of a unit fractional ideal
vanish outside `T` (`FractionalIdeal.mk_mem_closure_of_count_eq_zero`), or merely agree outside
`T` with those of a principal ideal (`FractionalIdeal.mk0_mem_closure_of_count_eq`), then its
class lies in the subgroup generated by `{[v] : v ∈ T}`.

This is what `TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak Mordell–Weil: it is
the step that makes the `S`-class group a quotient of the class group by the classes of `S`, hence
finite.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/FractionalIdeal.lean`
at the roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll), whose factorization layer this
repository already carries as `fractionalIdealDivisor` and friends; only the class-group statements
are ported here. Following this repository's convention for adapted material, the upstream
authorship is credited here rather than in the copyright header.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

namespace TauCeti

namespace AlgebraicGeometry

namespace WeilDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- If the `v`-adic multiplicities of a unit fractional ideal vanish outside a set `T` of height
one primes, its ideal class lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.FractionalIdeal.mk_mem_closure_of_count_eq_zero {T : Set (HeightOneSpectrum R)}
    {I : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) = 0) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  classical
  -- Recover `I` as the product of the prime powers its divisor records, already at unit level so
  -- that `ClassGroup.mk` can be pushed through the product in one step. The underlying fractional
  -- ideals agree by `symm_apply_apply` at `I`, read through the two characterising lemmas.
  have hI : I = (fractionalIdealDivisor R K (Additive.ofMul I)).prod fun v e =>
      Units.mk0 (v.asIdeal : FractionalIdeal R⁰ K)
        (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot) ^ e := by
    have hsymm := (fractionalIdealDivisorAddEquiv R K).symm_apply_apply (Additive.ofMul I)
    rw [fractionalIdealDivisorAddEquiv_apply, fractionalIdealDivisorAddEquiv_symm_apply] at hsymm
    refine Units.ext ?_
    rw [← congrArg (fun J : (FractionalIdeal R⁰ K)ˣ => (J : FractionalIdeal R⁰ K))
      (Additive.ofMul.injective hsymm)]
    push_cast [Finsupp.prod]
    simp
  rw [hI, map_finsuppProd]
  refine Subgroup.prod_mem _ fun v hv ↦ ?_
  have hvT : v ∈ T := by
    by_contra hvn
    refine WeilDivisor.mem_support_iff.mp hv ?_
    rw [coeff_fractionalIdealDivisor]
    exact h v hvn
  -- `Subgroup.prod_mem` leaves the `Finsupp.prod` body as a beta-redex, so use `simp only`
  -- (which beta-reduces) rather than `rw` to expose the `_ ^ _` that `map_zpow` needs.
  simp only [map_zpow]
  rw [← v.classGroupMk_eq_mk K]
  exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_image_of_mem _ hvT)) _

/-- If the `v`-adic multiplicities of a nonzero integral ideal `J` agree outside a set `T` of
height one primes with those of a principal fractional ideal `(x)`, then the class of `J` lies in
the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.FractionalIdeal.mk0_mem_closure_of_count_eq {T : Set (HeightOneSpectrum R)}
    {J : (Ideal R)⁰} {x : Kˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v ((J : Ideal R) : FractionalIdeal R⁰ K) =
      FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (x : K))) :
    ClassGroup.mk0 J ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hmk : ClassGroup.mk0 J =
      ClassGroup.mk K (FractionalIdeal.mk0 K J * (toPrincipalIdeal R K x)⁻¹) := by
    rw [map_mul, map_inv, ClassGroup.mk_toPrincipalIdeal, inv_one, mul_one, ClassGroup.mk_mk0]
  rw [hmk]
  refine FractionalIdeal.mk_mem_closure_of_count_eq_zero fun v hv ↦ ?_
  rw [Units.val_mul, FractionalIdeal.count_mul K v (Units.ne_zero _) (Units.ne_zero _),
    Units.val_inv_eq_inv_val, FractionalIdeal.count_inv, FractionalIdeal.coe_mk0,
    coe_toPrincipalIdeal, h v hv]
  exact add_neg_cancel _

end WeilDivisor

end AlgebraicGeometry

end TauCeti

end
