/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.AlgebraicGeometry.WeilDivisor.FractionalIdealDivisor.Basic

/-!
# Ideal classes of the height one primes

`TauCeti/AlgebraicGeometry/WeilDivisor/FractionalIdealDivisor/Basic.lean` identifies the invertible
fractional ideals of a Dedekind domain `R` with the Weil divisors of its height one spectrum, and
notes that the quotient-level comparison with the class group is not proved there. This file takes
the first step of that comparison, on the side the `S`-unit arguments need.

`IsDedekindDomain.HeightOneSpectrum.classGroupMk v` is the class `[v]` of a height one prime. The
two results are localisation statements about which classes a set `T` of primes generates: if the
`v`-adic multiplicities of a unit fractional ideal vanish outside `T`
(`FractionalIdeal.mk_mem_closure_of_count_eq_zero`), or merely agree outside `T` with those of a
principal ideal (`FractionalIdeal.mk0_mem_closure_of_count_eq`), then its class lies in the
subgroup generated by `{[v] : v ∈ T}`.

This is what `TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak Mordell–Weil: it is
the step that makes the `S`-class group a quotient of the class group by the classes of `S`, hence
finite.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/FractionalIdeal.lean`
at the roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll), whose factorization layer this
repository already carries as `fractionalIdealDivisor` and friends; only the class-group statements
are ported here. Following this repository's convention for adapted material, the upstream
authorship is credited here rather than in the copyright header.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

namespace TauCeti

namespace AlgebraicGeometry

namespace WeilDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- The class of a height one prime `v` in the ideal class group of `R`. -/
noncomputable def _root_.IsDedekindDomain.HeightOneSpectrum.classGroupMk
    (v : HeightOneSpectrum R) : ClassGroup R :=
  ClassGroup.mk0 ⟨v.asIdeal, mem_nonZeroDivisors_of_ne_zero v.ne_bot⟩

/-- The class of `v` is the class of `v.asIdeal` viewed as an invertible fractional ideal — the
same unit that `fractionalIdealDivisor_asIdeal` sends to the point divisor `[v]`. -/
lemma _root_.IsDedekindDomain.HeightOneSpectrum.classGroupMk_eq_mk (K : Type*) [Field K]
    [Algebra R K] [IsFractionRing R K] (v : HeightOneSpectrum R) :
    v.classGroupMk = ClassGroup.mk K (Units.mk0 (v.asIdeal : FractionalIdeal R⁰ K)
      (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)) := by
  rw [HeightOneSpectrum.classGroupMk, ← ClassGroup.mk_mk0 K]
  exact congrArg _ (Units.ext rfl)

/-- An invertible fractional ideal is the product of the prime powers its divisor records. This is
`fractionalIdealDivisorAddEquiv_symm_apply` read back through the equivalence. -/
lemma eq_prod_asIdeal_zpow (I : (FractionalIdeal R⁰ K)ˣ) :
    I = Units.mk0 ((fractionalIdealDivisor R K (Additive.ofMul I)).prod
        fun v e => (v.asIdeal : FractionalIdeal R⁰ K) ^ e)
      (prod_asIdeal_zpow_ne_zero R K _) := by
  have h := (fractionalIdealDivisorAddEquiv R K).symm_apply_apply (Additive.ofMul I)
  rw [fractionalIdealDivisorAddEquiv_apply, fractionalIdealDivisorAddEquiv_symm_apply] at h
  exact (Additive.ofMul.injective h).symm

/-- If the `v`-adic multiplicities of a unit fractional ideal vanish outside a set `T` of height
one primes, its ideal class lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.FractionalIdeal.mk_mem_closure_of_count_eq_zero {T : Set (HeightOneSpectrum R)}
    {I : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) = 0) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  classical
  set D := fractionalIdealDivisor R K (Additive.ofMul I) with hD
  rw [eq_prod_asIdeal_zpow (K := K) I]
  rw [show (Units.mk0 (D.prod fun v e => (v.asIdeal : FractionalIdeal R⁰ K) ^ e)
      (prod_asIdeal_zpow_ne_zero R K D))
      = D.prod (fun v e => Units.mk0 (v.asIdeal : FractionalIdeal R⁰ K)
          (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot) ^ e) from
    Units.ext (by push_cast [Finsupp.prod]; simp)]
  rw [map_finsuppProd]
  refine Subgroup.prod_mem _ fun v hv ↦ ?_
  have hvT : v ∈ T := by
    by_contra hvn
    refine Finsupp.mem_support_iff.mp hv ?_
    have hc := coeff_fractionalIdealDivisor R K (Additive.ofMul I) v
    simp only [coeff, toMul_ofMul] at hc
    rw [hD, hc]
    exact h v hvn
  -- `Subgroup.prod_mem` leaves the `Finsupp.prod` body as a beta-redex, so use `simp only`
  -- (which beta-reduces) rather than `rw` to expose the `_ ^ _` that `map_zpow` needs.
  simp only [map_zpow]
  rw [← v.classGroupMk_eq_mk K]
  exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_image_of_mem _ hvT)) _

end WeilDivisor

end AlgebraicGeometry

end TauCeti

end
