/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.ClassGroup.ExtendedHom
public import TauCeti.RingTheory.ClassGroup.HeightOneSpectrum
public import TauCeti.RingTheory.DedekindDomain.Factorization
public import TauCeti.RingTheory.DedekindDomain.SInteger.Spectrum

/-!
# The class group of the `S`-integers

For a Dedekind domain `R` with fraction field `K` and a set `S` of height one primes, the class
group of the ring `𝒪_S` of `S`-integers is the class group of `R` modulo the classes of the primes
in `S`:

`IsDedekindDomain.integerClassGroupEquiv : ClassGroup 𝒪_S ≃* ClassGroup R ⧸ ⟨[v] : v ∈ S⟩`.

The proof is the first isomorphism theorem applied to extension of ideals `Cl(R) → Cl(𝒪_S)`:

* `IsDedekindDomain.integer_extendedHom_surjective`: extension is surjective, because every ideal
  of `𝒪_S` is extended from `R` (`integer_map_comap_eq`);
* `IsDedekindDomain.ker_integer_extendedHom`: its kernel is generated by the classes of the primes
  in `S`. One inclusion is that a prime of `S` extends to `⊤` (`integer_map_asIdeal_eq_top`); the
  other compares multiplicities off `S`, which is what
  `IsDedekindDomain.integer_count_map_coeIdeal` and
  `IsDedekindDomain.integer_count_spanSingleton_integerPrimeOverOfNotMem` supply, and then applies
  `ClassGroup.mk0_mem_closure_of_count_eq`.

`IsDedekindDomain.integer_finite_classGroup` is the consequence the arithmetic wants: `Cl(𝒪_S)` is
finite whenever `Cl(R)` is, being a quotient of it. That is one of the two finiteness inputs to
weak Mordell–Weil (the other being the `S`-unit theorem), so this advances
`TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 (Mordell–Weil), whose Kummer argument needs
`E(K)/2E(K)` finite.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/SIntegers.lean` at the
roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll). Following this repository's
convention for adapted material, the upstream authorship is credited here rather than in the
copyright header. Stoll's unprefixed names are given the `integer` prefix that
`TauCeti/RingTheory/DedekindDomain/SInteger/` already uses.
-/

public section

open IsDedekindDomain FractionalIdeal
open scoped nonZeroDivisors

namespace IsDedekindDomain

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

/-- `𝒪_S` is torsion-free over `R`, as `R` embeds into it. -/
instance : Module.IsTorsionFree R (S.integer K) := by
  rw [Module.isTorsionFree_iff_algebraMap_injective]
  exact FaithfulSMul.algebraMap_injective R (S.integer K)

/-- Extension of ideals `Cl(R) → Cl(𝒪_S)` is surjective. -/
lemma integer_extendedHom_surjective :
    Function.Surjective (ClassGroup.extendedHom R (S.integer K)) := by
  intro c
  obtain ⟨I, rfl⟩ := ClassGroup.mk0_surjective c
  have hI : (I : Ideal (S.integer K)) ≠ ⊥ := by
    have := I.2; rwa [mem_nonZeroDivisors_iff_ne_zero] at this
  refine ⟨ClassGroup.mk0 ⟨(I : Ideal (S.integer K)).comap (algebraMap R (S.integer K)),
    mem_nonZeroDivisors_iff_ne_zero.mpr (integer_comap_ne_bot K S hI)⟩, ?_⟩
  rw [ClassGroup.extendedHom_mk0]
  exact congrArg _ (Subtype.ext (integer_map_comap_eq K S _))

/-- The class group of `𝒪_S` is finite as soon as that of `R` is, being a quotient of it. This is
one of the two finiteness inputs to weak Mordell–Weil. -/
instance integer_finite_classGroup [Finite (ClassGroup R)] : Finite (ClassGroup (S.integer K)) :=
  .of_surjective _ (integer_extendedHom_surjective K S)

/-- Divisibility by prime powers transfers along extension to `𝒪_S` and back, for primes off
`S`. -/
lemma integer_map_le_map_pow_iff {v : HeightOneSpectrum R} (hv : v ∉ S) (J : Ideal R) (k : ℕ) :
    Ideal.map (algebraMap R (S.integer K)) J ≤ (integerPrimeOverOfNotMem K S hv).asIdeal ^ k ↔
      J ≤ v.asIdeal ^ k := by
  rw [integerPrimeOverOfNotMem_asIdeal, ← Ideal.map_pow]
  exact ⟨fun h ↦ Ideal.le_comap_map.trans
    ((Ideal.comap_mono h).trans (integer_comap_map_pow K S hv k).le), Ideal.map_mono⟩

/-- The multiplicity of the extension of an ideal at the prime above `v ∉ S` is the multiplicity
at `v`. -/
lemma integer_count_map_coeIdeal {v : HeightOneSpectrum R} (hv : v ∉ S) {J : Ideal R}
    (hJ : J ≠ ⊥) :
    count K (integerPrimeOverOfNotMem K S hv)
        ((Ideal.map (algebraMap R (S.integer K)) J : Ideal (S.integer K)) :
          FractionalIdeal (S.integer K)⁰ K) =
      count K v (J : FractionalIdeal R⁰ K) := by
  have hmJ := Ideal.map_ne_bot_of_ne_bot (S := S.integer K) hJ
  rw [count_coe K _ hmJ, count_coe K v hJ, Nat.cast_inj]
  refine Nat.le_antisymm
    ((v.le_count_iff_le hJ _).mpr ((integer_map_le_map_pow_iff K S hv J _).mp
      (((integerPrimeOverOfNotMem K S hv).le_count_iff_le hmJ _).mp le_rfl)))
    (((integerPrimeOverOfNotMem K S hv).le_count_iff_le hmJ _).mpr
      ((integer_map_le_map_pow_iff K S hv J _).mpr ((v.le_count_iff_le hJ _).mp le_rfl)))

/-- The multiplicity of a principal fractional ideal at the prime above `v ∉ S` is the
multiplicity at `v`, because the two valuations agree
(`valuation_integerPrimeOverOfNotMem`) and multiplicity determines the valuation
(`valuation_eq_exp_neg_count`). -/
lemma integer_count_spanSingleton_integerPrimeOverOfNotMem {v : HeightOneSpectrum R} (hv : v ∉ S)
    {x : K} (hx : x ≠ 0) :
    count K (integerPrimeOverOfNotMem K S hv) (spanSingleton (S.integer K)⁰ x) =
      count K v (spanSingleton R⁰ x) := by
  refine neg_injective (WithZero.exp_injective ?_)
  rw [← valuation_eq_exp_neg_count K _ hx, ← valuation_eq_exp_neg_count K v hx]
  exact valuation_integerPrimeOverOfNotMem K S hv x

/-- The classes of the primes in `S` lie in the kernel of extension: such primes extend to `⊤`. -/
lemma closure_le_ker_integer_extendedHom :
    Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) ≤
      (ClassGroup.extendedHom R (S.integer K)).ker := by
  rw [Subgroup.closure_le]
  rintro _ ⟨v, hv, rfl⟩
  rw [SetLike.mem_coe, MonoidHom.mem_ker, HeightOneSpectrum.classGroupMk_eq_mk0,
    ClassGroup.extendedHom_mk0]
  refine (ClassGroup.mk0_eq_one_iff _).mpr ?_
  change (Ideal.map (algebraMap R (S.integer K)) v.asIdeal).IsPrincipal
  rw [integer_map_asIdeal_eq_top K S hv]
  exact ⟨1, Ideal.span_singleton_one.symm⟩

/-- The kernel of extension of ideal classes to `𝒪_S` is contained in the subgroup generated by
the classes of the primes in `S`. -/
lemma ker_integer_extendedHom_le :
    (ClassGroup.extendedHom R (S.integer K)).ker ≤
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) := by
  intro c hc
  obtain ⟨J, rfl⟩ := ClassGroup.mk0_surjective c
  rw [MonoidHom.mem_ker, ClassGroup.extendedHom_mk0, ← ClassGroup.mk_mk0 K,
    ClassGroup.mk_eq_one_iff_exists] at hc
  obtain ⟨x, hx⟩ := hc
  have hxval : spanSingleton (S.integer K)⁰ (x : K) =
      ((Ideal.map (algebraMap R (S.integer K)) (J : Ideal R) : Ideal (S.integer K)) :
        FractionalIdeal (S.integer K)⁰ K) := by
    have h := congrArg Units.val hx
    rwa [coe_toPrincipalIdeal, FractionalIdeal.coe_mk0] at h
  refine ClassGroup.mk0_mem_closure_of_count_eq K (x := x) fun v hv ↦ ?_
  rw [← integer_count_map_coeIdeal K S hv (mem_nonZeroDivisors_iff_ne_zero.mp J.2), ← hxval,
    integer_count_spanSingleton_integerPrimeOverOfNotMem K S hv x.ne_zero]

/-- The kernel of extension is exactly the subgroup generated by the classes of the primes in
`S`. -/
lemma ker_integer_extendedHom :
    (ClassGroup.extendedHom R (S.integer K)).ker =
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  le_antisymm (ker_integer_extendedHom_le K S) (closure_le_ker_integer_extendedHom K S)

/-- **The class group of the `S`-integers.** `Cl(𝒪_S)` is `Cl(R)` modulo the classes of the primes
in `S`: the first isomorphism theorem applied to extension of ideals. -/
noncomputable def integerClassGroupEquiv :
    ClassGroup (S.integer K) ≃*
      ClassGroup R ⧸ Subgroup.closure (HeightOneSpectrum.classGroupMk '' S) :=
  (QuotientGroup.quotientKerEquivOfSurjective _ (integer_extendedHom_surjective K S)).symm.trans
    (QuotientGroup.quotientMulEquivOfEq (ker_integer_extendedHom K S))

/-- `integerClassGroupEquiv` inverts extension: the class extended from `c : Cl(R)` corresponds to
the class of `c` in the quotient. -/
@[simp] lemma integerClassGroupEquiv_symm_mk (c : ClassGroup R) :
    (integerClassGroupEquiv K S).symm (QuotientGroup.mk c) =
      ClassGroup.extendedHom R (S.integer K) c := by
  -- a `public section` leaves the body unexposed, so this is not `rfl` from outside the file
  simp only [integerClassGroupEquiv]
  rfl

end IsDedekindDomain

end
