/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind
public import TauCeti.NumberTheory.NumberField.Index.Exponent

/-!
# Common index divisors

A prime `p` is a *common index divisor* of a number field `K` when it divides the index
`[𝓞 K : ℤ[θ]]` of **every** integral primitive element `θ`. Such a prime obstructs monogenicity:
`𝓞 K = ℤ[θ]` would force `index θ = 1`.

The obstruction is a counting argument. Kummer–Dedekind puts the primes of `𝓞 K` above `p` in
bijection with the distinct monic irreducible factors of `minpoly ℤ θ` modulo `p`, matching the
residue degree of a prime with the degree of its factor — but only for a `θ` whose conductor
exponent is prime to `p`. So if `p` has more primes of residue degree `d` than there are monic
irreducible polynomials of degree `d` available over `𝔽_p`, no `θ` can satisfy that hypothesis,
and then `p` divides `exponent θ`, hence `index θ`.

## Main definitions

* `TauCeti.NumberField.IsCommonIndexDivisor`: `p` divides the index of every integral primitive
  element.
* `TauCeti.NumberField.primesOverOfInertiaDeg`: the primes above `p` of a fixed residue degree.
* `TauCeti.NumberField.monicIrreduciblesOfDegree`: the monic irreducible polynomials of a fixed
  degree over `𝔽_p`.

## Main results

* `TauCeti.NumberField.IsCommonIndexDivisor.not_exists_index_eq_one`: a common index divisor
  rules out an element of index `1`, so it obstructs monogenicity.
* `TauCeti.NumberField.IsCommonIndexDivisor.adjoin_ne_top`: equivalently, no order `ℤ[θ]` is all
  of `𝓞 K`.
* `TauCeti.NumberField.finite_monicIrreduciblesOfDegree`: there are finitely many of them.
* `TauCeti.NumberField.ncard_primesOverOfInertiaDeg_le`: the Kummer–Dedekind counting bound.
* `TauCeti.NumberField.card_filter_monicFactorsMod_le`: the factors of `minpoly ℤ θ` of degree
  `d` are among the degree-`d` monic irreducibles over `𝔽_p`.
* `TauCeti.NumberField.isCommonIndexDivisor_of_ncard_lt_ncard`: the counting obstruction.

The converse is Hensel's criterion — the common index divisors are exactly the primes whose
splitting type is not realizable modulo `p` — and is deliberately not proved here.

## References

* [J. Neukirch, *Algebraic number theory*][neukirch1999], III §2 Exercise 1.
-/

public section

open scoped NumberField
open Ideal Polynomial RingOfIntegers NumberField.Ideal

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K] (p : ℕ) [Fact p.Prime]

/-- `p` is a **common index divisor** of `K` when it divides the index `[𝓞 K : ℤ[θ]]` of every
integral primitive element `θ` of `K`.

A common index divisor obstructs monogenicity. If `K` admits no integral primitive element the
condition holds vacuously, so the predicate carries content only when such a `θ` exists. -/
def IsCommonIndexDivisor (p : ℕ) (K : Type*) [Field K] [NumberField K] : Prop :=
  ∀ θ : IntegralPrimitiveElement K, p ∣ θ.index

namespace IsCommonIndexDivisor

variable {p}

/-- **A common index divisor obstructs monogenicity.** No integral primitive element has index
`1`, since `p` divides every index and `p` is prime. -/
theorem not_exists_index_eq_one (h : IsCommonIndexDivisor p K) :
    ¬ ∃ θ : IntegralPrimitiveElement K, θ.index = 1 := by
  rintro ⟨θ, hθ⟩
  exact (Fact.out : p.Prime).not_dvd_one (hθ ▸ h θ)

/-- The same obstruction stated on orders: no `ℤ[θ]` generated by an integral primitive element
is all of `𝓞 K`. -/
theorem adjoin_ne_top (h : IsCommonIndexDivisor p K) (θ : IntegralPrimitiveElement K) :
    θ.adjoin ≠ ⊤ := fun hadj =>
  h.not_exists_index_eq_one ⟨θ, (IntegralPrimitiveElement.index_eq_one_iff θ).mpr hadj⟩

end IsCommonIndexDivisor

variable (K) in
/-- The primes of `𝓞 K` above `p` whose residue degree over `ℤ` is `d`. -/
def primesOverOfInertiaDeg (d : ℕ) : Set ((span {(p : ℤ)}).primesOver (𝓞 K)) :=
  {Q | (Q : Ideal (𝓞 K)).inertiaDeg ℤ = d}

/-- The monic irreducible polynomials of degree `d` over `𝔽_p`.

This set depends only on `p` and `d`, not on any choice of generator, which is what lets the
counting obstruction below be stated without assuming a bound. -/
def monicIrreduciblesOfDegree (d : ℕ) : Set ((ZMod p)[X]) :=
  {g | g.Monic ∧ Irreducible g ∧ g.natDegree = d}

/-- There are finitely many monic irreducible polynomials of degree `d` over `𝔽_p`: they sit
inside the monic polynomials of degree `d`, which are parametrised by their lower coefficients. -/
theorem finite_monicIrreduciblesOfDegree (d : ℕ) : (monicIrreduciblesOfDegree p d).Finite := by
  have hdeg : Finite (Polynomial.degreeLT (ZMod p) d) :=
    Finite.of_equiv _ (Polynomial.degreeLTEquiv (ZMod p) d).toEquiv.symm
  have hmon : {g : (ZMod p)[X] | g.Monic ∧ g.natDegree = d}.Finite := by
    rw [← Set.finite_coe_iff]
    exact Finite.of_equiv _ (Polynomial.monicEquivDegreeLT (R := ZMod p) d).symm
  exact hmon.subset fun g hg => ⟨hg.1, hg.2.2⟩

omit [NumberField K] in
/-- The degree-`d` monic irreducible factors of `minpoly ℤ θ` modulo `p` are among the degree-`d`
monic irreducibles over `𝔽_p`, so they are no more numerous. -/
theorem card_filter_monicFactorsMod_le {θ : 𝓞 K} (d : ℕ) :
    ((monicFactorsMod θ p).filter fun Q => Q.natDegree = d).card ≤
      (monicIrreduciblesOfDegree p d).ncard := by
  classical
  have h₀ : Polynomial.map (Int.castRingHom (ZMod p)) (minpoly ℤ θ) ≠ 0 :=
    Polynomial.map_monic_ne_zero (minpoly.monic θ.isIntegral)
  have hsub : ↑((monicFactorsMod θ p).filter fun Q => Q.natDegree = d) ⊆
      monicIrreduciblesOfDegree p d := by
    intro g hg
    rw [Finset.mem_coe, Finset.mem_filter] at hg
    obtain ⟨hmem, hdeg⟩ := hg
    rw [Multiset.mem_toFinset] at hmem
    obtain ⟨hirr, hmon, -⟩ := (Polynomial.mem_normalizedFactors_iff h₀).mp hmem
    exact ⟨hmon, hirr, hdeg⟩
  rw [← Set.ncard_coe_finset]
  exact Set.ncard_le_ncard hsub (finite_monicIrreduciblesOfDegree p d)

/-- The Kummer–Dedekind bijection sends a prime above `p` of residue degree `d` to a monic
irreducible factor of `minpoly ℤ θ` modulo `p` of degree `d`. -/
private theorem mem_filter_monicFactorsMod_of_mem_primesOverOfInertiaDeg {θ : 𝓞 K}
    (hp : ¬ p ∣ exponent θ) {d : ℕ}
    (Q : (span {(p : ℤ)}).primesOver (𝓞 K))
    (hQ : Q ∈ primesOverOfInertiaDeg K p d) :
    ((primesOverSpanEquivMonicFactorsMod hp Q : (ZMod p)[X])) ∈
      (monicFactorsMod θ p).filter fun R => R.natDegree = d := by
  classical
  refine Finset.mem_filter.mpr ⟨(primesOverSpanEquivMonicFactorsMod hp Q).2, ?_⟩
  -- The degree lemma is stated at `.symm`; rewrite `Q` as `.symm (e Q)` to apply it.
  have h := inertiaDeg_primesOverSpanEquivMonicFactorsMod_symm_apply' hp
    (primesOverSpanEquivMonicFactorsMod hp Q).2
  rw [Subtype.coe_eta, Equiv.symm_apply_apply] at h
  exact h ▸ hQ

/-- **The Kummer–Dedekind counting bound.** For a `θ` whose conductor exponent is prime to `p`,
the primes of `𝓞 K` above `p` with residue degree `d` are no more numerous than the degree-`d`
monic irreducible factors of `minpoly ℤ θ` modulo `p`. -/
theorem ncard_primesOverOfInertiaDeg_le {θ : 𝓞 K} (hp : ¬ p ∣ exponent θ) (d : ℕ) :
    (primesOverOfInertiaDeg K p d).ncard ≤
      ((monicFactorsMod θ p).filter fun Q => Q.natDegree = d).card := by
  classical
  have hinj : Set.InjOn
      (fun Q => (primesOverSpanEquivMonicFactorsMod hp Q : (ZMod p)[X]))
      (primesOverOfInertiaDeg K p d) := fun _ _ _ _ h =>
    (primesOverSpanEquivMonicFactorsMod hp).injective (Subtype.ext h)
  rw [← Set.ncard_coe_finset ((monicFactorsMod θ p).filter fun Q => Q.natDegree = d)]
  exact Set.ncard_le_ncard_of_injOn _
    (mem_filter_monicFactorsMod_of_mem_primesOverOfInertiaDeg p hp) hinj
    (Finset.finite_toSet _)

/-- **The counting obstruction.** If `p` has more primes of residue degree `d` than there are
monic irreducible polynomials of degree `d` over `𝔽_p`, then `p` divides the index of every
integral primitive element.

Both counts are intrinsic to `p`, `d` and `K`: no bound is assumed, because the degree-`d` monic
irreducibles over `𝔽_p` are a fixed finite set independent of any generator. -/
theorem isCommonIndexDivisor_of_ncard_lt_ncard {d : ℕ}
    (hlt : (monicIrreduciblesOfDegree p d).ncard < (primesOverOfInertiaDeg K p d).ncard) :
    IsCommonIndexDivisor p K := by
  intro θ
  by_contra hdvd
  -- A `θ` escaping `p` in the index also escapes it in the conductor exponent.
  have hexp : ¬ p ∣ exponent (θ : 𝓞 K) := fun h =>
    hdvd ((IntegralPrimitiveElement.dvd_index_iff_dvd_exponent θ).mpr h)
  have hle : (primesOverOfInertiaDeg K p d).ncard ≤ (monicIrreduciblesOfDegree p d).ncard :=
    (ncard_primesOverOfInertiaDeg_le p hexp d).trans (card_filter_monicFactorsMod_le p d)
  exact absurd (hlt.trans_le hle) (lt_irrefl _)

end TauCeti.NumberField
