/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Group.Subgroup.ZPowers
public import TauCeti.NumberTheory.Cyclotomic.FixedField
public import TauCeti.NumberTheory.Cyclotomic.FixingSubgroup
public import TauCeti.NumberTheory.NumberField.Cyclotomic.Compositum

/-!
# The tagged fixed fields are cyclotomic

`M / K` is Galois with `Gal(M/K)` split by `galEquivProd` as `Gal(L/K) × (ZMod m)ˣ`, the second
factor being the cyclotomic character on the `m`-th roots of unity. A *tag* is a pair `(σ, τ)` in
that product. This file shows that when the tag satisfies `orderOf σ ∣ orderOf τ`, the field fixed
by the cyclic subgroup the tag generates has `M` as an `m`-th cyclotomic extension.

## Main results

* `IsCyclotomicExtension.fixedField_zpowers_isCyclotomicExtension`: for a tag `(σ, τ)` with
  `orderOf σ ∣ orderOf τ`, `M / fixedField ⟪(σ, τ)⟫` is an `m`-th cyclotomic extension.

## Implementation notes

The general criterion is
`IsPrimitiveRoot.fixedField_isCyclotomicExtension_of_inf_fixingSubgroup_eq_bot`: a subgroup whose
intersection with the fixer of `K(μ_m)` is trivial has that property. Two
identifications turn the divisibility hypothesis into that intersection statement. The fixer of
`K(μ_m)` is the kernel of the cyclotomic character, and under `galEquivProd` that kernel is the
preimage of `⊤ × ⊥`; and a cyclic subgroup of a product generated by `(σ, τ)` meets `⊤ × ⊥`
trivially exactly when `orderOf σ ∣ orderOf τ`. Composing the two leaves nothing to prove beyond
transporting an element along the splitting.
-/

public section

open IntermediateField
open scoped NumberField

namespace IsCyclotomicExtension

variable (K L M : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Field M]
  [Algebra K L] [Algebra K M] [Algebra L M] [IsScalarTower K L M] [IsGalois K L]
  (m : ℕ) [NeZero m] [IsCyclotomicExtension {m} L M] [FiniteDimensional K M] [IsGalois K M]

/-- **The tagged fixed field carries the cyclotomic extension.** For a tag `(σ, τ)` in the
splitting `Gal(M/K) ≃ Gal(L/K) × (ZMod m)ˣ` whose first component's order divides the second's,
`M` is an `m`-th cyclotomic extension of the field fixed by the cyclic subgroup the tag generates.

The divisibility is what makes the tag's cyclic subgroup meet the fixer of `K(μ_m)` trivially,
which is the hypothesis the general criterion needs. -/
theorem fixedField_zpowers_isCyclotomicExtension
    (hcop : ((NumberField.discr L).natAbs).Coprime m) {ζ : M} (hζ : IsPrimitiveRoot ζ m)
    (σ : Gal(L/K)) (τ : (ZMod m)ˣ) (hστ : orderOf σ ∣ orderOf τ) :
    IsCyclotomicExtension {m}
      (fixedField (Subgroup.zpowers ((galEquivProd K L M m hcop hζ).symm (σ, τ)))) M := by
  refine hζ.fixedField_isCyclotomicExtension_of_inf_fixingSubgroup_eq_bot _ ?_
  rw [hζ.fixingSubgroup_adjoin_nth_roots_eq_ker_autToPow,
    ker_autToPow_eq_comap_galEquivProd K L M m hcop hζ]
  ext x
  simp only [Subgroup.mem_inf, Subgroup.mem_comap, MulEquiv.coe_toMonoidHom,
    Subgroup.mem_bot]
  constructor
  · rintro ⟨⟨k, rfl⟩, hmem⟩
    have hzp : (galEquivProd K L M m hcop hζ) ((galEquivProd K L M m hcop hζ).symm (σ, τ) ^ k)
        = (σ, τ) ^ k := by
      rw [map_zpow, MulEquiv.apply_symm_apply]
    rw [hzp] at hmem
    have : ((σ, τ) : Gal(L/K) × (ZMod m)ˣ) ^ k = 1 := by
      have hbot := Subgroup.zpowers_inf_top_prod_bot_eq_bot_of_orderOf_dvd σ τ hστ
      have : ((σ, τ) : Gal(L/K) × (ZMod m)ˣ) ^ k ∈
          Subgroup.zpowers ((σ, τ) : Gal(L/K) × (ZMod m)ˣ) ⊓
            (⊤ : Subgroup Gal(L/K)).prod (⊥ : Subgroup (ZMod m)ˣ) :=
        ⟨⟨k, rfl⟩, hmem⟩
      rwa [hbot, Subgroup.mem_bot] at this
    have := congrArg (galEquivProd K L M m hcop hζ).symm this
    rwa [map_zpow, map_one] at this
  · rintro rfl
    exact ⟨one_mem _, by simp [Subgroup.mem_prod]⟩

end IsCyclotomicExtension
