/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.CoordinateRing
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.XYIdealMaximal
public import Mathlib.RingTheory.DedekindDomain.AdicValuation

/-!
# The place of an affine point of an elliptic curve

For an elliptic curve `W` over a field, the coordinate ring is a Dedekind domain and the ideal
`⟨X - x, Y - y(X)⟩` of a solution of the Weierstrass equation is maximal and nonzero. It is
therefore a point of `IsDedekindDomain.HeightOneSpectrum W.CoordinateRing`, which is Mathlib's
type of nonzero primes and carries the adic valuation on the function field.

## Main definitions

* `TauCeti.WeierstrassCurve.Affine.CoordinateRing.pointSpectrum`: the height-one prime attached to
  a solution of the Weierstrass equation.

## Main results

* `TauCeti.WeierstrassCurve.Affine.CoordinateRing.pointSpectrum_asIdeal`: its underlying ideal is
  `XYIdeal` (generated by `@[simps]`).

The order of vanishing at the point is then `(pointSpectrum h).valuation W.FunctionField`, with
Mathlib's `Valuation` API — multiplicativity, the ultrametric inequality, vanishing exactly at `0`,
and the existence of a uniformiser — available with no further work.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 0** (the function field, places, and divisors),
whose §Places asks for the affine places as the maximal ideals of the coordinate ring together with
an API of `ord_v` and uniformisers, and for the point–place dictionary. This is the direction that
sends a point to a place. The layer seeds no declaration this competes with, and records that the
design is coordinated with D. Angdinata's in-flight upstream `CoordinateRing` work.

## Provenance

Not a port. AINTLIB's `HasseWeil/Curves/Valuation.lean` builds an `ord_P` for its own
`SmoothPlaneCurve` wrapper with about twenty lemmas — multiplicativity, the ultrametric bound,
inverses, powers, uniformisers. None of that is reproduced: once the point is presented as a
`HeightOneSpectrum`, those are Mathlib's `Valuation.map_mul`, `Valuation.map_add`,
`Valuation.zero_iff`, `Valuation.map_inv`, `Valuation.map_add_of_distinct_val` and
`IsDedekindDomain.HeightOneSpectrum.valuation_exists_uniformizer`.
-/

public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain

namespace TauCeti

namespace WeierstrassCurve.Affine.CoordinateRing

variable {F : Type*} [Field F] {W : _root_.WeierstrassCurve.Affine F}
  [IsDedekindDomain W.CoordinateRing] {x : F}

/-- **The place of an affine point of an elliptic curve**: the ideal `⟨X - x, Y - y(X)⟩` as a
nonzero prime of the coordinate ring, for `y` solving the Weierstrass equation at `x`. The Dedekind
hypothesis is an instance argument; for an elliptic curve it is
`TauCeti.WeierstrassCurve.Affine.isDedekindDomain_coordinateRing`. -/
@[expose, simps]
noncomputable def pointSpectrum {y : F[X]} (h : (W.polynomial.eval y).eval x = 0) :
    HeightOneSpectrum W.CoordinateRing where
  asIdeal := CoordinateRing.XYIdeal W x y
  isPrime := (XYIdeal_isMaximal h).isPrime
  ne_bot := XYIdeal_ne_bot x y

end WeierstrassCurve.Affine.CoordinateRing

end TauCeti

end
