/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Basic
-- Proof-only, named in no statement here: the monic witness `Φₙ − C c * ΨSqₙ` with its root
-- equation, and the passage from an integral `x`-coordinate to an integral `y`-coordinate.
import TauCeti.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Integral
import TauCeti.AlgebraicGeometry.EllipticCurve.Integrality

/-!
# `[n]` maps infinity to infinity

`Isogeny/MulByInt/Basic.lean` builds the coordinate pullback of `[n]` and records that the
`MapsInfinity` condition — and so `[n]` as an `Isogeny W W` — is not proved there. This file
proves it, for every `n` with `ψₙ` nonvanishing at the generic point.

## The argument

`MapsInfinity` asks that every element of the coordinate ring, read in the function field, be
integral over the coordinate ring acting through the pullback. Three steps:

* the generic `x`-coordinate is integral, because `[n]*x · ΨSqₙ(x) = Φₙ(x)` is exactly the
  hypothesis of `isIntegral_of_mul_eval_ΨSq_eq_eval_Φ`, and `[n]*x` is the pullback of the class
  of `X`;
* the generic `y`-coordinate is then integral too, by `isIntegral_y_of_equation_of_isIntegral_x`
  applied at the generic point;
* every element of the coordinate ring lies in the subalgebra generated by the two coordinates
  (`algebraMap_mem_adjoin_genericX_genericY`), and integrality is preserved by the ring
  operations.

## Implementation notes

`W.FunctionField` carries two `Algebra W.CoordinateRing` structures once `[n]` is in play: the
canonical fraction-field embedding, and the one pulled back along `[n]`. Since `[n]` is an
endomorphism these have the same type, and the canonical one wins any type ascription that names
`IsIntegral W.CoordinateRing` or `IsScalarTower F W.CoordinateRing W.FunctionField`. The
integrality step below is therefore stated with `RingHom.IsIntegralElem` against a named
homomorphism, in which no `Algebra` instance occurs, and the final assembly closes under the
generators rather than passing through a scalar tower. `CoordinatePullback.MapsInfinity.map`
takes the tower route, which is available to it because its source and target curves differ.

## Main results

* `TauCeti.Isogeny.mulByIntX_mul_aeval_ΨSq`: the coordinate identity at the generic point.
* `TauCeti.Isogeny.mapsInfinity_mulByIntPullback`: the pullback of `[n]` maps infinity to
  infinity.
* `TauCeti.Isogeny.mulByIntIsogeny`: `[n]` as an `Isogeny W W`.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.4.

## Provenance

The integral witness is adapted from the AINTLIB `HasseWeil` project
(`github.com/CBirkbeck/AINTLIB`, Apache-2.0) pinned at
`513e83879e2f8cbc626eb9e04d660e92be16ccba`, `HasseWeil/MulByIntPullback.lean`, declaration
`mulByInt_x_transcendental`, which builds the same polynomial
`Φₙ.map (algebraMap F S) − C c * ΨSqₙ.map (algebraMap F S)` and the same root step, there to
contradict transcendence of the generic `x`-coordinate rather than to establish `MapsInfinity`.
Its monicity half is already in this repository as `monic_Φ_sub_C_mul_ΨSq`, itself ported from
that project's `NagellLutz`.

The `MapsInfinity` packaging is not from that source and has no counterpart in it: its `Isogeny`
carries a function-field `AlgHom` obtained by localizing an injective coordinate homomorphism,
with no pointedness field, so it never needs the `y`-coordinate step or the reduction to the two
coordinates.
-/

public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

open TauCeti.WeierstrassCurve.Affine.CoordinateRing (mk_C_eq_algebraMap)

namespace TauCeti

variable {F : Type*} [Field F] (W : WeierstrassCurve.Affine F)

namespace Isogeny

/-- **The coordinate identity at the generic point**: `[n]*x · ΨSqₙ(x) = Φₙ(x)`. -/
theorem mulByIntX_mul_aeval_ΨSq (n : ℤ) (hn : psiFunctionField W n ≠ 0) :
    mulByIntX W n * aeval W.genericX (W.ΨSq n) = aeval W.genericX (W.Φ n) := by
  have hphi : phiFunctionField W n = aeval W.genericX (W.Φ n) := by
    rw [phiFunctionField_eq_algebraMap, W.algebraMap_eq_aeval_genericX]
  have hpsi : psiFunctionField W n ^ 2 = aeval W.genericX (W.ΨSq n) := by
    rw [psiFunctionField_sq, mk_C_eq_algebraMap,
      ← IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField,
      W.algebraMap_eq_aeval_genericX]
  rw [← hphi, ← hpsi, mulByIntX_def]
  exact div_mul_cancel₀ _ (pow_ne_zero 2 hn)

-- Private: `mapsInfinity_mulByIntPullback` below states the stronger fact for every element of
-- the coordinate ring, so a consumer wanting this one specialises `mapsInfinity_iff` instead.
private theorem isIntegralElem_genericX [W.IsElliptic] {n : ℤ}
    (hn : psiFunctionField W n ≠ 0) :
    RingHom.IsIntegralElem (mulByIntPullback W hn).toRingHom W.genericX := by
  let _ : Algebra W.CoordinateRing W.FunctionField :=
    (mulByIntPullback W hn).toRingHom.toAlgebra
  have hmap : (algebraMap W.CoordinateRing W.FunctionField).comp
      (algebraMap F W.CoordinateRing) = algebraMap F W.FunctionField := by
    ext x; rw [RingHom.algebraMap_toAlgebra]; exact (mulByIntPullback W hn).commutes x
  refine TauCeti.WeierstrassCurve.isIntegral_of_mul_eval_ΨSq_eq_eval_Φ
    (W.map (algebraMap F W.CoordinateRing)) n (c := AdjoinRoot.of W.polynomial X) ?_
  have hx : algebraMap W.CoordinateRing W.FunctionField (AdjoinRoot.of W.polynomial X) =
      mulByIntX W n := mulByIntPullback_X W hn
  simp only [hx, _root_.WeierstrassCurve.baseChange, _root_.WeierstrassCurve.map_Φ,
    _root_.WeierstrassCurve.map_ΨSq, Polynomial.map_map, hmap, ← eval₂_eq_eval_map, ← aeval_def]
  exact mulByIntX_mul_aeval_ΨSq W n hn

/-- **The pullback of `[n]` maps infinity to infinity**, so `[n]` is an isogeny. -/
theorem mapsInfinity_mulByIntPullback [W.IsElliptic] {n : ℤ} (hn : psiFunctionField W n ≠ 0) :
    (mulByIntPullback W hn).MapsInfinity := by
  rw [CoordinatePullback.mapsInfinity_iff]
  let _ : Algebra W.CoordinateRing W.FunctionField :=
    (mulByIntPullback W hn).toRingHom.toAlgebra
  have halg : ∀ x : F, algebraMap F W.FunctionField x =
      algebraMap W.CoordinateRing W.FunctionField (algebraMap F W.CoordinateRing x) :=
    fun x ↦ ((mulByIntPullback W hn).commutes x).symm
  have hgx : IsIntegral W.CoordinateRing W.genericX := isIntegralElem_genericX W hn
  have hgy : IsIntegral W.CoordinateRing W.genericY :=
    TauCeti.WeierstrassCurve.isIntegral_y_of_equation_of_isIntegral_x
      (W.map (algebraMap F W.CoordinateRing))
      (by
        have hmap : (algebraMap W.CoordinateRing W.FunctionField).comp
            (algebraMap F W.CoordinateRing) = algebraMap F W.FunctionField := by
          ext x; exact (halg x).symm
        simpa only [_root_.WeierstrassCurve.baseChange, _root_.WeierstrassCurve.map_map, hmap]
          using W.equation_genericX_genericY) hgx
  -- `CoordinatePullback.MapsInfinity.map` finishes the analogous argument with an
  -- `IsScalarTower F W₂.CoordinateRing W₁.FunctionField` and `Algebra.adjoin_le` into a
  -- `restrictScalars`. That does NOT transfer here: `[n]` is an endomorphism, so
  -- `Algebra W.CoordinateRing W.FunctionField` already has the canonical fraction-field instance,
  -- which wins the tower's type ascription against the pullback one -- the ascription elaborates
  -- with `OreLocalization.instSMulOfIsScalarTower` while the term carries the local instance.
  -- Closing under the generators directly keeps every instance the one the goal names.
  have key : ∀ x ∈ Algebra.adjoin F ({W.genericX, W.genericY} : Set W.FunctionField),
      IsIntegral W.CoordinateRing x := by
    intro x hx
    induction hx using Algebra.adjoin_induction with
    | mem y hy => rcases hy with rfl | rfl
                  exacts [hgx, hgy]
    | algebraMap r => rw [halg r]; exact isIntegral_algebraMap
    | add y z _ _ hy hz => exact hy.add hz
    | mul y z _ _ hy hz => exact hy.mul hz
  exact fun z ↦ key _ (W.algebraMap_mem_adjoin_genericX_genericY z)

/-- **Multiplication by `n` as an isogeny**, for every `n` whose division polynomial does not
vanish at the generic point. -/
noncomputable def mulByIntIsogeny [W.IsElliptic] {n : ℤ} (hn : psiFunctionField W n ≠ 0) :
    _root_.TauCeti.Isogeny W W where
  pullback := mulByIntPullback W hn
  mapsInfinity := mapsInfinity_mulByIntPullback W hn

@[simp]
theorem mulByIntIsogeny_pullback [W.IsElliptic] {n : ℤ} (hn : psiFunctionField W n ≠ 0) :
    (mulByIntIsogeny W hn).pullback = mulByIntPullback W hn :=
  (rfl)

/-- **Multiplication by `n` as an isogeny, for every `n ≠ 0`**, the non-vanishing hypothesis
discharged by `psiFunctionField_ne_zero_of_Δ_ne_zero` as in `mulByIntPullbackOfNeZero`. -/
noncomputable abbrev mulByIntIsogenyOfNeZero [W.IsElliptic] {n : ℤ} (hn : n ≠ 0) :
    _root_.TauCeti.Isogeny W W :=
  mulByIntIsogeny W (psiFunctionField_ne_zero_of_Δ_ne_zero W W.isUnit_Δ.ne_zero hn)

end Isogeny

end TauCeti
