#!/usr/bin/env python3
"""toaddname.py --base <ref> <file.lean>... -- explicit `to_additive` targets on freshly rooted
declarations, which the rooting may have made redundant.

THE r687 RED BUILD, #6482.  The PR rooted one instance and CI failed on a line the PR did not even
change in substance:

    ConstMulAction.lean:32:14: `to_additive` correctly autogenerated target name for
    Submonoid.continuousConstSMul.

**The rooting is what broke it.**  Nested as `TauCeti.Submonoid.continuousConstSMul`, the attribute
needed an explicit target.  At root, `to_additive` derives `AddSubmonoid.continuousConstVAdd` from
`Submonoid.continuousConstSMul` on its own -- and naming a target it can autogenerate is an ERROR,
not a style note.  So a rooting can turn a correct attribute into a failing one without the
attribute changing at all.

WHY THE GATE CANNOT DECIDE THIS.  Whether the explicit name equals the autogenerated one depends on
Mathlib's `to_additive` translation dictionary (`Submonoid`->`AddSubmonoid`, `SMul`->`VAdd`, ...),
which lives in the elaborator.  This screen therefore does not answer the question; it ASKS it,
which is all that was needed -- the failure cost a full CI cycle and the answer is one line of
thought.  It fires only when a PR adds a `_root_.` declaration whose attribute block names a
`to_additive` target, so on most PRs it says nothing at all.
"""
import re, subprocess, sys, os

DECL = re.compile(r'^\s*(?:public\s+|private\s+|protected\s+|noncomputable\s+|nonrec\s+|scoped\s+)*'
                  r'(?:theorem|lemma|def|abbrev|instance|structure|class|inductive)\s+_root_\.'
                  r"([^\W\d][\w.'!?]*)")
# `@[to_additive Foo.bar ...]` -- an explicit TARGET NAME, as opposed to `@[to_additive]`,
# `@[to_additive (attr := simp)]` or `@[to_additive /-- doc -/]`, none of which name a target.
TOADD = re.compile(r'@\[\s*to_additive\s+(?!\(|/--|\]|$)([^\W\d][\w.\'!?]*)')


def findings(lines):
    """(attr_line_no, target, decl_name) for each rooted declaration with an explicit target.

    Pure so the controls can exercise it on fixture text without git or the network.  The attribute
    block may span several lines and carry a docstring, so the declaration is sought within a short
    window below the `@[to_additive` that opened it.
    """
    out = []
    for i, L in enumerate(lines):
        m = TOADD.search(L)
        if not m:
            continue
        for j in range(i, min(i + 8, len(lines))):
            d = DECL.match(lines[j])
            if d:
                out.append((i + 1, m.group(1), d.group(1)))
                break
    return out


def main():
    a = sys.argv[1:]
    base = None
    if a and a[0] == "--base":
        base, a = a[1], a[2:]
    if not a:
        print("# UNRUN: no files given.", file=sys.stderr); return 0
    hits, scanned = [], 0
    for f in a:
        if not os.path.exists(f):
            continue
        scanned += 1
        head = open(f, encoding="utf-8").read().split("\n")
        now = findings(head)
        if not now:
            continue
        # Only the ones this PR introduced: a declaration already rooted at the base was already
        # passing CI with that attribute, so it is not this PR's problem.
        was = set()
        if base:
            r = subprocess.run(["git", "show", f"{base}:{f}"], capture_output=True, text=True)
            if not r.returncode:
                was = {(t, d) for _i, t, d in findings(r.stdout.split("\n"))}
        for i, t, d in now:
            if (t, d) not in was:
                hits.append((f, i, t, d))
    for f, i, t, d in hits:
        print(f"TO-ADDITIVE  {f}:{i}\n"
              f"       `_root_.{d}` is rooted by this PR and its `@[to_additive]` names `{t}`.\n"
              f"       At root, `to_additive` may now derive that name itself -- and naming a target\n"
              f"       it can autogenerate is a CI ERROR, not a style note (#6482). Drop the target\n"
              f"       and keep the docstring, or confirm the derived name differs.")
    print(f"# FIRING CONTROL: {scanned} file(s) scanned, {len(hits)} rooted declaration(s) carrying "
          f"an explicit `to_additive` target. Most PRs have none. This screen ASKS the question; "
          f"only the elaborator knows Mathlib's translation dictionary.", file=sys.stderr)
    return 1 if hits else 0


if __name__ == "__main__":
    sys.exit(main())
