/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.Algebra.MvPolynomial.Eval
public import TauCeti.RingTheory.Huber.OpenIdeal
public import TauCeti.RingTheory.Localization.Away

/-!
# Over a Tate ring, the fractions of a rational subset generate the localisation

`TauCeti.Localization.adjoin_divBy_eq_top` says that the fractions `t/s` generate a localisation
away from `s` as soon as the numerators `T` generate the **unit ideal**. Over a Tate ring that
hypothesis is free: the condition a rational subset carries is that `T · A` be *open*, and an open
ideal of a Tate ring is `⊤` (`TauCeti.Huber.IsTateRing.eq_top_of_isOpen`).

This file records the two statements that combination gives, so a consumer in the rational-subset
setting does not repeat the derivation.

Nothing here is about the localisation *topology*: `S` carries no topology, and the Tate hypothesis
is used only on `A`, to turn openness into the unit ideal. That is why this file sits beside the
other Huber-ring results rather than under `LocalizationTopology`, whose subject is the topology
`TauCeti.Huber.locTopology` that plays no part here.

## Main results

* `TauCeti.Huber.adjoin_divBy_eq_top_of_isOpen`: the `A`-subalgebra of `Aₛ` generated by the
  fractions `t/s`, `t ∈ T`, is everything.
* `TauCeti.Huber.aeval_divBy_surjective_of_isOpen`: equivalently, evaluating a polynomial ring on
  one variable per numerator at those fractions is surjective onto `Aₛ`. This is the form a
  presentation consumes, and the reason the polynomial ring appears at all.

## What this is not

Both statements are about `Aₛ`, **before completion**. The corresponding statement about
`A⟨T/s⟩` — that the completed evaluation map out of `A⟨X₁, …, Xₖ⟩` is surjective, which is what
Wedhorn's Examples 6.38 and 6.39 assert — does not follow formally from these and is not proved
here.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Definition 7.29 for the
  openness condition on `T · A`, and §8.2 for the use.
-/

public section

namespace TauCeti.Huber

open TauCeti.Localization

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsTateRing A]
  (s : A) {S : Type*} [CommRing S] [Algebra A S] [IsLocalization.Away s S]

/-- **Over a Tate ring the fractions of a rational subset generate the localisation.** The
condition Wedhorn's rational subsets impose on the numerators is that `T · A` be open; a Tate ring
has no proper open ideal, so that says `T` generates the unit ideal.
`TauCeti.Localization.adjoin_divBy_eq_top` asks the denominator to be among the generators, which
follows since `Ideal.span T ≤ Ideal.span (insert s T)`; doing that step here is what saves a caller
holding only the rational-subset condition from doing it.

The Tate hypothesis is not decorative. Over `A = ℤ_p`, whose only open ideals are the `pⁿ`, the
ideal `(p)` is open and proper, `T = {p}` with `s = p` satisfies the openness condition, and the
fractions generate only `ℤ_p` rather than `ℤ_p[1/p]`. -/
theorem adjoin_divBy_eq_top_of_isOpen {T : Set A}
    (hT : IsOpen ((Ideal.span T : Ideal A) : Set A)) :
    Algebra.adjoin A (Set.range fun t : T ↦ (divBy (t : A) s : S)) = ⊤ :=
  adjoin_divBy_eq_top s <| eq_top_iff.mpr <|
    IsTateRing.eq_top_of_isOpen hT ▸ Ideal.span_mono (Set.subset_insert s T)

/-- **The polynomial presentation of `Aₛ`**: evaluating `A[Xₜ : t ∈ T]` at the fractions `t/s` is
surjective. The `Algebra.adjoin` form above says the same thing, and
`Algebra.adjoin_range_eq_range_aeval` is the translation; this is the form a presentation
consumes. -/
theorem aeval_divBy_surjective_of_isOpen {T : Set A}
    (hT : IsOpen ((Ideal.span T : Ideal A) : Set A)) :
    Function.Surjective (MvPolynomial.aeval (R := A) fun t : T ↦ (divBy (t : A) s : S)) := by
  rw [← AlgHom.range_eq_top, ← Algebra.adjoin_range_eq_range_aeval]
  exact adjoin_divBy_eq_top_of_isOpen s hT

end TauCeti.Huber

end
