/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RingTheory.Huber.RestrictedPowerSeries
public import Mathlib.Topology.Algebra.Nonarchimedean.Bases

/-!
# Weighted restricted power series `A⟨X⟩_T`

For a topological ring `A` and a family `T` of subsets of `A` indexed by the variables, Wedhorn
defines the *weighted* restricted power series ring

```text
A⟨X⟩_T := { ∑ aν Xν ∈ A[[X]] ; aν ∈ Tν · U for every open subgroup U of A and almost all ν },
```

with the subgroups `U⟨X⟩ := { ∑ aν Xν ∈ A⟨X⟩_T ; aν ∈ Tν · U for all ν }` as a fundamental
system of neighbourhoods of zero. Here `Tν := T₁^ν₁ ⋯ Tₖ^νₖ`. Taking every `Tᵢ = {1}` recovers
the ordinary restricted series `A⟨X⟩`.

## Main definitions

* `TauCeti.Huber.weightPow`: the subset `Tν = T₁^ν₁ ⋯ Tₖ^νₖ` of `A`.
* `TauCeti.Huber.weightMul`: the additive subgroup `Tν · U`.
* `TauCeti.Huber.IsWeightedRestricted`: Wedhorn's condition (5.6.1) on a power series.

## Main results

* `TauCeti.Huber.IsWeightedRestricted.mul`: `A⟨X⟩_T` is closed under multiplication, the point
  Wedhorn flags as not entirely clear; with the additive closure lemmas this gives the subring
  `TauCeti.Huber.weightedRestrictedSubring`.
* `TauCeti.Huber.weightedNhd_ringSubgroupsBasis` and `TauCeti.Huber.weightedTopology`: the
  `U⟨X⟩` are a fundamental system of neighbourhoods of zero for a ring topology, together with
  its contract (`weightedTopology_hasBasis_nhds_zero`, `weightedTopology_isTopologicalRing`,
  `weightedTopology_nonarchimedean`).
* `TauCeti.Huber.weightedRestrictedSubring_one`: for the trivial weight this is the ordinary
  ring of restricted power series (Wedhorn Example 5.54).

## Scope

Wedhorn states (5.6.1) for an arbitrary index set `I`. This file formalises the finite-variable
case `I = Fin k`, which is what the roadmap's Layer 0.4 target needs; an arbitrary-index version
would run the weight through `Finsupp.prod` over the (finite) support of `ν`.

## Implementation notes

`Tν · U` is read as the additive subgroup *generated by* the products `t * u`, not as the
pointwise product set. Wedhorn's own statement forces this: he asserts that the `U⟨X⟩` are a
fundamental system of neighbourhoods of zero for a *ring* topology, so each must be an additive
subgroup, and the pointwise set `{t * u}` is not closed under addition.

The predicate carries no nonarchimedean hypothesis, matching (5.6.1), but it only *means*
coefficient convergence when the open additive subgroups are a neighbourhood basis of zero — the
setting Wedhorn works in throughout §5.6. Without that it can be vacuous: over `ℝ` with its usual
topology the only open additive subgroup is `ℝ` itself, so every power series is `T`-restricted
for the trivial weight. `TauCeti.Huber.isWeightedRestricted_one_weight_iff` therefore assumes
`NonarchimedeanRing`.

If some `Tᵢ` is empty and `νᵢ > 0` then `Tν` is empty and `Tν · U = ⊥`, so the condition forces
those coefficients to vanish; the closure lemmas below need no nonemptiness hypothesis.

This is *not* `TauCeti/RingTheory/Huber/ScaledTateTopology.lean`, which retopologises the
ordinary `A⟨X⟩` by transporting along `X ↦ f X`; there the weight multiplies the coefficient
rather than the neighbourhood, and the carrier does not vary with `T`.

Closure of `A⟨X⟩_T` under multiplication is the one non-obvious point of the construction —
Wedhorn writes "note that it is not entirely clear that `A⟨X⟩_T` is multiplicatively closed" — and
is `TauCeti.Huber.IsWeightedRestricted.mul` here. It is exactly what the standing hypothesis is
for.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Remark and Definition 5.48, equation (5.6.1), and
  Example 5.54 for the case `Tᵢ = {1}`.
-/

open Filter Pointwise Topology

namespace TauCeti.Huber

public section

variable {k : ℕ} {A : Type*} [CommRing A] [TopologicalSpace A]

/-- The weight `Tν = T₁^ν₁ ⋯ Tₖ^νₖ` attached to a multi-index, as a subset of `A`. -/
def weightPow (T : Fin k → Set A) (ν : Fin k →₀ ℕ) : Set A := ∏ i, T i ^ ν i

omit [TopologicalSpace A] in
/-- Unfolding lemma for `TauCeti.Huber.weightPow`. -/
theorem weightPow_eq (T : Fin k → Set A) (ν : Fin k →₀ ℕ) :
    weightPow T ν = ∏ i, T i ^ ν i := (rfl)

/-- The additive subgroup `Tν · U` generated by the products of the weight with `U`. See the
module docstring: the subgroup, not the pointwise product set, is what Wedhorn's statement
requires. -/
def weightMul (T : Fin k → Set A) (ν : Fin k →₀ ℕ) (U : AddSubgroup A) : AddSubgroup A :=
  AddSubgroup.closure (weightPow T ν * (U : Set A))

omit [TopologicalSpace A] in
/-- Unfolding lemma for `TauCeti.Huber.weightMul`. -/
theorem weightMul_eq (T : Fin k → Set A) (ν : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul T ν U = AddSubgroup.closure (weightPow T ν * (U : Set A)) := (rfl)

/-- Wedhorn's standing hypothesis on the weight family, fixed at the start of his §5.6: for every
variable `i`, every `m`, and every neighbourhood `U` of zero, the subgroup `Tᵢ^m · U` is again a
neighbourhood of zero.

Without it `A⟨X⟩_T` is not multiplicatively closed. Take `A = ℚ_p⟨Y, Z⟩`, `T = {Y}`, `f = Z X`
and `g = ∑ₙ Yⁿ pⁿ Xⁿ`: both are `T`-restricted, but the `Xᵏ` coefficient of `f * g` is
`Z Yᵏ⁻¹ pᵏ⁻¹`, which never lies in `Tᵏ · A = Yᵏ A`. Note that there `A` is complete, Tate and
Huber and `T` is finite, bounded and power-bounded — so none of those conditions substitute for
this one. What fails is exactly that `Y A` is not open. -/
def IsWeightFamily (T : Fin k → Set A) : Prop :=
  ∀ (i : Fin k) (m : ℕ) (U : Set A), U ∈ nhds (0 : A) →
    (AddSubgroup.closure (T i ^ m * U) : Set A) ∈ nhds (0 : A)

/-- Unfolding lemma for `TauCeti.Huber.IsWeightFamily`. -/
theorem isWeightFamily_iff {T : Fin k → Set A} :
    IsWeightFamily T ↔ ∀ (i : Fin k) (m : ℕ) (U : Set A), U ∈ nhds (0 : A) →
      (AddSubgroup.closure (T i ^ m * U) : Set A) ∈ nhds (0 : A) := (Iff.rfl)

/-- **Wedhorn's automatic case**: the standing hypothesis holds when every weight consists of
units.

The nonemptiness hypothesis is not decoration. The empty set consists of units vacuously, but
`(∅ : Set A) ^ m` is empty for `m > 0`, so the subgroup it generates is `⊥`, which is a
neighbourhood of zero only for the discrete topology. -/
theorem IsWeightFamily.of_forall_isUnit [IsTopologicalRing A] {T : Fin k → Set A}
    (hne : ∀ i, (T i).Nonempty)
    (hu : ∀ i, ∀ t ∈ T i, IsUnit t) : IsWeightFamily T := by
  intro i m U hU
  obtain ⟨t, ht⟩ := hne i
  have hunit : IsUnit (t ^ m) := (hu i t ht).pow m
  have hsmul : (t ^ m) • U ∈ nhds (0 : A) := by
    have h := hunit.smul_mem_nhds_smul_iff (s := U) (a := (0 : A))
    rw [smul_zero] at h
    exact h.mpr hU
  refine Filter.mem_of_superset hsmul ?_
  rintro _ ⟨u, hu', rfl⟩
  exact AddSubgroup.subset_closure ⟨t ^ m, Set.pow_mem_pow ht, u, hu', by simp [smul_eq_mul]⟩

/-- Wedhorn: the standing hypothesis is automatic when every `Tᵢ` is `{1}`, the important special
case, since then `Tᵢ^m · U` is the subgroup generated by `U`. -/
theorem isWeightFamily_one : IsWeightFamily (fun _ : Fin k ↦ ({1} : Set A)) := by
  intro _ m U hU
  refine Filter.mem_of_superset hU fun u hu ↦ ?_
  exact AddSubgroup.subset_closure ⟨1, by simp, u, hu, by simp⟩

omit [TopologicalSpace A] in
/-- At the zero multi-index the weight is trivial, so `T⁰ · U` is just `U`; in particular it is a
neighbourhood of zero whenever `U` is. This is the base case of Wedhorn's remark that `Tν · U` is
a neighbourhood of zero for every `ν`. -/
theorem weightMul_zero (T : Fin k → Set A) (U : AddSubgroup A) :
    weightMul T 0 U = U := by
  rw [weightMul_eq, weightPow]
  simp

/-- Wedhorn (5.6.1): a power series is *`T`-restricted* if, for every open subgroup `U` of `A`,
all but finitely many of its coefficients lie in `Tν · U`. -/
def IsWeightedRestricted (T : Fin k → Set A) (f : MvPowerSeries (Fin k) A) : Prop :=
  ∀ U : OpenAddSubgroup A,
    ∀ᶠ ν in cofinite, MvPowerSeries.coeff ν f ∈ weightMul T ν U.toAddSubgroup

/-- Unfolding lemma for `TauCeti.Huber.IsWeightedRestricted`. -/
theorem isWeightedRestricted_iff {T : Fin k → Set A} {f : MvPowerSeries (Fin k) A} :
    IsWeightedRestricted T f ↔ ∀ U : OpenAddSubgroup A,
      ∀ᶠ ν in cofinite, MvPowerSeries.coeff ν f ∈ weightMul T ν U.toAddSubgroup := (Iff.rfl)

/-- The zero series is `T`-restricted. -/
@[simp]
theorem isWeightedRestricted_zero (T : Fin k → Set A) :
    IsWeightedRestricted T (0 : MvPowerSeries (Fin k) A) := by
  intro U
  filter_upwards with ν
  simp

/-- The one series is `T`-restricted: every coefficient but the constant one vanishes. -/
@[simp]
theorem isWeightedRestricted_one (T : Fin k → Set A) :
    IsWeightedRestricted T (1 : MvPowerSeries (Fin k) A) := by
  classical
  intro U
  filter_upwards [(Set.finite_singleton (0 : Fin k →₀ ℕ)).compl_mem_cofinite] with ν hν
  rw [MvPowerSeries.coeff_one, if_neg (by simpa using hν)]
  exact (weightMul T ν U.toAddSubgroup).zero_mem

omit [TopologicalSpace A] in
/-- Weights are multiplicative in the multi-index: `T^(α+β) = T^α · T^β`. This is the algebraic
identity that any proof of multiplicative closure has to run on. -/
theorem weightPow_add (T : Fin k → Set A) (α β : Fin k →₀ ℕ) :
    weightPow T (α + β) = weightPow T α * weightPow T β := by
  simp only [weightPow, Finsupp.add_apply, pow_add]
  exact Finset.prod_mul_distrib

omit [TopologicalSpace A] in
/-- A product of an element of `T^α · V` with an element of `T^β · W` lies in
`T^(α+β) · (V · W)`. Together with `TauCeti.Huber.weightPow_add` this is the algebraic half of
multiplicative closure; the analytic half — controlling the finitely many coefficients that fail
a given bound — is what Wedhorn flags as not entirely clear. -/
theorem weightMul_mul_mem {T : Fin k → Set A} {α β : Fin k →₀ ℕ} {V W : AddSubgroup A} {x y : A}
    (hx : x ∈ weightMul T α V) (hy : y ∈ weightMul T β W) :
    x * y ∈ weightMul T (α + β) (AddSubgroup.closure ((V : Set A) * (W : Set A))) := by
  induction hx using AddSubgroup.closure_induction with
  | mem u hu =>
      induction hy using AddSubgroup.closure_induction with
      | mem v hv =>
          obtain ⟨t, ht, a, ha, rfl⟩ := hu
          obtain ⟨t', ht', b, hb, rfl⟩ := hv
          refine AddSubgroup.subset_closure ⟨t * t', ?_, a * b, ?_, by ring⟩
          · rw [weightPow_add]
            exact Set.mul_mem_mul ht ht'
          · exact AddSubgroup.subset_closure (Set.mul_mem_mul ha hb)
      | zero => simp
      | add _ _ _ _ h₁ h₂ => simpa [mul_add] using (weightMul T (α + β) _).add_mem h₁ h₂
      | neg _ _ h => simpa [mul_neg] using (weightMul T (α + β) _).neg_mem h
  | zero => simp
  | add _ _ _ _ h₁ h₂ => simpa [add_mul] using (weightMul T (α + β) _).add_mem h₁ h₂
  | neg _ _ h => simpa [neg_mul] using (weightMul T (α + β) _).neg_mem h

omit [TopologicalSpace A] in
/-- `Tν · U` is monotone in `U`. -/
theorem weightMul_mono (T : Fin k → Set A) (ν : Fin k →₀ ℕ) {U V : AddSubgroup A} (h : U ≤ V) :
    weightMul T ν U ≤ weightMul T ν V :=
  AddSubgroup.closure_mono (Set.mul_subset_mul_left h)

omit [TopologicalSpace A] in
/-- Multiplying by a weight element shifts the multi-index: `T^β · (T^α · U) ⊆ T^(α+β) · U`. -/
theorem weightPow_mul_weightMul_mem {T : Fin k → Set A} {α β : Fin k →₀ ℕ} {U : AddSubgroup A}
    {t x : A} (ht : t ∈ weightPow T β) (hx : x ∈ weightMul T α U) :
    t * x ∈ weightMul T (α + β) U := by
  induction hx using AddSubgroup.closure_induction with
  | mem y hy =>
      obtain ⟨t', ht', u, hu, rfl⟩ := hy
      refine AddSubgroup.subset_closure ⟨t' * t, ?_, u, hu, by ring⟩
      rw [weightPow_add]
      exact Set.mul_mem_mul ht' ht
  | zero => simp
  | add _ _ _ _ h₁ h₂ => simpa [mul_add] using (weightMul T (α + β) U).add_mem h₁ h₂
  | neg _ _ h => simpa [mul_neg] using (weightMul T (α + β) U).neg_mem h

omit [TopologicalSpace A] in
/-- At a single-variable multi-index the weight is the corresponding power: `T^(single i m)` is
`Tᵢ ^ m`. This is what connects Wedhorn's per-variable standing hypothesis to the multi-index
statement he derives from it. -/
theorem weightPow_single (T : Fin k → Set A) (i : Fin k) (m : ℕ) :
    weightPow T (Finsupp.single i m) = T i ^ m := by
  rw [weightPow, Finset.prod_eq_single i]
  · simp
  · intro j _ hj
    simp [Ne.symm hj]
  · simp

omit [TopologicalSpace A] in
/-- Splitting a multi-index splits the weight subgroup: `T^(α+β) · U` is generated by `T^α`
against `T^β · U`. This is the step that lets the multi-index neighbourhood statement be proved
by induction from the per-variable one. -/
theorem weightMul_add_eq (T : Fin k → Set A) (α β : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul T (α + β) U
      = AddSubgroup.closure (weightPow T α * (weightMul T β U : Set A)) := by
  refine le_antisymm ?_ ?_
  · rw [weightMul_eq, AddSubgroup.closure_le]
    rintro _ ⟨t, ht, u, hu, rfl⟩
    rw [weightPow_add] at ht
    obtain ⟨a, ha, b, hb, rfl⟩ := ht
    exact AddSubgroup.subset_closure
      ⟨a, ha, b * u, AddSubgroup.subset_closure ⟨b, hb, u, hu, rfl⟩, by ring⟩
  · rw [AddSubgroup.closure_le]
    rintro _ ⟨t, ht, x, hx, rfl⟩
    exact add_comm α β ▸ weightPow_mul_weightMul_mem ht hx

/-- **Wedhorn's derived hypothesis**: from the per-variable assumption that each `Tᵢ^m · U` is a
neighbourhood of zero it follows that `Tν · U` is one for every multi-index `ν`. Wedhorn states
this in a sentence ("Then `Tν U` is a neighborhood of `0` for all `ν`"); the proof is induction
on `ν`, splitting off one variable at a time with
`TauCeti.Huber.weightMul_add_eq` and `TauCeti.Huber.weightPow_single`. -/
theorem IsWeightFamily.weightMul_mem_nhds {T : Fin k → Set A} (hT : IsWeightFamily T)
    (ν : Fin k →₀ ℕ) {U : AddSubgroup A} (hU : (U : Set A) ∈ nhds (0 : A)) :
    (weightMul T ν U : Set A) ∈ nhds (0 : A) := by
  induction ν using Finsupp.induction with
  | zero => rwa [weightMul_zero]
  | single_add i m ν' _ _ ih =>
      rw [weightMul_add_eq, weightPow_single]
      exact hT i m _ ih

/-- Multiplication by a fixed element is continuous, so any subgroup that is a neighbourhood of
zero absorbs it: there is an open subgroup `Z` with `a * Z ⊆ V`.

Applied with `V = Tα · U`, which
`TauCeti.Huber.IsWeightFamily.weightMul_mem_nhds` makes a neighbourhood of zero, this is what
produces the subgroup that `TauCeti.Huber.weightMul_absorb` consumes for a coefficient that fails
a given bound. -/
theorem exists_openAddSubgroup_mul_subset [NonarchimedeanRing A] (a : A)
    (V : AddSubgroup A) (hV : (V : Set A) ∈ nhds (0 : A)) :
    ∃ Z : OpenAddSubgroup A, ∀ z ∈ Z, a * z ∈ V := by
  have hmul : (fun x ↦ a * x) ⁻¹' (V : Set A) ∈ nhds (0 : A) :=
    (continuous_const.mul continuous_id).continuousAt.preimage_mem_nhds (by simpa using hV)
  obtain ⟨Z, hZ⟩ := NonarchimedeanAddGroup.is_nonarchimedean _ hmul
  exact ⟨Z, fun z hz ↦ hZ hz⟩

/-- The finite-family form of `TauCeti.Huber.exists_openAddSubgroup_mul_subset`: one open
subgroup `Z` absorbs each of finitely many fixed elements into its own target.

In the proof that `A⟨X⟩_T` is multiplicatively closed this is applied to the finitely many
coefficients that fail a given bound, producing the single subgroup against which the whole
antidiagonal is estimated. -/
theorem exists_openAddSubgroup_forall_mul_subset [NonarchimedeanRing A] {ι : Type*}
    (s : Finset ι) (a : ι → A) (V : ι → AddSubgroup A)
    (hV : ∀ i ∈ s, (V i : Set A) ∈ nhds (0 : A)) :
    ∃ Z : OpenAddSubgroup A, ∀ i ∈ s, ∀ z ∈ Z, a i * z ∈ V i := by
  classical
  induction s using Finset.induction with
  | empty => exact ⟨⊤, by simp⟩
  | insert i s' hi ih =>
      obtain ⟨Z', hZ'⟩ := ih fun j hj ↦ hV j (Finset.mem_insert_of_mem hj)
      obtain ⟨Z, hZ⟩ :=
        exists_openAddSubgroup_mul_subset (a i) (V i) (hV i (Finset.mem_insert_self i s'))
      refine ⟨Z ⊓ Z', fun j hj z hz ↦ ?_⟩
      rcases Finset.mem_insert.mp hj with rfl | hj'
      · exact hZ z hz.1
      · exact hZ' j hj' z hz.2

omit [TopologicalSpace A] in
/-- **The absorption step.** If multiplication by `a` carries the subgroup `Z` into `T^α · U`,
then it carries all of `T^β · Z` into `T^(α+β) · U`.

This is what handles the finitely many coefficients that fail a given bound in the proof that
`A⟨X⟩_T` is multiplicatively closed: Wedhorn's standing hypothesis
(`TauCeti.Huber.IsWeightFamily`) makes `T^α · U` a neighbourhood of zero, so continuity of
multiplication by the fixed bad coefficient `a` supplies such a `Z`. -/
theorem weightMul_absorb {T : Fin k → Set A} {α β : Fin k →₀ ℕ} {U Z : AddSubgroup A} {a b : A}
    (ha : ∀ z ∈ Z, a * z ∈ weightMul T α U) (hb : b ∈ weightMul T β Z) :
    a * b ∈ weightMul T (α + β) U := by
  induction hb using AddSubgroup.closure_induction with
  | mem y hy =>
      obtain ⟨t, ht, z, hz, rfl⟩ := hy
      rw [mul_left_comm]
      exact weightPow_mul_weightMul_mem ht (ha z hz)
  | zero => simp
  | add _ _ _ _ h₁ h₂ => simpa [mul_add] using (weightMul T (α + β) U).add_mem h₁ h₂
  | neg _ _ h => simpa [mul_neg] using (weightMul T (α + β) U).neg_mem h

omit [TopologicalSpace A] in
/-- With every weight equal to `{1}`, the weight of any multi-index is `{1}`. -/
@[simp]
theorem weightPow_one (ν : Fin k →₀ ℕ) :
    weightPow (fun _ : Fin k ↦ ({1} : Set A)) ν = {1} := by
  simp [weightPow]

omit [TopologicalSpace A] in
/-- With every weight equal to `{1}`, the subgroup `Tν · U` is `U` itself. -/
@[simp]
theorem weightMul_one (ν : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul (fun _ : Fin k ↦ ({1} : Set A)) ν U = U := by
  rw [weightMul_eq, weightPow_one, Set.singleton_mul]
  simp

/-- **Wedhorn Example 5.54**: for the trivial weight `Tᵢ = {1}` the condition is the ordinary
restrictedness of `A⟨X⟩`, that the coefficients tend to zero along the cofinite filter. This is
the nontrivial witness that `TauCeti.Huber.IsWeightedRestricted` is not vacuous. -/
theorem isWeightedRestricted_one_weight_iff [NonarchimedeanRing A]
    {f : MvPowerSeries (Fin k) A} :
    IsWeightedRestricted (fun _ : Fin k ↦ ({1} : Set A)) f ↔
      Tendsto (fun ν ↦ MvPowerSeries.coeff ν f) cofinite (nhds 0) := by
  rw [isWeightedRestricted_iff]
  constructor
  · intro h
    rw [tendsto_nhds]
    intro V hV h0V
    obtain ⟨U, hUV⟩ := NonarchimedeanAddGroup.is_nonarchimedean V (hV.mem_nhds h0V)
    filter_upwards [h U] with ν hν
    exact hUV (by simpa using hν)
  · intro h U
    have := (tendsto_nhds.mp h) _ U.isOpen (SetLike.mem_coe.mpr U.zero_mem)
    filter_upwards [this] with ν hν
    simpa using hν

/-- Anything with only finitely many nonzero coefficients is `T`-restricted, whatever the weight:
the zero coefficients meet every bound. This is the source of all the polynomial constructors
below. -/
theorem isWeightedRestricted_of_finite_support (T : Fin k → Set A)
    {f : MvPowerSeries (Fin k) A} (h : {ν | MvPowerSeries.coeff ν f ≠ 0}.Finite) :
    IsWeightedRestricted T f := by
  intro U
  rw [Filter.eventually_cofinite]
  refine h.subset fun ν hν ↦ ?_
  simp only [Set.mem_ofPred_eq] at hν ⊢
  exact fun hz ↦ hν (hz ▸ (weightMul T ν U.toAddSubgroup).zero_mem)

/-- A monomial is `T`-restricted. -/
@[simp]
theorem isWeightedRestricted_monomial (T : Fin k → Set A) (μ : Fin k →₀ ℕ) (a : A) :
    IsWeightedRestricted T (MvPowerSeries.monomial μ a) := by
  classical
  refine isWeightedRestricted_of_finite_support T ((Set.finite_singleton μ).subset fun ν hν ↦ ?_)
  simp only [Set.mem_ofPred_eq, MvPowerSeries.coeff_monomial] at hν
  by_contra hne
  simp only [Set.mem_singleton_iff] at hne
  exact hν (if_neg hne)

/-- A constant series is `T`-restricted. -/
@[simp]
theorem isWeightedRestricted_C (T : Fin k → Set A) (a : A) :
    IsWeightedRestricted T (MvPowerSeries.C a) := by
  simpa using isWeightedRestricted_monomial T 0 a

/-- Each variable is `T`-restricted. -/
@[simp]
theorem isWeightedRestricted_X (T : Fin k → Set A) (i : Fin k) :
    IsWeightedRestricted T (MvPowerSeries.X i : MvPowerSeries (Fin k) A) := by
  classical
  exact isWeightedRestricted_monomial T (Finsupp.single i 1) (1 : A)

/-- A sum of `T`-restricted series is `T`-restricted. -/
theorem IsWeightedRestricted.add {T : Fin k → Set A} {f g : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) (hg : IsWeightedRestricted T g) :
    IsWeightedRestricted T (f + g) := by
  intro U
  filter_upwards [hf U, hg U] with ν hfν hgν
  simpa using (weightMul T ν U.toAddSubgroup).add_mem hfν hgν

/-- **`A⟨X⟩_T` is closed under multiplication** (Wedhorn 5.48, the point he flags as "not
entirely clear").

Fix an open subgroup `U` and choose `W` with `W · W ⊆ U`. The coefficients of `f` and `g` that
fail the `W` bound form finite sets `F` and `G`. Wedhorn's standing hypothesis makes each
`Tα · U` a neighbourhood of zero, so one open subgroup `Z ≤ W` absorbs every bad coefficient into
its own `Tα · U`. Writing `F_Z`, `G_Z` for the bad sets against `Z`, put
`E = (F + G_Z) ∪ (F_Z + G)`, a finite set. For `ν ∉ E` every splitting `α + β = ν` falls into one
of three cases — `α` bad, `β` bad, or neither — and each lands in `Tν · U`. -/
theorem IsWeightedRestricted.mul [NonarchimedeanRing A] {T : Fin k → Set A}
    (hT : IsWeightFamily T) {f g : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) (hg : IsWeightedRestricted T g) :
    IsWeightedRestricted T (f * g) := by
  classical
  intro U
  have hUnhds : (U : Set A) ∈ nhds (0 : A) := U.isOpen.mem_nhds U.zero_mem
  obtain ⟨W, hWU⟩ := NonarchimedeanRing.mul_subset U
  have hF : {α | MvPowerSeries.coeff α f ∉ weightMul T α W.toAddSubgroup}.Finite :=
    Filter.eventually_cofinite.mp (hf W)
  have hG : {β | MvPowerSeries.coeff β g ∉ weightMul T β W.toAddSubgroup}.Finite :=
    Filter.eventually_cofinite.mp (hg W)
  obtain ⟨Zf, hZf⟩ := exists_openAddSubgroup_forall_mul_subset hF.toFinset
    (fun α ↦ MvPowerSeries.coeff α f) (fun α ↦ weightMul T α U.toAddSubgroup)
    (fun α _ ↦ hT.weightMul_mem_nhds α hUnhds)
  obtain ⟨Zg, hZg⟩ := exists_openAddSubgroup_forall_mul_subset hG.toFinset
    (fun β ↦ MvPowerSeries.coeff β g) (fun β ↦ weightMul T β U.toAddSubgroup)
    (fun β _ ↦ hT.weightMul_mem_nhds β hUnhds)
  set Z : OpenAddSubgroup A := W ⊓ Zf ⊓ Zg with hZdef
  have hZle_f : Z ≤ Zf := le_trans inf_le_left inf_le_right
  have hZle_g : Z ≤ Zg := inf_le_right
  have hFZ : {α | MvPowerSeries.coeff α f ∉ weightMul T α Z.toAddSubgroup}.Finite :=
    Filter.eventually_cofinite.mp (hf Z)
  have hGZ : {β | MvPowerSeries.coeff β g ∉ weightMul T β Z.toAddSubgroup}.Finite :=
    Filter.eventually_cofinite.mp (hg Z)
  rw [Filter.eventually_cofinite]
  refine Set.Finite.subset ((hF.add hGZ).union (hFZ.add hG)) ?_
  intro ν hν
  by_contra hνE
  refine hν ?_
  rw [MvPowerSeries.coeff_mul]
  refine sum_mem fun p hp ↦ ?_
  have hsum : p.1 + p.2 = ν := Finset.mem_antidiagonal.mp hp
  by_cases hp1 : MvPowerSeries.coeff p.1 f ∈ weightMul T p.1 W.toAddSubgroup
  · by_cases hp2 : MvPowerSeries.coeff p.2 g ∈ weightMul T p.2 W.toAddSubgroup
    · -- both coefficients meet the `W` bound
      have := weightMul_mul_mem hp1 hp2
      rw [hsum] at this
      exact weightMul_mono T ν (AddSubgroup.closure_le _ |>.mpr hWU) this
    · -- `p.2` is bad: absorb it, after commuting
      have hgood : MvPowerSeries.coeff p.1 f ∈ weightMul T p.1 Z.toAddSubgroup := by
        by_contra hbad
        exact hνE (Or.inr ⟨p.1, hbad, p.2, hp2, hsum⟩)
      have := weightMul_absorb
        (fun z hz ↦ hZg p.2 (hG.mem_toFinset.mpr hp2) z (hZle_g hz))
        hgood
      rw [mul_comm, add_comm, hsum] at this
      exact this
  · -- `p.1` is bad: absorb it
    have hgood : MvPowerSeries.coeff p.2 g ∈ weightMul T p.2 Z.toAddSubgroup := by
      by_contra hbad
      exact hνE (Or.inl ⟨p.1, hp1, p.2, hbad, hsum⟩)
    have := weightMul_absorb
      (fun z hz ↦ hZf p.1 (hF.mem_toFinset.mpr hp1) z (hZle_f hz))
      hgood
    rw [hsum] at this
    exact this

/-- The negation of a `T`-restricted series is `T`-restricted. -/
theorem IsWeightedRestricted.neg {T : Fin k → Set A} {f : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) : IsWeightedRestricted T (-f) := by
  intro U
  filter_upwards [hf U] with ν hfν
  simpa using (weightMul T ν U.toAddSubgroup).neg_mem hfν

omit [TopologicalSpace A] in
/-- If *every* coefficient of `f` meets the `V` bound and every coefficient of `g` meets the `W`
bound, then every coefficient of `f * g` meets the `V · W` bound.

Unlike `TauCeti.Huber.IsWeightedRestricted.mul` this needs no finiteness bookkeeping — there are
no exceptional coefficients — which is why it is the form the neighbourhood subgroups use. -/
theorem coeff_mul_mem_weightMul {T : Fin k → Set A} {V W : AddSubgroup A}
    {f g : MvPowerSeries (Fin k) A}
    (hf : ∀ α, MvPowerSeries.coeff α f ∈ weightMul T α V)
    (hg : ∀ β, MvPowerSeries.coeff β g ∈ weightMul T β W) (ν : Fin k →₀ ℕ) :
    MvPowerSeries.coeff ν (f * g)
      ∈ weightMul T ν (AddSubgroup.closure ((V : Set A) * (W : Set A))) := by
  classical
  rw [MvPowerSeries.coeff_mul]
  refine sum_mem fun p hp ↦ ?_
  have hsum : p.1 + p.2 = ν := Finset.mem_antidiagonal.mp hp
  exact hsum ▸ weightMul_mul_mem (hf p.1) (hg p.2)

/-! ### The ring `A⟨X⟩_T` -/

/-- **Wedhorn's `A⟨X⟩_T`**: the weighted restricted power series form a subring of `A[[X]]`.

The weight family must satisfy Wedhorn's standing hypothesis
(`TauCeti.Huber.IsWeightFamily`); without it the carrier is not closed under multiplication, and
the docstring of that definition records the counterexample. -/
def weightedRestrictedSubring [NonarchimedeanRing A] (T : Fin k → Set A) (hT : IsWeightFamily T) :
    Subring (MvPowerSeries (Fin k) A) where
  carrier := {f | IsWeightedRestricted T f}
  mul_mem' := IsWeightedRestricted.mul hT
  one_mem' := isWeightedRestricted_one T
  add_mem' := IsWeightedRestricted.add
  zero_mem' := isWeightedRestricted_zero T
  neg_mem' := IsWeightedRestricted.neg

/-- Membership in `A⟨X⟩_T` is `T`-restrictedness. -/
@[simp]
theorem mem_weightedRestrictedSubring [NonarchimedeanRing A] {T : Fin k → Set A}
    {hT : IsWeightFamily T} {f : MvPowerSeries (Fin k) A} :
    f ∈ weightedRestrictedSubring T hT ↔ IsWeightedRestricted T f := (Iff.rfl)

/-- The constant-series embedding `A → A⟨X⟩_T`. -/
noncomputable def weightedC [NonarchimedeanRing A] (T : Fin k → Set A) (hT : IsWeightFamily T) :
    A →+* weightedRestrictedSubring T hT where
  toFun a := ⟨MvPowerSeries.C a, isWeightedRestricted_C T a⟩
  map_one' := by ext; simp
  map_mul' _ _ := by ext; simp
  map_zero' := by ext; simp
  map_add' _ _ := by ext; simp

@[simp]
theorem coe_weightedC [NonarchimedeanRing A] {T : Fin k → Set A} {hT : IsWeightFamily T} (a : A) :
    (weightedC T hT a : MvPowerSeries (Fin k) A) = MvPowerSeries.C a := (rfl)

/-- The variable `Xᵢ`, as an element of `A⟨X⟩_T`. -/
noncomputable def weightedX [NonarchimedeanRing A] (T : Fin k → Set A) (hT : IsWeightFamily T)
    (i : Fin k) :
    weightedRestrictedSubring T hT :=
  ⟨MvPowerSeries.X i, isWeightedRestricted_X T i⟩

@[simp]
theorem coe_weightedX [NonarchimedeanRing A] {T : Fin k → Set A} {hT : IsWeightFamily T}
    (i : Fin k) :
    (weightedX T hT i : MvPowerSeries (Fin k) A) = MvPowerSeries.X i := (rfl)

/-- `A⟨X⟩_T` is an `A`-algebra, via the constant series. -/
noncomputable instance weightedRestrictedSubring.instAlgebra [NonarchimedeanRing A]
    (T : Fin k → Set A) (hT : IsWeightFamily T) : Algebra A (weightedRestrictedSubring T hT) :=
  (weightedC T hT).toAlgebra

@[simp]
theorem coe_algebraMap_weightedRestrictedSubring [NonarchimedeanRing A] {T : Fin k → Set A}
    {hT : IsWeightFamily T} (a : A) :
    ((algebraMap A (weightedRestrictedSubring T hT) a : weightedRestrictedSubring T hT) :
      MvPowerSeries (Fin k) A) = MvPowerSeries.C a := (rfl)

/-- **Wedhorn's neighbourhood subgroups** `U⟨X⟩`: the series all of whose coefficients — not
merely almost all — satisfy the `U` bound. These are the fundamental system of neighbourhoods of
zero for the topology on `A⟨X⟩_T`. -/
def weightedNhd [NonarchimedeanRing A] (T : Fin k → Set A) (hT : IsWeightFamily T)
    (U : AddSubgroup A) : AddSubgroup (weightedRestrictedSubring T hT) where
  carrier := {f | ∀ ν, MvPowerSeries.coeff ν (f : MvPowerSeries (Fin k) A) ∈ weightMul T ν U}
  add_mem' hf hg ν := by simpa using (weightMul T ν U).add_mem (hf ν) (hg ν)
  zero_mem' ν := by simp
  neg_mem' hf ν := by simpa using (weightMul T ν U).neg_mem (hf ν)

/-- Membership in `U⟨X⟩` is the `U` bound on every coefficient. -/
@[simp]
theorem mem_weightedNhd [NonarchimedeanRing A] {T : Fin k → Set A} {hT : IsWeightFamily T}
    {U : AddSubgroup A} {f : weightedRestrictedSubring T hT} :
    f ∈ weightedNhd T hT U ↔
      ∀ ν, MvPowerSeries.coeff ν (f : MvPowerSeries (Fin k) A) ∈ weightMul T ν U := (Iff.rfl)

/-- **Wedhorn Example 5.54, bundled**: for the trivial weight, `A⟨X⟩_T` *is* the ordinary ring of
restricted power series, not merely a predicate-level equivalent. -/
theorem weightedRestrictedSubring_one [NonarchimedeanRing A] :
    weightedRestrictedSubring (fun _ : Fin k ↦ ({1} : Set A)) isWeightFamily_one
      = restrictedMvPowerSeriesSubring k A := by
  ext f
  rw [mem_weightedRestrictedSubring, mem_restrictedMvPowerSeriesSubring,
    isWeightedRestricted_one_weight_iff, isRestricted_iff]

/-- The neighbourhood subgroups are antitone in `U`. -/
theorem weightedNhd_mono [NonarchimedeanRing A] {T : Fin k → Set A} {hT : IsWeightFamily T}
    {U V : AddSubgroup A} (h : U ≤ V) : weightedNhd T hT U ≤ weightedNhd T hT V :=
  fun _ hf ν ↦ weightMul_mono T ν h (hf ν)

/-- **The multiplicative half of the neighbourhood basis**: if `W · W ⊆ U` then the product of two
elements of `W⟨X⟩` lies in `U⟨X⟩`. This is the condition
`RingSubgroupsBasis` calls `mul`, and unlike multiplicative closure of the ring it needs no
finiteness argument. -/
theorem weightedNhd_mul_subset [NonarchimedeanRing A] {T : Fin k → Set A}
    {hT : IsWeightFamily T} {W U : AddSubgroup A} (hWU : (W : Set A) * (W : Set A) ⊆ (U : Set A))
    {f g : weightedRestrictedSubring T hT} (hf : f ∈ weightedNhd T hT W)
    (hg : g ∈ weightedNhd T hT W) : f * g ∈ weightedNhd T hT U := by
  intro ν
  have := coeff_mul_mem_weightMul (T := T) (V := W) (W := W) hf hg ν
  exact weightMul_mono T ν ((AddSubgroup.closure_le _).mpr hWU) this

/-- **The left-multiplication half of the neighbourhood basis**: for a fixed `x ∈ A⟨X⟩_T` and an
open subgroup `U`, some `V⟨X⟩` is carried into `U⟨X⟩` by multiplication by `x`. This is the
condition `RingSubgroupsBasis` calls `leftMul`.

Unlike `TauCeti.Huber.weightedNhd_mul_subset` this does need the bad coefficients of `x` handled,
since `x` is only restricted rather than uniformly bounded — but no exceptional set of `ν`
survives, because the absorbing subgroup works for every `β` at once. -/
theorem weightedNhd_leftMul [NonarchimedeanRing A] {T : Fin k → Set A} (hT : IsWeightFamily T)
    (x : weightedRestrictedSubring T hT) (U : OpenAddSubgroup A) :
    ∃ V : OpenAddSubgroup A, ∀ g : weightedRestrictedSubring T hT,
      g ∈ weightedNhd T hT V.toAddSubgroup → x * g ∈ weightedNhd T hT U.toAddSubgroup := by
  classical
  have hUnhds : (U : Set A) ∈ nhds (0 : A) := U.isOpen.mem_nhds U.zero_mem
  obtain ⟨W, hWU⟩ := NonarchimedeanRing.mul_subset U
  have hx : IsWeightedRestricted T (x : MvPowerSeries (Fin k) A) := x.2
  have hF : {α | MvPowerSeries.coeff α (x : MvPowerSeries (Fin k) A)
      ∉ weightMul T α W.toAddSubgroup}.Finite := Filter.eventually_cofinite.mp (hx W)
  obtain ⟨Zx, hZx⟩ := exists_openAddSubgroup_forall_mul_subset hF.toFinset
    (fun α ↦ MvPowerSeries.coeff α (x : MvPowerSeries (Fin k) A))
    (fun α ↦ weightMul T α U.toAddSubgroup) (fun α _ ↦ hT.weightMul_mem_nhds α hUnhds)
  refine ⟨W ⊓ Zx, fun g hg ν ↦ ?_⟩
  have hZleW : (W ⊓ Zx : OpenAddSubgroup A) ≤ W := inf_le_left
  have hZleZx : (W ⊓ Zx : OpenAddSubgroup A) ≤ Zx := inf_le_right
  rw [Subring.coe_mul, MvPowerSeries.coeff_mul]
  refine sum_mem fun p hp ↦ ?_
  have hsum : p.1 + p.2 = ν := Finset.mem_antidiagonal.mp hp
  by_cases hp1 : MvPowerSeries.coeff p.1 (x : MvPowerSeries (Fin k) A)
      ∈ weightMul T p.1 W.toAddSubgroup
  · -- `p.1` meets the `W` bound, and every coefficient of `g` meets the `W ⊓ Zx` bound
    have hp2 : MvPowerSeries.coeff p.2 (g : MvPowerSeries (Fin k) A)
        ∈ weightMul T p.2 W.toAddSubgroup :=
      weightMul_mono T p.2 hZleW (hg p.2)
    have := weightMul_mul_mem hp1 hp2
    rw [hsum] at this
    exact weightMul_mono T ν ((AddSubgroup.closure_le _).mpr hWU) this
  · -- `p.1` is one of the finitely many bad coefficients: absorb it
    have := weightMul_absorb
      (fun z hz ↦ hZx p.1 (hF.mem_toFinset.mpr hp1) z (hZleZx hz))
      (weightMul_mono T p.2 (le_refl _) (hg p.2))
    rw [hsum] at this
    exact this

/-- **The neighbourhood basis of `A⟨X⟩_T`**: the subgroups `U⟨X⟩`, as `U` ranges over the open
subgroups of `A`, are a `RingSubgroupsBasis`. This is Wedhorn's assertion that they form a
fundamental system of neighbourhoods of zero for a ring topology. -/
theorem weightedNhd_ringSubgroupsBasis [NonarchimedeanRing A] {T : Fin k → Set A}
    (hT : IsWeightFamily T) :
    RingSubgroupsBasis fun U : OpenAddSubgroup A ↦ weightedNhd T hT U.toAddSubgroup :=
  .of_comm _
    (fun U V ↦ ⟨U ⊓ V, le_inf (weightedNhd_mono inf_le_left) (weightedNhd_mono inf_le_right)⟩)
    (fun U ↦ by
      obtain ⟨W, hWU⟩ := NonarchimedeanRing.mul_subset U
      exact ⟨W, by
        rintro _ ⟨f, hf, g, hg, rfl⟩
        exact weightedNhd_mul_subset hWU hf hg⟩)
    (fun x U ↦ by
      obtain ⟨V, hV⟩ := weightedNhd_leftMul hT x U
      exact ⟨V, fun g hg ↦ hV g hg⟩)

/-- **Wedhorn's topology on `A⟨X⟩_T`** (Remark and Definition 5.48): the ring topology whose
neighbourhoods of zero are the `U⟨X⟩`.

Consumers should go through the contract lemmas below rather than unfolding this: the basis is
`weightedTopology_hasBasis_nhds_zero`, and `weightedTopology_isTopologicalRing` /
`weightedTopology_nonarchimedean` give the structure. `@[instance_reducible]` rather than plain
`@[reducible]` is what the `classDefReducibility` linter requires of a class-valued `def`; it
opens the body to instance synthesis only, not to general definitional unfolding. -/
@[instance_reducible]
noncomputable def weightedTopology [NonarchimedeanRing A] {T : Fin k → Set A}
    (hT : IsWeightFamily T) : TopologicalSpace (weightedRestrictedSubring T hT) :=
  (weightedNhd_ringSubgroupsBasis hT).topology

/-- The `U⟨X⟩` are a basis of neighbourhoods of zero for `weightedTopology`. -/
theorem weightedTopology_hasBasis_nhds_zero [NonarchimedeanRing A] {T : Fin k → Set A}
    (hT : IsWeightFamily T) :
    (@nhds _ (weightedTopology hT) 0).HasBasis (fun _ : OpenAddSubgroup A ↦ True)
      fun U ↦ (weightedNhd T hT U.toAddSubgroup : Set (weightedRestrictedSubring T hT)) :=
  (weightedNhd_ringSubgroupsBasis hT).hasBasis_nhds_zero

/-- `weightedTopology` is a ring topology. -/
theorem weightedTopology_isTopologicalRing [NonarchimedeanRing A] {T : Fin k → Set A}
    (hT : IsWeightFamily T) :
    @IsTopologicalRing _ (weightedTopology hT) _ :=
  (weightedNhd_ringSubgroupsBasis hT).toRingFilterBasis.isTopologicalRing

/-- `weightedTopology` is nonarchimedean: `A⟨X⟩_T` inherits a basis of open additive subgroups at
zero, as every ring built from a `RingSubgroupsBasis` does. -/
theorem weightedTopology_nonarchimedean [NonarchimedeanRing A] {T : Fin k → Set A}
    (hT : IsWeightFamily T) :
    @NonarchimedeanRing _ _ (weightedTopology hT) :=
  (weightedNhd_ringSubgroupsBasis hT).nonarchimedean

end

end TauCeti.Huber
