/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.MvPowerSeries.Basic
public import Mathlib.Topology.Algebra.Nonarchimedean.Basic

/-!
# Weighted restricted power series `A⟨X⟩_T`

For a topological ring `A` and a family `T` of subsets of `A` indexed by the variables, Wedhorn
defines the *weighted* restricted power series ring

```text
A⟨X⟩_T := { ∑ aν Xν ∈ A[[X]] ; aν ∈ Tν · U for every open subgroup U of A and almost all ν },
```

with the subgroups `U⟨X⟩ := { ∑ aν Xν ∈ A⟨X⟩_T ; aν ∈ Tν · U for all ν }` as a fundamental
system of neighbourhoods of zero. Here `Tν := T₁^ν₁ ⋯ Tₖ^νₖ`. Taking every `Tᵢ = {1}` recovers
the ordinary restricted series `A⟨X⟩`.

## Main definitions

* `TauCeti.Huber.weightPow`: the subset `Tν = T₁^ν₁ ⋯ Tₖ^νₖ` of `A`.
* `TauCeti.Huber.weightMul`: the additive subgroup `Tν · U`.
* `TauCeti.Huber.IsWeightedRestricted`: Wedhorn's condition (5.6.1) on a power series.

## Main results

* `TauCeti.Huber.isWeightedRestricted_zero`, `TauCeti.Huber.isWeightedRestricted_one`,
  `TauCeti.Huber.IsWeightedRestricted.add`, `TauCeti.Huber.IsWeightedRestricted.neg`: the
  condition is closed under the additive-group operations.

## Implementation notes

`Tν · U` is read as the additive subgroup *generated by* the products `t * u`, not as the
pointwise product set. Wedhorn's own statement forces this: he asserts that the `U⟨X⟩` are a
fundamental system of neighbourhoods of zero for a *ring* topology, so each must be an additive
subgroup, and the pointwise set `{t * u}` is not closed under addition.

The predicate carries no nonarchimedean hypothesis, matching (5.6.1), but it only *means*
coefficient convergence when the open additive subgroups are a neighbourhood basis of zero — the
setting Wedhorn works in throughout §5.6. Without that it can be vacuous: over `ℝ` with its usual
topology the only open additive subgroup is `ℝ` itself, so every power series is `T`-restricted
for the trivial weight. `TauCeti.Huber.isWeightedRestricted_one_weight_iff` therefore assumes
`NonarchimedeanRing`.

If some `Tᵢ` is empty and `νᵢ > 0` then `Tν` is empty and `Tν · U = ⊥`, so the condition forces
those coefficients to vanish; the closure lemmas below need no nonemptiness hypothesis.

This is *not* `TauCeti/RingTheory/Huber/ScaledTateTopology.lean`, which retopologises the
ordinary `A⟨X⟩` by transporting along `X ↦ f X`; there the weight multiplies the coefficient
rather than the neighbourhood, and the carrier does not vary with `T`.

Closure of `A⟨X⟩_T` under multiplication is not yet formalised. Wedhorn flags it as the one
non-obvious point of the construction ("note that it is not entirely clear that `A⟨X⟩_T` is
multiplicatively closed").

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Remark and Definition 5.48, equation (5.6.1), and
  Example 5.54 for the case `Tᵢ = {1}`.
-/

open Filter Pointwise Topology

namespace TauCeti.Huber

public section

variable {k : ℕ} {A : Type*} [CommRing A] [TopologicalSpace A]

/-- The weight `Tν = T₁^ν₁ ⋯ Tₖ^νₖ` attached to a multi-index, as a subset of `A`. -/
def weightPow (T : Fin k → Set A) (ν : Fin k →₀ ℕ) : Set A := ∏ i, T i ^ ν i

omit [TopologicalSpace A] in
/-- Unfolding lemma for `TauCeti.Huber.weightPow`. -/
theorem weightPow_eq (T : Fin k → Set A) (ν : Fin k →₀ ℕ) :
    weightPow T ν = ∏ i, T i ^ ν i := (rfl)

/-- The additive subgroup `Tν · U` generated by the products of the weight with `U`. See the
module docstring: the subgroup, not the pointwise product set, is what Wedhorn's statement
requires. -/
def weightMul (T : Fin k → Set A) (ν : Fin k →₀ ℕ) (U : AddSubgroup A) : AddSubgroup A :=
  AddSubgroup.closure (weightPow T ν * (U : Set A))

omit [TopologicalSpace A] in
/-- Unfolding lemma for `TauCeti.Huber.weightMul`. -/
theorem weightMul_eq (T : Fin k → Set A) (ν : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul T ν U = AddSubgroup.closure (weightPow T ν * (U : Set A)) := (rfl)

/-- Wedhorn (5.6.1): a power series is *`T`-restricted* if, for every open subgroup `U` of `A`,
all but finitely many of its coefficients lie in `Tν · U`. -/
def IsWeightedRestricted (T : Fin k → Set A) (f : MvPowerSeries (Fin k) A) : Prop :=
  ∀ U : OpenAddSubgroup A,
    ∀ᶠ ν in cofinite, MvPowerSeries.coeff ν f ∈ weightMul T ν U.toAddSubgroup

/-- Unfolding lemma for `TauCeti.Huber.IsWeightedRestricted`. -/
theorem isWeightedRestricted_iff {T : Fin k → Set A} {f : MvPowerSeries (Fin k) A} :
    IsWeightedRestricted T f ↔ ∀ U : OpenAddSubgroup A,
      ∀ᶠ ν in cofinite, MvPowerSeries.coeff ν f ∈ weightMul T ν U.toAddSubgroup := (Iff.rfl)

/-- The zero series is `T`-restricted. -/
@[simp]
theorem isWeightedRestricted_zero (T : Fin k → Set A) :
    IsWeightedRestricted T (0 : MvPowerSeries (Fin k) A) := by
  intro U
  filter_upwards with ν
  simp

/-- The one series is `T`-restricted: every coefficient but the constant one vanishes. -/
@[simp]
theorem isWeightedRestricted_one (T : Fin k → Set A) :
    IsWeightedRestricted T (1 : MvPowerSeries (Fin k) A) := by
  classical
  intro U
  filter_upwards [(Set.finite_singleton (0 : Fin k →₀ ℕ)).compl_mem_cofinite] with ν hν
  rw [MvPowerSeries.coeff_one, if_neg (by simpa using hν)]
  exact (weightMul T ν U.toAddSubgroup).zero_mem

omit [TopologicalSpace A] in
/-- With every weight equal to `{1}`, the weight of any multi-index is `{1}`. -/
@[simp]
theorem weightPow_one (ν : Fin k →₀ ℕ) :
    weightPow (fun _ : Fin k ↦ ({1} : Set A)) ν = {1} := by
  simp [weightPow]

omit [TopologicalSpace A] in
/-- With every weight equal to `{1}`, the subgroup `Tν · U` is `U` itself. -/
@[simp]
theorem weightMul_one (ν : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul (fun _ : Fin k ↦ ({1} : Set A)) ν U = U := by
  rw [weightMul_eq, weightPow_one, Set.singleton_mul]
  simp

/-- **Wedhorn Example 5.54**: for the trivial weight `Tᵢ = {1}` the condition is the ordinary
restrictedness of `A⟨X⟩`, that the coefficients tend to zero along the cofinite filter. This is
the nontrivial witness that `TauCeti.Huber.IsWeightedRestricted` is not vacuous. -/
theorem isWeightedRestricted_one_weight_iff [NonarchimedeanRing A]
    {f : MvPowerSeries (Fin k) A} :
    IsWeightedRestricted (fun _ : Fin k ↦ ({1} : Set A)) f ↔
      Tendsto (fun ν ↦ MvPowerSeries.coeff ν f) cofinite (nhds 0) := by
  rw [isWeightedRestricted_iff]
  constructor
  · intro h
    rw [tendsto_nhds]
    intro V hV h0V
    obtain ⟨U, hUV⟩ := NonarchimedeanAddGroup.is_nonarchimedean V (hV.mem_nhds h0V)
    filter_upwards [h U] with ν hν
    exact hUV (by simpa using hν)
  · intro h U
    have := (tendsto_nhds.mp h) _ U.isOpen (SetLike.mem_coe.mpr U.zero_mem)
    filter_upwards [this] with ν hν
    simpa using hν

/-- A sum of `T`-restricted series is `T`-restricted. -/
theorem IsWeightedRestricted.add {T : Fin k → Set A} {f g : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) (hg : IsWeightedRestricted T g) :
    IsWeightedRestricted T (f + g) := by
  intro U
  filter_upwards [hf U, hg U] with ν hfν hgν
  simpa using (weightMul T ν U.toAddSubgroup).add_mem hfν hgν

/-- The negation of a `T`-restricted series is `T`-restricted. -/
theorem IsWeightedRestricted.neg {T : Fin k → Set A} {f : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) : IsWeightedRestricted T (-f) := by
  intro U
  filter_upwards [hf U] with ν hfν
  simpa using (weightMul T ν U.toAddSubgroup).neg_mem hfν

end

end TauCeti.Huber
