/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.MvPowerSeries.Basic
public import Mathlib.Topology.Algebra.Nonarchimedean.Basic

/-!
# Weighted restricted power series `A⟨X⟩_T`

For a topological ring `A` and a family `T` of subsets of `A` indexed by the variables, Wedhorn
defines the *weighted* restricted power series ring

```text
A⟨X⟩_T := { ∑ aν Xν ∈ A[[X]] ; aν ∈ Tν · U for every open subgroup U of A and almost all ν },
```

with the subgroups `U⟨X⟩ := { ∑ aν Xν ∈ A⟨X⟩_T ; aν ∈ Tν · U for all ν }` as a fundamental
system of neighbourhoods of zero. Here `Tν := T₁^ν₁ ⋯ Tₖ^νₖ`. Taking every `Tᵢ = {1}` recovers
the ordinary restricted series `A⟨X⟩`.

## Main definitions

* `TauCeti.Huber.weightPow`: the subset `Tν = T₁^ν₁ ⋯ Tₖ^νₖ` of `A`.
* `TauCeti.Huber.weightMul`: the additive subgroup `Tν · U`.
* `TauCeti.Huber.IsWeightedRestricted`: Wedhorn's condition (5.6.1) on a power series.

## Main results

* `TauCeti.Huber.isWeightedRestricted_zero`, `TauCeti.Huber.isWeightedRestricted_one`,
  `TauCeti.Huber.IsWeightedRestricted.add`, `TauCeti.Huber.IsWeightedRestricted.neg`: the
  condition is closed under the additive-group operations.

## Implementation notes

`Tν · U` is read as the additive subgroup *generated by* the products `t * u`, not as the
pointwise product set. Wedhorn's own statement forces this: he asserts that the `U⟨X⟩` are a
fundamental system of neighbourhoods of zero for a *ring* topology, so each must be an additive
subgroup, and the pointwise set `{t * u}` is not closed under addition.

The predicate carries no nonarchimedean hypothesis, matching (5.6.1), but it only *means*
coefficient convergence when the open additive subgroups are a neighbourhood basis of zero — the
setting Wedhorn works in throughout §5.6. Without that it can be vacuous: over `ℝ` with its usual
topology the only open additive subgroup is `ℝ` itself, so every power series is `T`-restricted
for the trivial weight. `TauCeti.Huber.isWeightedRestricted_one_weight_iff` therefore assumes
`NonarchimedeanRing`.

If some `Tᵢ` is empty and `νᵢ > 0` then `Tν` is empty and `Tν · U = ⊥`, so the condition forces
those coefficients to vanish; the closure lemmas below need no nonemptiness hypothesis.

This is *not* `TauCeti/RingTheory/Huber/ScaledTateTopology.lean`, which retopologises the
ordinary `A⟨X⟩` by transporting along `X ↦ f X`; there the weight multiplies the coefficient
rather than the neighbourhood, and the carrier does not vary with `T`.

Closure of `A⟨X⟩_T` under multiplication is not yet formalised. Wedhorn flags it as the one
non-obvious point of the construction ("note that it is not entirely clear that `A⟨X⟩_T` is
multiplicatively closed").

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Remark and Definition 5.48, equation (5.6.1), and
  Example 5.54 for the case `Tᵢ = {1}`.
-/

open Filter Pointwise Topology

namespace TauCeti.Huber

public section

variable {k : ℕ} {A : Type*} [CommRing A] [TopologicalSpace A]

/-- The weight `Tν = T₁^ν₁ ⋯ Tₖ^νₖ` attached to a multi-index, as a subset of `A`. -/
def weightPow (T : Fin k → Set A) (ν : Fin k →₀ ℕ) : Set A := ∏ i, T i ^ ν i

omit [TopologicalSpace A] in
/-- Unfolding lemma for `TauCeti.Huber.weightPow`. -/
theorem weightPow_eq (T : Fin k → Set A) (ν : Fin k →₀ ℕ) :
    weightPow T ν = ∏ i, T i ^ ν i := (rfl)

/-- The additive subgroup `Tν · U` generated by the products of the weight with `U`. See the
module docstring: the subgroup, not the pointwise product set, is what Wedhorn's statement
requires. -/
def weightMul (T : Fin k → Set A) (ν : Fin k →₀ ℕ) (U : AddSubgroup A) : AddSubgroup A :=
  AddSubgroup.closure (weightPow T ν * (U : Set A))

omit [TopologicalSpace A] in
/-- Unfolding lemma for `TauCeti.Huber.weightMul`. -/
theorem weightMul_eq (T : Fin k → Set A) (ν : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul T ν U = AddSubgroup.closure (weightPow T ν * (U : Set A)) := (rfl)

/-- Wedhorn's standing hypothesis on the weight family, fixed at the start of his §5.6: for every
variable `i`, every `m`, and every neighbourhood `U` of zero, the subgroup `Tᵢ^m · U` is again a
neighbourhood of zero.

Without it `A⟨X⟩_T` is not multiplicatively closed. Take `A = ℚ_p⟨Y, Z⟩`, `T = {Y}`, `f = Z X`
and `g = ∑ₙ Yⁿ pⁿ Xⁿ`: both are `T`-restricted, but the `Xᵏ` coefficient of `f * g` is
`Z Yᵏ⁻¹ pᵏ⁻¹`, which never lies in `Tᵏ · A = Yᵏ A`. Note that there `A` is complete, Tate and
Huber and `T` is finite, bounded and power-bounded — so none of those conditions substitute for
this one. What fails is exactly that `Y A` is not open. -/
def IsWeightFamily (T : Fin k → Set A) : Prop :=
  ∀ (i : Fin k) (m : ℕ) (U : Set A), U ∈ nhds (0 : A) →
    (AddSubgroup.closure (T i ^ m * U) : Set A) ∈ nhds (0 : A)

/-- Wedhorn: the standing hypothesis is automatic when every `Tᵢ` is `{1}`, the important special
case, since then `Tᵢ^m · U` is the subgroup generated by `U`. -/
theorem isWeightFamily_one [NonarchimedeanRing A] :
    IsWeightFamily (fun _ : Fin k ↦ ({1} : Set A)) := by
  intro _ m U hU
  obtain ⟨V, hVU⟩ := NonarchimedeanAddGroup.is_nonarchimedean U hU
  refine Filter.mem_of_superset (V.isOpen.mem_nhds V.zero_mem) ?_
  refine le_trans ?_ (AddSubgroup.closure_mono (Set.mul_subset_mul_left hVU))
  exact fun v hv ↦ AddSubgroup.subset_closure ⟨1, by simp, v, hv, by simp⟩

/-- A weight subgroup that is a neighbourhood of zero is open, and so packages as an
`OpenAddSubgroup`. Wedhorn's standing hypothesis is exactly what supplies the neighbourhood
premise, and the open form is what continuity of multiplication consumes. -/
def weightMul.toOpenAddSubgroup [IsTopologicalAddGroup A] (T : Fin k → Set A) (ν : Fin k →₀ ℕ)
    (U : AddSubgroup A) (h : (weightMul T ν U : Set A) ∈ nhds (0 : A)) : OpenAddSubgroup A where
  toAddSubgroup := weightMul T ν U
  isOpen' := (weightMul T ν U).isOpen_of_mem_nhds h

@[simp]
theorem weightMul.coe_toOpenAddSubgroup [IsTopologicalAddGroup A] (T : Fin k → Set A)
    (ν : Fin k →₀ ℕ) (U : AddSubgroup A) (h : (weightMul T ν U : Set A) ∈ nhds (0 : A)) :
    (weightMul.toOpenAddSubgroup T ν U h : Set A) = weightMul T ν U := (rfl)

omit [TopologicalSpace A] in
/-- At the zero multi-index the weight is trivial, so `T⁰ · U` is just `U`; in particular it is a
neighbourhood of zero whenever `U` is. This is the base case of Wedhorn's remark that `Tν · U` is
a neighbourhood of zero for every `ν`. -/
theorem weightMul_zero (T : Fin k → Set A) (U : AddSubgroup A) :
    weightMul T 0 U = U := by
  rw [weightMul_eq, weightPow, show (0 : Fin k →₀ ℕ) = 0 from rfl]
  simp

/-- Wedhorn (5.6.1): a power series is *`T`-restricted* if, for every open subgroup `U` of `A`,
all but finitely many of its coefficients lie in `Tν · U`. -/
def IsWeightedRestricted (T : Fin k → Set A) (f : MvPowerSeries (Fin k) A) : Prop :=
  ∀ U : OpenAddSubgroup A,
    ∀ᶠ ν in cofinite, MvPowerSeries.coeff ν f ∈ weightMul T ν U.toAddSubgroup

/-- Unfolding lemma for `TauCeti.Huber.IsWeightedRestricted`. -/
theorem isWeightedRestricted_iff {T : Fin k → Set A} {f : MvPowerSeries (Fin k) A} :
    IsWeightedRestricted T f ↔ ∀ U : OpenAddSubgroup A,
      ∀ᶠ ν in cofinite, MvPowerSeries.coeff ν f ∈ weightMul T ν U.toAddSubgroup := (Iff.rfl)

/-- The zero series is `T`-restricted. -/
@[simp]
theorem isWeightedRestricted_zero (T : Fin k → Set A) :
    IsWeightedRestricted T (0 : MvPowerSeries (Fin k) A) := by
  intro U
  filter_upwards with ν
  simp

/-- The one series is `T`-restricted: every coefficient but the constant one vanishes. -/
@[simp]
theorem isWeightedRestricted_one (T : Fin k → Set A) :
    IsWeightedRestricted T (1 : MvPowerSeries (Fin k) A) := by
  classical
  intro U
  filter_upwards [(Set.finite_singleton (0 : Fin k →₀ ℕ)).compl_mem_cofinite] with ν hν
  rw [MvPowerSeries.coeff_one, if_neg (by simpa using hν)]
  exact (weightMul T ν U.toAddSubgroup).zero_mem

omit [TopologicalSpace A] in
/-- Weights are multiplicative in the multi-index: `T^(α+β) = T^α · T^β`. This is the algebraic
identity that any proof of multiplicative closure has to run on. -/
theorem weightPow_add (T : Fin k → Set A) (α β : Fin k →₀ ℕ) :
    weightPow T (α + β) = weightPow T α * weightPow T β := by
  simp only [weightPow, Finsupp.add_apply, pow_add]
  exact Finset.prod_mul_distrib

omit [TopologicalSpace A] in
/-- A product of an element of `T^α · V` with an element of `T^β · W` lies in
`T^(α+β) · (V · W)`. Together with `TauCeti.Huber.weightPow_add` this is the algebraic half of
multiplicative closure; the analytic half — controlling the finitely many coefficients that fail
a given bound — is what Wedhorn flags as not entirely clear. -/
theorem weightMul_mul_mem {T : Fin k → Set A} {α β : Fin k →₀ ℕ} {V W : AddSubgroup A} {x y : A}
    (hx : x ∈ weightMul T α V) (hy : y ∈ weightMul T β W) :
    x * y ∈ weightMul T (α + β) (AddSubgroup.closure ((V : Set A) * (W : Set A))) := by
  induction hx using AddSubgroup.closure_induction with
  | mem u hu =>
      induction hy using AddSubgroup.closure_induction with
      | mem v hv =>
          obtain ⟨t, ht, a, ha, rfl⟩ := hu
          obtain ⟨t', ht', b, hb, rfl⟩ := hv
          refine AddSubgroup.subset_closure ⟨t * t', ?_, a * b, ?_, by ring⟩
          · rw [weightPow_add]
            exact Set.mul_mem_mul ht ht'
          · exact AddSubgroup.subset_closure (Set.mul_mem_mul ha hb)
      | zero => simp
      | add _ _ _ _ h₁ h₂ => simpa [mul_add] using (weightMul T (α + β) _).add_mem h₁ h₂
      | neg _ _ h => simpa [mul_neg] using (weightMul T (α + β) _).neg_mem h
  | zero => simp
  | add _ _ _ _ h₁ h₂ => simpa [add_mul] using (weightMul T (α + β) _).add_mem h₁ h₂
  | neg _ _ h => simpa [neg_mul] using (weightMul T (α + β) _).neg_mem h

omit [TopologicalSpace A] in
/-- Multiplying by a weight element shifts the multi-index: `T^β · (T^α · U) ⊆ T^(α+β) · U`. -/
theorem weightPow_mul_weightMul_mem {T : Fin k → Set A} {α β : Fin k →₀ ℕ} {U : AddSubgroup A}
    {t x : A} (ht : t ∈ weightPow T β) (hx : x ∈ weightMul T α U) :
    t * x ∈ weightMul T (α + β) U := by
  induction hx using AddSubgroup.closure_induction with
  | mem y hy =>
      obtain ⟨t', ht', u, hu, rfl⟩ := hy
      refine AddSubgroup.subset_closure ⟨t' * t, ?_, u, hu, by ring⟩
      rw [weightPow_add]
      exact Set.mul_mem_mul ht' ht
  | zero => simp
  | add _ _ _ _ h₁ h₂ => simpa [mul_add] using (weightMul T (α + β) U).add_mem h₁ h₂
  | neg _ _ h => simpa [mul_neg] using (weightMul T (α + β) U).neg_mem h

omit [TopologicalSpace A] in
/-- At a single-variable multi-index the weight is the corresponding power: `T^(single i m)` is
`Tᵢ ^ m`. This is what connects Wedhorn's per-variable standing hypothesis to the multi-index
statement he derives from it. -/
theorem weightPow_single (T : Fin k → Set A) (i : Fin k) (m : ℕ) :
    weightPow T (Finsupp.single i m) = T i ^ m := by
  rw [weightPow, Finset.prod_eq_single i]
  · simp
  · intro j _ hj
    simp [Ne.symm hj]
  · simp

omit [TopologicalSpace A] in
/-- Splitting a multi-index splits the weight subgroup: `T^(α+β) · U` is generated by `T^α`
against `T^β · U`. This is the step that lets the multi-index neighbourhood statement be proved
by induction from the per-variable one. -/
theorem weightMul_add_eq (T : Fin k → Set A) (α β : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul T (α + β) U
      = AddSubgroup.closure (weightPow T α * (weightMul T β U : Set A)) := by
  refine le_antisymm ?_ ?_
  · rw [weightMul_eq, AddSubgroup.closure_le]
    rintro _ ⟨t, ht, u, hu, rfl⟩
    rw [weightPow_add] at ht
    obtain ⟨a, ha, b, hb, rfl⟩ := ht
    exact AddSubgroup.subset_closure
      ⟨a, ha, b * u, AddSubgroup.subset_closure ⟨b, hb, u, hu, rfl⟩, by ring⟩
  · rw [AddSubgroup.closure_le]
    rintro _ ⟨t, ht, x, hx, rfl⟩
    exact add_comm α β ▸ weightPow_mul_weightMul_mem ht hx

/-- **Wedhorn's derived hypothesis**: from the per-variable assumption that each `Tᵢ^m · U` is a
neighbourhood of zero it follows that `Tν · U` is one for every multi-index `ν`. Wedhorn states
this in a sentence ("Then `Tν U` is a neighborhood of `0` for all `ν`"); the proof is induction
on `ν`, splitting off one variable at a time with
`TauCeti.Huber.weightMul_add_eq` and `TauCeti.Huber.weightPow_single`. -/
theorem IsWeightFamily.weightMul_mem_nhds {T : Fin k → Set A} (hT : IsWeightFamily T)
    (ν : Fin k →₀ ℕ) {U : AddSubgroup A} (hU : (U : Set A) ∈ nhds (0 : A)) :
    (weightMul T ν U : Set A) ∈ nhds (0 : A) := by
  induction ν using Finsupp.induction with
  | zero => rwa [weightMul_zero]
  | single_add i m ν' _ _ ih =>
      rw [weightMul_add_eq, weightPow_single]
      exact hT i m _ ih

/-- Multiplication by a fixed element is continuous, so any subgroup that is a neighbourhood of
zero absorbs it: there is an open subgroup `Z` with `a * Z ⊆ V`.

Applied with `V = Tα · U`, which
`TauCeti.Huber.IsWeightFamily.weightMul_mem_nhds` makes a neighbourhood of zero, this is what
produces the subgroup that `TauCeti.Huber.weightMul_absorb` consumes for a coefficient that fails
a given bound. -/
theorem exists_openAddSubgroup_mul_subset [NonarchimedeanRing A] (a : A)
    (V : AddSubgroup A) (hV : (V : Set A) ∈ nhds (0 : A)) :
    ∃ Z : OpenAddSubgroup A, ∀ z ∈ Z, a * z ∈ V := by
  have hmul : (fun x ↦ a * x) ⁻¹' (V : Set A) ∈ nhds (0 : A) :=
    (continuous_const.mul continuous_id).continuousAt.preimage_mem_nhds (by simpa using hV)
  obtain ⟨Z, hZ⟩ := NonarchimedeanAddGroup.is_nonarchimedean _ hmul
  exact ⟨Z, fun z hz ↦ hZ hz⟩

/-- The finite-family form of `TauCeti.Huber.exists_openAddSubgroup_mul_subset`: one open
subgroup `Z` absorbs each of finitely many fixed elements into its own target.

In the proof that `A⟨X⟩_T` is multiplicatively closed this is applied to the finitely many
coefficients that fail a given bound, producing the single subgroup against which the whole
antidiagonal is estimated. -/
theorem exists_openAddSubgroup_forall_mul_subset [NonarchimedeanRing A] {ι : Type*}
    (s : Finset ι) (a : ι → A) (V : ι → AddSubgroup A)
    (hV : ∀ i ∈ s, (V i : Set A) ∈ nhds (0 : A)) :
    ∃ Z : OpenAddSubgroup A, ∀ i ∈ s, ∀ z ∈ Z, a i * z ∈ V i := by
  classical
  induction s using Finset.induction with
  | empty => exact ⟨⊤, by simp⟩
  | insert i s' hi ih =>
      obtain ⟨Z', hZ'⟩ := ih fun j hj ↦ hV j (Finset.mem_insert_of_mem hj)
      obtain ⟨Z, hZ⟩ :=
        exists_openAddSubgroup_mul_subset (a i) (V i) (hV i (Finset.mem_insert_self i s'))
      refine ⟨Z ⊓ Z', fun j hj z hz ↦ ?_⟩
      rcases Finset.mem_insert.mp hj with rfl | hj'
      · exact hZ z hz.1
      · exact hZ' j hj' z hz.2

omit [TopologicalSpace A] in
/-- **The absorption step.** If multiplication by `a` carries the subgroup `Z` into `T^α · U`,
then it carries all of `T^β · Z` into `T^(α+β) · U`.

This is what handles the finitely many coefficients that fail a given bound in the proof that
`A⟨X⟩_T` is multiplicatively closed: Wedhorn's standing hypothesis
(`TauCeti.Huber.IsWeightFamily`) makes `T^α · U` a neighbourhood of zero, so continuity of
multiplication by the fixed bad coefficient `a` supplies such a `Z`. -/
theorem weightMul_absorb {T : Fin k → Set A} {α β : Fin k →₀ ℕ} {U Z : AddSubgroup A} {a b : A}
    (ha : ∀ z ∈ Z, a * z ∈ weightMul T α U) (hb : b ∈ weightMul T β Z) :
    a * b ∈ weightMul T (α + β) U := by
  induction hb using AddSubgroup.closure_induction with
  | mem y hy =>
      obtain ⟨t, ht, z, hz, rfl⟩ := hy
      rw [show a * (t * z) = t * (a * z) by ring]
      exact weightPow_mul_weightMul_mem ht (ha z hz)
  | zero => simp
  | add _ _ _ _ h₁ h₂ => simpa [mul_add] using (weightMul T (α + β) U).add_mem h₁ h₂
  | neg _ _ h => simpa [mul_neg] using (weightMul T (α + β) U).neg_mem h

omit [TopologicalSpace A] in
/-- With every weight equal to `{1}`, the weight of any multi-index is `{1}`. -/
@[simp]
theorem weightPow_one (ν : Fin k →₀ ℕ) :
    weightPow (fun _ : Fin k ↦ ({1} : Set A)) ν = {1} := by
  simp [weightPow]

omit [TopologicalSpace A] in
/-- With every weight equal to `{1}`, the subgroup `Tν · U` is `U` itself. -/
@[simp]
theorem weightMul_one (ν : Fin k →₀ ℕ) (U : AddSubgroup A) :
    weightMul (fun _ : Fin k ↦ ({1} : Set A)) ν U = U := by
  rw [weightMul_eq, weightPow_one, Set.singleton_mul]
  simp

/-- **Wedhorn Example 5.54**: for the trivial weight `Tᵢ = {1}` the condition is the ordinary
restrictedness of `A⟨X⟩`, that the coefficients tend to zero along the cofinite filter. This is
the nontrivial witness that `TauCeti.Huber.IsWeightedRestricted` is not vacuous. -/
theorem isWeightedRestricted_one_weight_iff [NonarchimedeanRing A]
    {f : MvPowerSeries (Fin k) A} :
    IsWeightedRestricted (fun _ : Fin k ↦ ({1} : Set A)) f ↔
      Tendsto (fun ν ↦ MvPowerSeries.coeff ν f) cofinite (nhds 0) := by
  rw [isWeightedRestricted_iff]
  constructor
  · intro h
    rw [tendsto_nhds]
    intro V hV h0V
    obtain ⟨U, hUV⟩ := NonarchimedeanAddGroup.is_nonarchimedean V (hV.mem_nhds h0V)
    filter_upwards [h U] with ν hν
    exact hUV (by simpa using hν)
  · intro h U
    have := (tendsto_nhds.mp h) _ U.isOpen (SetLike.mem_coe.mpr U.zero_mem)
    filter_upwards [this] with ν hν
    simpa using hν

/-- A sum of `T`-restricted series is `T`-restricted. -/
theorem IsWeightedRestricted.add {T : Fin k → Set A} {f g : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) (hg : IsWeightedRestricted T g) :
    IsWeightedRestricted T (f + g) := by
  intro U
  filter_upwards [hf U, hg U] with ν hfν hgν
  simpa using (weightMul T ν U.toAddSubgroup).add_mem hfν hgν

/-- The negation of a `T`-restricted series is `T`-restricted. -/
theorem IsWeightedRestricted.neg {T : Fin k → Set A} {f : MvPowerSeries (Fin k) A}
    (hf : IsWeightedRestricted T f) : IsWeightedRestricted T (-f) := by
  intro U
  filter_upwards [hf U] with ν hfν
  simpa using (weightMul T ν U.toAddSubgroup).neg_mem hfν

end

end TauCeti.Huber
