/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.ClassGroup.Basic
public import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
public import Mathlib.RingTheory.DedekindDomain.Factorization

/-!
# Ideal classes of the height one primes

Facts about Mathlib's `ClassGroup R` that its own file does not carry, culminating in the
localisation statements about which classes a set `T` of height one primes generates.

## Main results

* `ClassGroup.mk_toPrincipalIdeal`: a principal fractional ideal has trivial class. This is the
  `simp` form of `ClassGroup.mk_eq_one_iff` for the one witness that arises in practice, and it
  holds over any domain.
* `IsDedekindDomain.HeightOneSpectrum.classGroupMk`: the class `[v]` of a height one prime of a
  Dedekind domain, with `classGroupMk_eq_mk` identifying it with the class of `v.asIdeal` seen as
  an invertible fractional ideal of any fraction field.
* `FractionalIdeal.mk_mem_closure_of_count_eq_zero`: if the `v`-adic multiplicities of a unit
  fractional ideal vanish outside `T`, its class lies in the subgroup generated by `{[v] : v ∈ T}`.
* `FractionalIdeal.mk0_mem_closure_of_count_eq`: the same conclusion for a nonzero integral ideal
  whose multiplicities merely agree outside `T` with those of a principal ideal.

Everything is stated at the weakest hypotheses its proof needs — `ClassGroup.mk_toPrincipalIdeal`
over `[IsDomain R]`, since nothing in it is Dedekind-specific. Nothing here mentions Weil
divisors: the factorization `I = ∏_v v ^ count v I` comes from Mathlib's
`FractionalIdeal.finprod_heightOneSpectrum_factorization'`, lifted from fractional ideals to units
along `Units.coeHom`, so that `RingTheory` and `NumberTheory` consumers — in particular the
`S`-integer material — can reach these results without importing `TauCeti.AlgebraicGeometry`.

Split out of material adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/FractionalIdeal.lean`
at the roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll). Following this repository's
convention for adapted material, the upstream authorship is credited here rather than in the
copyright header.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

/-- A principal fractional ideal has trivial ideal class. -/
@[simp]
lemma ClassGroup.mk_toPrincipalIdeal {R : Type*} [CommRing R] [IsDomain R] {K : Type*} [Field K]
    [Algebra R K] [IsFractionRing R K] (x : Kˣ) :
    ClassGroup.mk K (toPrincipalIdeal R K x) = 1 :=
  ClassGroup.mk_eq_one_iff.mpr
    ⟨⟨(x : K), by rw [coe_toPrincipalIdeal, FractionalIdeal.coe_spanSingleton]⟩⟩

variable {R : Type*} [CommRing R] [IsDedekindDomain R]

/-- The class of a height one prime `v` in the ideal class group of `R`. -/
noncomputable def IsDedekindDomain.HeightOneSpectrum.classGroupMk (v : HeightOneSpectrum R) :
    ClassGroup R :=
  ClassGroup.mk0 ⟨v.asIdeal, mem_nonZeroDivisors_of_ne_zero v.ne_bot⟩

/-- The defining formula for `classGroupMk`, so that consumers working with `ClassGroup.mk0` never
need to unfold the definition (whose body a `public section` leaves unexposed). -/
@[simp]
lemma IsDedekindDomain.HeightOneSpectrum.classGroupMk_eq_mk0 (v : HeightOneSpectrum R) :
    v.classGroupMk = ClassGroup.mk0 ⟨v.asIdeal, mem_nonZeroDivisors_of_ne_zero v.ne_bot⟩ := by
  -- Not `rfl`: a `public section` leaves the body of `classGroupMk` unexposed, so the equation
  -- has to come from the definition's own equation lemma.
  simp only [IsDedekindDomain.HeightOneSpectrum.classGroupMk]

/-- The class of `v` is the class of `v.asIdeal` viewed as an invertible fractional ideal of a
fraction field `K`. -/
lemma IsDedekindDomain.HeightOneSpectrum.classGroupMk_eq_mk (K : Type*) [Field K] [Algebra R K]
    [IsFractionRing R K] (v : HeightOneSpectrum R) :
    v.classGroupMk = ClassGroup.mk K (Units.mk0 (v.asIdeal : FractionalIdeal R⁰ K)
      (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)) := by
  rw [classGroupMk_eq_mk0, ← ClassGroup.mk_mk0 K]
  exact congrArg _ (Units.ext (FractionalIdeal.coe_mk0 K _))

/-- `v.asIdeal` as an invertible fractional ideal of `K`. Local to this file: it is the shape the
factorization of a unit fractional ideal takes, and it appears in no statement. -/
private noncomputable def unitOfPrime (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
    (v : HeightOneSpectrum R) : (FractionalIdeal R⁰ K)ˣ :=
  Units.mk0 (v.asIdeal : FractionalIdeal R⁰ K) (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)

variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- If the `v`-adic multiplicities of a unit fractional ideal vanish outside a set `T` of height
one primes, its ideal class lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.FractionalIdeal.mk_mem_closure_of_count_eq_zero {T : Set (HeightOneSpectrum R)}
    {I : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) = 0) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  classical
  -- Only finitely many primes divide `I`, so the factorization is a finite product.
  have hfin : (Function.mulSupport fun v : HeightOneSpectrum R =>
      unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K)).Finite := by
    refine (Filter.eventually_cofinite.mp
      (FractionalIdeal.finite_factors (I : FractionalIdeal R⁰ K))).subset fun v hv hc0 => ?_
    exact hv (by simp only [hc0, zpow_zero])
  -- `I = ∏_v v ^ count v I`, lifted from Mathlib's fractional-ideal statement to units.  The
  -- `map_finprod` equation is stated rather than rewritten into, because `← Units.coeHom_apply`
  -- would also rewrite the coercion inside `count K v ↑I`.
  have hI : I = ∏ᶠ v : HeightOneSpectrum R,
      unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) := by
    have hmap : ((∏ᶠ v : HeightOneSpectrum R,
          unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K)) :
          (FractionalIdeal R⁰ K)ˣ) =
        ∏ᶠ v : HeightOneSpectrum R,
          ((unitOfPrime K v ^ FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) :
            (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) :=
      MonoidHom.map_finprod (Units.coeHom (FractionalIdeal R⁰ K)) hfin
    refine Units.ext ?_
    rw [hmap]
    simp only [unitOfPrime, Units.val_zpow_eq_zpow_val, Units.val_mk0]
    exact (FractionalIdeal.finprod_heightOneSpectrum_factorization' (K := K)
      (I := (I : FractionalIdeal R⁰ K)) (Units.ne_zero I)).symm
  rw [hI, finprod_eq_prod_of_mulSupport_toFinset_subset _ hfin (Finset.Subset.refl _), map_prod]
  refine Subgroup.prod_mem _ fun v hv ↦ ?_
  have hvT : v ∈ T := by
    by_contra hvn
    refine (hfin.mem_toFinset.mp hv) ?_
    simp only [h v hvn, zpow_zero]
  rw [map_zpow]
  simp only [unitOfPrime, ← v.classGroupMk_eq_mk K]
  exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_image_of_mem _ hvT)) _

/-- If the `v`-adic multiplicities of a nonzero integral ideal `J` agree outside a set `T` of
height one primes with those of a principal fractional ideal `(x)`, then the class of `J` lies in
the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.FractionalIdeal.mk0_mem_closure_of_count_eq {T : Set (HeightOneSpectrum R)}
    {J : (Ideal R)⁰} {x : Kˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v ((J : Ideal R) : FractionalIdeal R⁰ K) =
      FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (x : K))) :
    ClassGroup.mk0 J ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hmk : ClassGroup.mk0 J =
      ClassGroup.mk K (FractionalIdeal.mk0 K J * (toPrincipalIdeal R K x)⁻¹) := by
    rw [map_mul, map_inv, ClassGroup.mk_toPrincipalIdeal, inv_one, mul_one, ClassGroup.mk_mk0]
  rw [hmk]
  refine FractionalIdeal.mk_mem_closure_of_count_eq_zero fun v hv ↦ ?_
  rw [Units.val_mul, FractionalIdeal.count_mul K v (Units.ne_zero _) (Units.ne_zero _),
    Units.val_inv_eq_inv_val, FractionalIdeal.count_inv, FractionalIdeal.coe_mk0,
    coe_toPrincipalIdeal, h v hv]
  exact add_neg_cancel _

end
