/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.OpenMapping
public import TauCeti.RingTheory.Huber.WeightedRestrictedSeries.Basic

/-!
# The weight condition from openness, via the open mapping theorem

`TauCeti.Huber.IsWeightFamily` asks that `Tᵢ^m · U` be a neighbourhood of `0` for every
neighbourhood `U` — that multiplication by a weight is an open *map*. The roadmap instead phrases
the condition as each `Tᵢ · A` being *open*, and `IsWeightFamily.of_exists_isOpenMap_mul`'s
docstring records that the two coincide only under an open mapping theorem.

Over a complete Tate ring that theorem is available, as `TauCeti.Huber.IsTateRing.isOpenMap`.

**This file covers the principal case only, and that is strictly weaker than the roadmap's
hypothesis.** What is proved below assumes some *single* `t ∈ Tᵢ` has `t · A` open; the roadmap
asks that the ideal generated by `Tᵢ` *collectively* be open, and an open finitely generated ideal
need not contain a generator whose principal ideal is open — `span {ϖ + x, ϖ - x}` contains `2ϖ`
and so is open whenever `2` is a unit, while neither generator need be. The collective statement
needs the open mapping theorem applied to a surjection `Aⁿ ↠ span Tᵢ`, whose source hypothesis
`NonarchimedeanAddGroup (Fin n → A)` is not yet on `main`; so the gap is narrowed here, not
closed.

It is a separate file rather than an addition to `WeightedRestrictedSeries.Basic` on import
weight: importing `Huber.OpenMapping` there would take that file's closure from 17 modules to 40,
pulling Baire category theory and the whole Henkel stack into the file that merely *defines*
`IsWeightFamily`.

## Main results

* `TauCeti.Huber.isOpenMap_mul_of_isOpen_span`: over a complete Tate ring, an open principal
  ideal makes multiplication by its generator an open map.
* `TauCeti.Huber.IsWeightFamily.of_isOpen_span`: a family each of whose weights contains an
  element with open principal ideal is a weight family. **Not** the roadmap's collective-span
  hypothesis — see above.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Theorem 6.16 for the open
  mapping theorem this consumes.
-/

public section

namespace TauCeti.Huber

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [IsTopologicalRing A]
  [IsTateRing A] [CompleteSpace A] [T0Space A]

/-- **The principal case of the weight condition.** If each `Tᵢ` contains a `t` whose principal
ideal is open, the family is a weight family.

This is *stronger* than asking that `span (Tᵢ)` be open, which is what the roadmap states; see the
module docstring for why the two differ and what the collective version needs.

It is `TauCeti.Huber.IsWeightFamily.of_exists_isOpenMap_mul` fed by
`TauCeti.Huber.isOpenMap_mul_of_isOpen_span`; the completeness and Tate hypotheses are what that
open mapping theorem needs, and are not used elsewhere. -/
theorem IsWeightFamily.of_isOpen_span {k : ℕ} {T : Fin k → Set A}
    (h : ∀ i, ∃ t ∈ T i, IsOpen ((Ideal.span {t} : Ideal A) : Set A)) : IsWeightFamily T :=
  IsWeightFamily.of_exists_isOpenMap_mul fun i ↦
    (h i).imp fun _ ht ↦ ⟨ht.1, isOpenMap_mul_of_isOpen_span ht.2⟩

end TauCeti.Huber

end
