/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.GroupTheory.OrderOfElement

/-!
# When a cyclic subgroup of a product meets a factor trivially

For `σ : G` and `τ : H`, the cyclic subgroup generated by `(σ, τ)` meets the first factor
`G × 1` trivially as soon as `orderOf σ ∣ orderOf τ`.

The divisibility is what does the work, and it is used only once: an element of
`⟨(σ, τ)⟩ ∩ (G × 1)` is `(σ, τ) ^ k` with `τ ^ k = 1`, so `orderOf τ ∣ k`, hence `orderOf σ ∣ k`
and `σ ^ k = 1` as well. Nothing is assumed finite. `orderOf x = 0` when `x` has infinite
order, so if `σ` has infinite order the hypothesis forces `orderOf τ = 0` as well, and then
`τ ^ k = 1` gives `k = 0`; the argument goes through unchanged.

## Main results

* `Subgroup.zpowers_inf_prod_bot_of_orderOf_dvd`: `⟨(σ, τ)⟩ ⊓ (⊤ × ⊥) = ⊥`.
-/

public section

namespace Subgroup

/-- **A cyclic subgroup of a product meets the first factor trivially**, whenever the order of
the first coordinate divides that of the second: `⟨(σ, τ)⟩ ⊓ (G × 1) = 1`.

This is the only place the divisibility `orderOf σ ∣ orderOf τ` is needed. Note the asymmetry:
the meet with the *other* factor `1 × H` is trivial under the reverse divisibility, so the two
statements are not interchangeable. -/
theorem zpowers_inf_prod_bot_of_orderOf_dvd {G H : Type*} [Group G] [Group H]
    (σ : G) (τ : H) (hστ : orderOf σ ∣ orderOf τ) :
    zpowers ((σ, τ) : G × H) ⊓ (⊤ : Subgroup G).prod (⊥ : Subgroup H) = ⊥ := by
  rw [eq_bot_iff]
  rintro ⟨g, h⟩ hmem
  rw [mem_inf, mem_prod, mem_bot] at hmem
  obtain ⟨⟨k, hk⟩, -, (hh : h = 1)⟩ := hmem
  have hτ : τ ^ k = 1 := by simpa [hh] using congrArg Prod.snd hk
  have hσ : σ ^ k = 1 :=
    orderOf_dvd_iff_zpow_eq_one.mp (hστ.natCast.trans (orderOf_dvd_iff_zpow_eq_one.mpr hτ))
  rw [mem_bot, Prod.mk_eq_one]
  exact ⟨by simpa [hσ] using (congrArg Prod.fst hk).symm, hh⟩

end Subgroup
