/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Basic
public import TauCeti.AlgebraicGeometry.EllipticCurve.Universal

/-!
# The universal `ψ` family in the universal field

`ψᵤ n` is the `n`-division polynomial of the universal curve, pushed into `Universal.Field` along
`polyToField`. Writing it as a `normEDS` is what connects the universal curve to the elliptic
divisibility sequence machinery: every statement proved about `normEDS` becomes a statement about
the universal division polynomials, and hence — by specialising along `map_specialize` — about
every Weierstrass curve at once.

## Main results

* `WeierstrassCurve.Universal.ψᵤ`: the universal `ψ` family, valued in `Universal.Field`.
* `WeierstrassCurve.Universal.ψᵤ_eq_normEDS`: it is the normalised EDS generated by the images of
  `ψ₂`, `Ψ₃` and `preΨ₄`.

## Implementation notes

`ψᵤ_eq_normEDS` is `map_normEDS` read backwards. Mathlib defines `ψ` *as* a `normEDS`
(`DivisionPolynomial/Basic.lean:401`), so once the ring homomorphism is pushed inside, the two
sides are definitionally equal and `rfl` closes it. That the `rfl` succeeds across a module
boundary is not automatic — it works because Mathlib's `DivisionPolynomial/Basic.lean` opens
`@[expose] public section`, so `ψ`'s body is visible here.

## What is deliberately not here

The source continues with `isEllSequence_ψᵤ` and `net_ψᵤ`. Neither is available:

* `isEllSequence_ψᵤ` needs `normEDS` to be known an elliptic sequence. The pinned Mathlib's
  `IsEllipticSequence` namespace contains exactly `id` and `smul` — there is no `normEDS`
  instance, and `EllipticDivisibilitySequence.lean:70` still carries this as a TODO.
* `net_ψᵤ` needs `net_normEDS`, which does not exist in this repository or upstream.

Both belong with that upstream work rather than here.

## Provenance

Adapted from `LutzNagell/ZSMul.lean` in AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0) at
`dev/modular-curves @ 9fec8eba7652` — the revision `TauCetiRoadmap/EllipticCurves/README.md` pins
for the NagellLutz project. Declarations `ψᵤ` and `ψᵤ_eq_normEDS`. That file's header reads
`Authors: David Kurniadi Angdinata, Junyan Xu`; following this repository's convention for adapted
material the upstream authorship is credited here rather than in the copyright header.

The statements and the proof are the source's unchanged.
-/

public section

noncomputable section

open Polynomial

namespace WeierstrassCurve.Universal

/-- The `ψ` family of division polynomials of the universal curve, as elements of the universal
field. -/
abbrev ψᵤ (n : ℤ) : Universal.Field := polyToField (curve.ψ n)

/-- The universal `ψ` family is the normalised elliptic divisibility sequence generated by the
images of `ψ₂`, `Ψ₃` and `preΨ₄`. -/
lemma ψᵤ_eq_normEDS :
    ψᵤ = normEDS
      (polyToField curve.ψ₂) (polyToField <| C curve.Ψ₃) (polyToField <| C curve.preΨ₄) := by
  ext; rw [← map_normEDS]; rfl

end WeierstrassCurve.Universal
