/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

-- `IsCyclotomicExtension`, `IsPrimitiveRoot.intermediateField_adjoin_isCyclotomicExtension`
-- and `IsCyclotomicExtension.equiv` are the cyclotomic input.
public import Mathlib.NumberTheory.Cyclotomic.Basic
-- The Galois correspondence: `IntermediateField.fixedField`, `fixingSubgroup_sup`,
-- `IsGalois.fixedField_fixingSubgroup`.
public import Mathlib.FieldTheory.Galois.Basic

/-!
# A cyclotomic extension over the fixed field of a cyclic subgroup

Let `M / K` be a finite Galois extension containing a primitive `m`-th root of unity `ζ`, and let
`g` be an automorphism of `M` over `K`.  Write `K(μ_m)` for the subfield generated by the `m`-th
roots of unity, so that `Gal(M/K(μ_m))` is its fixing subgroup.  If the cyclic group `⟨g⟩` meets
`Gal(M/K(μ_m))` trivially, then `M` is a cyclotomic extension of the fixed field of `⟨g⟩`.

The mechanism is the Galois correspondence read on a supremum: a trivial meet of the two subgroups
says their fixed fields *generate* `M`, and one of the two generators is `K(μ_m)`, so `M` is
obtained from the other by adjoining `ζ`.

## Main results

* `IsCyclotomicExtension.of_zpowers_inf_fixingSubgroup_eq_bot`: `M` is `{m}`-cyclotomic over
  `IntermediateField.fixedField (Subgroup.zpowers g)` when `⟨g⟩ ⊓ Gal(M/K(μ_m)) = ⊥`.
-/

public section

open IntermediateField

namespace IsCyclotomicExtension

/-- If the cyclic subgroup generated by `g` meets `Gal(M/K(μ_m))` trivially, then `M` is a
`{m}`-cyclotomic extension of the fixed field of `⟨g⟩`.

Trivial meet gives `fixedField ⟨g⟩ ⊔ K(μ_m) = ⊤` by the Galois correspondence, and `K(μ_m)` is
`K(ζ)`, so adjoining `ζ` to the fixed field already gives all of `M`. -/
theorem of_zpowers_inf_fixingSubgroup_eq_bot {K M : Type*} [Field K] [Field M] [Algebra K M]
    [FiniteDimensional K M] [IsGalois K M] {m : ℕ} [NeZero m] {ζ : M}
    (hζ : IsPrimitiveRoot ζ m) (g : M ≃ₐ[K] M)
    (hmeet : Subgroup.zpowers g ⊓ (adjoin K {b : M | b ^ m = 1}).fixingSubgroup = ⊥) :
    IsCyclotomicExtension {m} ↥(fixedField (Subgroup.zpowers g)) M := by
  set F : IntermediateField K M := fixedField (Subgroup.zpowers g) with hF
  set Kμ : IntermediateField K M := adjoin K {b : M | b ^ m = 1} with hKμ
  have hadjζ : adjoin K {ζ} = Kμ :=
    le_antisymm
      (adjoin_le_iff.mpr (Set.singleton_subset_iff.mpr (subset_adjoin K _ hζ.pow_eq_one)))
      (adjoin_le_iff.mpr fun x hx ↦ by
        obtain ⟨i, -, rfl⟩ := hζ.eq_pow_of_pow_eq_one hx
        exact pow_mem (subset_adjoin K _ (Set.mem_singleton ζ)) i)
  have hsup : (F ⊔ Kμ).fixingSubgroup = ⊥ := by
    rw [fixingSubgroup_sup, hF, fixingSubgroup_fixedField, hmeet]
  have htop : F ⊔ Kμ = ⊤ := by
    have := congrArg fixedField hsup
    rwa [IsGalois.fixedField_fixingSubgroup, fixedField_bot] at this
  have htopF : adjoin (↥F) {ζ} = ⊤ := by
    apply restrictScalars_injective K
    rw [restrictScalars_adjoin_eq_sup, hadjζ, htop]
    rfl
  have : Algebra.IsIntegral ↥F M := Algebra.IsIntegral.of_finite ↥F M
  have hcyc : IsCyclotomicExtension {m} ↥F (adjoin (↥F) {ζ}) :=
    IsPrimitiveRoot.intermediateField_adjoin_isCyclotomicExtension (K := ↥F) hζ
  rw [htopF] at hcyc
  exact IsCyclotomicExtension.equiv (S := {m}) (A := ↥F) (f := IntermediateField.topEquiv)

end IsCyclotomicExtension
