/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.DedekindDomain.SInteger

/-!
# The ring of `S`-integers of a Dedekind domain is a Dedekind domain

Let `R` be a Dedekind domain with fraction field `K` and `S` a set of height-one primes of `R`.
`Mathlib/RingTheory/DedekindDomain/SInteger.lean` defines the subalgebra of `S`-integers
`{x : K | ∀ v ∉ S, v x ≤ 1}` as `Set.integer S K`, but proves nothing about its ring
structure.
This file shows it is again a Dedekind domain: integrally closed (`isIntegrallyClosed`),
noetherian (`isNoetherianRing`), and of dimension at most one (`dimensionLEOne`), hence
`isDedekindDomain`.

The key step is `integer_map_comap_eq`: every ideal of the `S`-integers is generated by its
contraction to `R`, proved through the denominator ideal `Algebra.denomIdeal K x = (R : x)` of
an element of `K`.

Note that the `S`-integers are **not** in general a localization of `R`, so the ring has to be
handled as a general overring of `R` rather than a ring of fractions. Localizing at
`{r : R | r ≠ 0 ∧ ∀ v ∉ S, v r = 1}` can give a strictly smaller ring: if `Cl(R) ≅ ℤ` is
generated by the class of a single prime `v` and `S = {v}`, no power `v ^ k` with `k ≠ 0` is
principal, so that monoid is just the units of `R`, yet the `S`-integers strictly contain `R`.

This is a prerequisite for the Selmer-group finiteness that
`TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak Mordell–Weil: the `S`-class
group and `S`-units in that statement are those of this ring.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/SIntegers.lean` at the
roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll), which the roadmap names as the
provenance for its Layer 6 Mordell–Weil lane. Following this repository's convention for adapted
material, the upstream authorship is credited here rather than in the copyright header. Ported
with the source's blanket `import Mathlib` narrowed to the modules actually used, and the
class-group half of the source file deferred to the PR that consumes it.
-/

public section

open IsDedekindDomain FractionalIdeal

open scoped nonZeroDivisors

section DenomIdeal

variable {R : Type*} [CommRing R] (K : Type*) [CommRing K] [Algebra R K]

/-- The denominator ideal of `x : K`: the colon ideal `(R : x) = {r : R | r • x ∈ R}`.

`mem_denomIdeal_iff` below is deliberately not a `simp` lemma: `denomIdeal` is an `abbrev`, so
`simp` rewrites through it with `Submodule.mem_colon_singleton` and `Submodule.mem_one` before
the lemma could fire, and its left-hand side is therefore not in simp-normal form. -/
abbrev Algebra.denomIdeal (x : K) : Ideal R := (1 : Submodule R K).colon {x}

lemma Algebra.mem_denomIdeal_iff {x : K} {r : R} :
    r ∈ Algebra.denomIdeal K x ↔ ∃ s : R, algebraMap R K r * x = algebraMap R K s := by
  rw [Submodule.mem_colon_singleton, Algebra.smul_def, Submodule.mem_one]
  exact exists_congr fun s ↦ eq_comm

/-- The denominator ideal of an element of a localization at the non-zero-divisors is nonzero:
a denominator witnessing the element as a fraction lies in it. -/
lemma Algebra.denomIdeal_ne_bot [Nontrivial R] [IsLocalization R⁰ K] (x : K) :
    Algebra.denomIdeal K x ≠ (⊥ : Ideal R) := by
  obtain ⟨⟨a, b, hb⟩, hab⟩ := IsLocalization.surj R⁰ x
  refine fun h0 ↦ nonZeroDivisors.ne_zero hb ?_
  have : b ∈ Algebra.denomIdeal K x := by
    rw [Algebra.mem_denomIdeal_iff]; exact ⟨a, by rw [mul_comm]; exact hab⟩
  simpa [h0] using this

end DenomIdeal

namespace IsDedekindDomain

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

lemma integer_toSubring_le_valuationSubring {v : HeightOneSpectrum R} (hv : v ∉ S) :
    (S.integer K).toSubring ≤ (v.valuation K).valuationSubring.toSubring :=
  fun _ hx ↦ hx v hv

/-- The fraction field of the ring of `S`-integers is `K`. This is already an instance, as
`Set.integer S K` is a subalgebra of `K` over `R`. -/
example : IsFractionRing (S.integer K) K := inferInstance

/-- The ring of `S`-integers is integrally closed: it is an intersection of valuation subrings
of `K`, each of which is integrally closed in `K`. -/
instance integer_isIntegrallyClosed : IsIntegrallyClosed (S.integer K) := by
  -- `𝒪_S` is the intersection of the valuation subalgebras at the `v ∉ S`, each of which is
  -- integrally closed, so `IsIntegrallyClosed.iInf` applies.
  have he : S.integer K = ⨅ v : {v : HeightOneSpectrum R // v ∉ S},
      ({ (v.1.valuation K).valuationSubring.toSubring with
          algebraMap_mem' := fun r ↦ v.1.valuation_le_one r } : Subalgebra R K) := by
    ext x
    simp only [Algebra.mem_iInf, Subtype.forall]
    rfl
  rw [he]
  exact IsIntegrallyClosed.iInf _ fun v ↦
    inferInstanceAs (IsIntegrallyClosed (v.1.valuation K).valuationSubring)

/-!
### Primes in `S` become the unit ideal

For `v ∈ S` the inverse `v⁻¹` of `v` as a fractional ideal consists of `S`-integers, because an
element `y` with `y * v ⊆ R` can have a pole only at `v`. As `v * v⁻¹ = 1`, the extension of
`v`
to `𝒪_S` is therefore the unit ideal. This is the one place where the Dedekind property of `R`
enters, and it is what makes `𝒪_S` bigger than `R`.
-/

/-- A height one prime is not contained in any other one. -/
lemma _root_.IsDedekindDomain.HeightOneSpectrum.exists_mem_asIdeal_notMem_asIdeal
    {v w : HeightOneSpectrum R} (h : w ≠ v) :
    ∃ a ∈ v.asIdeal, a ∉ w.asIdeal := by
  by_contra! hc
  exact h (HeightOneSpectrum.ext (v.isMaximal.eq_of_le w.isPrime.ne_top hc).symm)

/-- For `v ∈ S`, the fractional ideal `v⁻¹` consists of `S`-integers. -/
lemma valuation_le_one_of_mem_inv {v w : HeightOneSpectrum R} (hw : w ≠ v) {y : K}
    (hy : y ∈ (v.asIdeal : FractionalIdeal R⁰ K)⁻¹) : w.valuation K y ≤ 1 := by
  obtain ⟨a, ha, haw⟩ := HeightOneSpectrum.exists_mem_asIdeal_notMem_asIdeal hw
  have h1 : y * algebraMap R K a ∈ (1 : FractionalIdeal R⁰ K) :=
    (FractionalIdeal.mem_inv_iff (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)).mp hy _
      (FractionalIdeal.mem_coeIdeal_of_mem R⁰ ha)
  obtain ⟨r, hr⟩ := (FractionalIdeal.mem_one_iff _).mp h1
  have h2 : w.valuation K (y * algebraMap R K a) ≤ 1 := hr ▸ w.valuation_le_one r
  rwa [map_mul, w.valuation_eq_one_iff_notMem.mpr haw, mul_one] at h2

/-- For `v ∈ S`, the extension of `v` to the ring of `S`-integers is the unit ideal. -/
@[simp] lemma integer_map_asIdeal_eq_top {v : HeightOneSpectrum R} (hv : v ∈ S) :
    Ideal.map (algebraMap R (S.integer K)) v.asIdeal = ⊤ := by
  set A := S.integer K with hA
  set M := Ideal.map (algebraMap R A) v.asIdeal with hM
  -- `1 ∈ v * v⁻¹`, as a submodule of `K`
  have h1 : (1 : K) ∈
      (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹ := by
    rw [FractionalIdeal.coe_ideal_mul_inv _ v.ne_bot]
    exact (FractionalIdeal.mem_one_iff _).mpr ⟨1, map_one _⟩
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at h1
  -- every element of the product that is an `S`-integer lies in `M`
  refine Ideal.eq_top_iff_one M |>.mpr ?_
  suffices H : ∀ x ∈ (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹,
      ∃ hx : x ∈ A, (⟨x, hx⟩ : A) ∈ M by
    obtain ⟨hx, hx'⟩ := H 1 (by rwa [← FractionalIdeal.coe_mul, FractionalIdeal.mem_coe] at h1)
    exact (show (⟨1, hx⟩ : A) = 1 from rfl) ▸ hx'
  intro x hx
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at hx
  refine Submodule.mul_induction_on hx (fun a ha y hy ↦ ?_) (fun x y hx hy ↦ ?_)
  · obtain ⟨a, ha', rfl⟩ := (FractionalIdeal.mem_coeIdeal R⁰).mp
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K))).mpr ha)
    have hyA : y ∈ A := fun w hw ↦ valuation_le_one_of_mem_inv K
      (show w ≠ v by rintro rfl; exact hw hv)
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K)⁻¹)).mpr hy)
    have haA : algebraMap R K a ∈ A := A.algebraMap_mem a
    refine ⟨mul_mem haA hyA, ?_⟩
    have he : (⟨algebraMap R K a * y, mul_mem haA hyA⟩ : A) = algebraMap R A a * ⟨y, hyA⟩ := rfl
    rw [he]
    exact Ideal.mul_mem_right _ M (Ideal.mem_map_of_mem _ ha')
  · obtain ⟨hx, hx'⟩ := hx
    obtain ⟨hy, hy'⟩ := hy
    exact ⟨add_mem hx hy, add_mem hx' hy'⟩

/-!
### Ideals of `𝒪_S` are extended from `R`

Let `I` be an ideal of `𝒪_S` and `J = I ∩ R` its contraction. For `x ∈ I` the denominator ideal
`𝔡 x = {r : R | r * x ∈ R}` is divisible only by primes in `S`, because `x` is `w`-integral for
`w ∉ S`. Hence `𝔡 x * 𝒪_S = ⊤` by `integer_map_asIdeal_eq_top`, so `1 = ∑ dᵢ cᵢ` with `dᵢ ∈ 𝔡 x` and
`cᵢ ∈ 𝒪_S`, and `x = ∑ (dᵢ * x) * cᵢ` exhibits `x` as an element of `J * 𝒪_S`, since
`dᵢ * x ∈ R ∩ I = J`.

Noetherianity is immediate from this: `J` is finitely generated as `R` is Noetherian, hence so
is its extension `I`.
-/

/-- The denominator ideal of an `S`-integer is not contained in any prime off `S`: at such a
prime `x` is integral, so it has a denominator away from the prime. -/
lemma denomIdeal_not_le {x : K} {w : HeightOneSpectrum R} (hx : w.valuation K x ≤ 1) :
    ¬ Algebra.denomIdeal K x ≤ w.asIdeal := by
  obtain ⟨n, d, hnd⟩ := HeightOneSpectrum.exists_primeCompl_mul_eq_of_integer w x hx
  refine fun hle ↦ d.property (hle ?_)
  rw [Algebra.mem_denomIdeal_iff]
  exact ⟨n, by rw [mul_comm]; exact hnd⟩

/-- The denominator ideal of an `S`-integer extends to the unit ideal of `𝒪_S`: all its prime
factors lie in `S`, and each of those extends to the unit ideal by `integer_map_asIdeal_eq_top`. -/
@[simp] lemma integer_map_denomIdeal_eq_top {x : K} (hx : x ∈ S.integer K) :
    Ideal.map (algebraMap R (S.integer K)) (Algebra.denomIdeal K x) = ⊤ := by
  by_contra h
  obtain ⟨M, hM, hle⟩ := Ideal.exists_le_maximal _ h
  have h𝔭le : Algebra.denomIdeal K x ≤ M.comap (algebraMap R (S.integer K)) :=
    (Ideal.le_comap_map).trans (Ideal.comap_mono hle)
  have h𝔭ne : M.comap (algebraMap R (S.integer K)) ≠ ⊥ :=
    fun h0 ↦ Algebra.denomIdeal_ne_bot K x (le_bot_iff.mp (h0 ▸ h𝔭le))
  have hprime : (M.comap (algebraMap R (S.integer K))).IsPrime := hM.isPrime.comap _
  have hwS : (⟨_, hprime, h𝔭ne⟩ : HeightOneSpectrum R) ∈ S :=
    by_contra fun hwn ↦ denomIdeal_not_le K (hx _ hwn) h𝔭le
  have htop := integer_map_asIdeal_eq_top K S hwS
  exact hM.ne_top (top_le_iff.mp (htop.ge.trans Ideal.map_comap_le))

/-- **Every ideal of `𝒪_S` is extended from `R`.** -/
@[simp] theorem integer_map_comap_eq (I : Ideal (S.integer K)) :
    Ideal.map (algebraMap R (S.integer K)) (I.comap (algebraMap R (S.integer K))) = I := by
  refine le_antisymm Ideal.map_comap_le fun x hx ↦ ?_
  set f := algebraMap R (S.integer K) with hf
  set J' := Ideal.map f (I.comap f) with hJ'
  have coeval (r : R) : ((f r : S.integer K) : K) = algebraMap R K r := by
    rw [IsScalarTower.algebraMap_apply R (S.integer K) K]; rfl
  -- for a denominator `d` of `x`, the product `f d * x` is extended from `R` and lies in `I`
  have key (d : R) (hd : d ∈ Algebra.denomIdeal K (x : K)) : f d * x ∈ J' := by
    rw [Algebra.mem_denomIdeal_iff] at hd
    obtain ⟨s, hs⟩ := hd
    have hfx : f d * x = f s := by
      apply Subtype.val_injective
      rw [Subalgebra.coe_mul, coeval d, coeval s, hs]
    rw [hfx]
    exact Ideal.mem_map_of_mem f (show f s ∈ I from hfx ▸ I.mul_mem_left _ hx)
  -- the elements `r` with `r * x ∈ J'` form an ideal containing the extension of `denomIdeal`
  let K' : Ideal (S.integer K) :=
    { carrier := {r | r * x ∈ J'}
      zero_mem' := by simp
      add_mem' := fun {a b} ha hb ↦ by simpa [add_mul] using J'.add_mem ha hb
      smul_mem' := fun c {a} ha ↦ by
        simpa only [smul_eq_mul, Set.mem_ofPred_eq, mul_assoc] using J'.mul_mem_left c ha }
  have hsub : Ideal.map f (Algebra.denomIdeal K (x : K)) ≤ K' := Ideal.map_le_iff_le_comap.mpr key
  have hmtop : Ideal.map f (Algebra.denomIdeal K (x : K)) = ⊤ :=
    integer_map_denomIdeal_eq_top K S x.property
  have h1 : (1 : S.integer K) * x ∈ J' := hsub (hmtop.ge Submodule.mem_top)
  simpa using h1

/-!
### The Dedekind property
-/

/-- The ring of `S`-integers is Noetherian: every ideal is extended from the Noetherian
ring `R` by `integer_map_comap_eq`. -/
instance integer_isNoetherianRing : IsNoetherianRing (S.integer K) := by
  refine (isNoetherianRing_iff_ideal_fg _).mpr fun I ↦ ?_
  rw [← integer_map_comap_eq K S I]
  exact Ideal.FG.map (IsNoetherian.noetherian (R := R) (I.comap (algebraMap R (S.integer K))))
    (algebraMap R (S.integer K))

/-- The contraction to `R` of a nonzero prime of `𝒪_S` is a nonzero prime: if it were zero, the
prime would be `map ⊥ = ⊥` by `integer_map_comap_eq`. -/
lemma integer_comap_ne_bot {P : Ideal (S.integer K)} (hP : P ≠ ⊥) :
    P.comap (algebraMap R (S.integer K)) ≠ ⊥ := by
  intro h0
  exact hP (by rw [← integer_map_comap_eq K S P, h0, Ideal.map_bot])

/-- The ring of `S`-integers has Krull dimension at most `1`: the contraction to `R` of a
nonzero prime is maximal, and equalities of ideals lift back through `integer_map_comap_eq`. -/
instance integer_dimensionLEOne : Ring.DimensionLEOne (S.integer K) := by
  refine ⟨fun {P} hP hPp ↦ ?_⟩
  set f := algebraMap R (S.integer K) with hf
  -- pass to a maximal ideal `M` above `P` and compare contractions in `R`
  obtain ⟨M, hM, hPM⟩ := P.exists_le_maximal hPp.ne_top
  have hcP : P.comap f ≠ ⊥ := integer_comap_ne_bot K S hP
  have hMne : M ≠ ⊥ := fun h ↦ hP (le_bot_iff.mp (h ▸ hPM))
  have hcM : M.comap f ≠ ⊥ := integer_comap_ne_bot K S hMne
  -- both contractions are maximal in `R`, and one contains the other, so they are equal
  have hcPmax : (P.comap f).IsMaximal :=
    Ring.DimensionLEOne.maximalOfPrime hcP (hPp.comap f)
  have hcMprime : (M.comap f).IsPrime := hM.isPrime.comap f
  have heq : P.comap f = M.comap f :=
    hcPmax.eq_of_le hcMprime.ne_top (Ideal.comap_mono hPM)
  -- lift the equality back through `integer_map_comap_eq`
  rwa [← integer_map_comap_eq K S P, heq, integer_map_comap_eq K S M]

/-- **The ring of `S`-integers of a Dedekind domain is a Dedekind domain.** -/
instance integer_isDedekindDomain : IsDedekindDomain (S.integer K) where



end IsDedekindDomain

end
