/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.Algebra.Ring.Subgroup
public import Mathlib.Algebra.Ring.Subring.Basic

/-!
# Additive closures in rings

This file gives criteria for the additive closure of a set in a ring to be closed under
multiplication, and hence to coincide with the underlying additive subgroup of the subring
generated by that set.

## Main results

* `TauCeti.AddSubgroup.mul_mem_closure_of_mul_mem`: products of elements of an additive closure
  remain in the closure when this holds for its generators.
* `TauCeti.AddSubgroup.closure_mul_closure`: the product of two additive closures is the additive
  closure of the pairwise products.
* `Subring.toAddSubgroup_closure_of_one_mem_of_mul_mem`: under the corresponding
  hypotheses, the subring and additive-subgroup closures have the same underlying additive group.
-/

public section

open scoped Pointwise

namespace TauCeti

namespace AddSubgroup

variable {R : Type*} [NonUnitalNonAssocRing R]

/-- The product of two additive closures is the additive closure of the pairwise products. -/
theorem closure_mul_closure (S T : Set R) :
    AddSubgroup.closure S * AddSubgroup.closure T = AddSubgroup.closure (S * T) := by
  apply le_antisymm
  · intro z hz
    refine AddSubmonoid.mul_induction_on hz (fun x hx y hy => ?_)
      (fun _ _ => AddSubgroup.add_mem _)
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
        induction hy using AddSubgroup.closure_induction with
        | mem y hy => exact AddSubgroup.subset_closure ⟨x, hx, y, hy, rfl⟩
        | zero => simp
        | add y z _ _ hy hz => simpa [mul_add] using AddSubgroup.add_mem _ hy hz
        | neg y _ hy => simpa [mul_neg] using AddSubgroup.neg_mem _ hy
    | zero => simp
    | add x z _ _ hx hz => simpa [add_mul] using AddSubgroup.add_mem _ hx hz
    | neg x _ hx => simpa [neg_mul] using AddSubgroup.neg_mem _ hx
  · rw [AddSubgroup.closure_le]
    rintro _ ⟨x, hx, y, hy, rfl⟩
    exact AddSubmonoid.mul_mem_mul (AddSubgroup.subset_closure hx)
      (AddSubgroup.subset_closure hy)

end AddSubgroup

/-- If products of generators lie in their additive closure, then that additive closure is
closed under multiplication. -/
theorem AddSubgroup.mul_mem_closure_of_mul_mem {R : Type*} [NonUnitalNonAssocRing R] {s : Set R}
    (hs : ∀ x ∈ s, ∀ y ∈ s, x * y ∈ AddSubgroup.closure s) {x y : R}
    (hx : x ∈ AddSubgroup.closure s) (hy : y ∈ AddSubgroup.closure s) :
    x * y ∈ AddSubgroup.closure s := by
  induction hx, hy using AddSubgroup.closure_induction₂ with
  | mem x y hx hy => exact hs x hx y hy
  | zero_left => simp
  | zero_right => simp
  | add_left _ _ _ _ _ _ hx hy => simpa [add_mul] using AddSubgroup.add_mem _ hx hy
  | add_right _ _ _ _ _ _ hx hy => simpa [mul_add] using AddSubgroup.add_mem _ hx hy
  | neg_left _ _ _ _ hx => simpa [neg_mul] using AddSubgroup.neg_mem _ hx
  | neg_right _ _ _ _ hx => simpa [mul_neg] using AddSubgroup.neg_mem _ hx

/-- If the additive closure of a set contains one and products of generators lie in that closure,
then it is the underlying additive subgroup of the subring closure of the set. -/
theorem _root_.Subring.toAddSubgroup_closure_of_one_mem_of_mul_mem {R : Type*} [NonAssocRing R]
    {s : Set R}
    (h1 : (1 : R) ∈ AddSubgroup.closure s)
    (hmul : ∀ x ∈ s, ∀ y ∈ s, x * y ∈ AddSubgroup.closure s) :
    (Subring.closure s).toAddSubgroup = AddSubgroup.closure s := by
  refine le_antisymm (fun x hx => ?_) ((AddSubgroup.closure_le _).2 fun x hx => ?_)
  · rw [Subring.mem_toAddSubgroup] at hx
    induction hx using Subring.closure_induction with
    | mem x hx => exact AddSubgroup.subset_closure hx
    | zero => exact zero_mem _
    | one => exact h1
    | add _ _ _ _ hx hy => exact add_mem hx hy
    | neg _ _ hx => exact neg_mem hx
    | mul _ _ _ _ hx hy => exact AddSubgroup.mul_mem_closure_of_mul_mem hmul hx hy
  · exact Subring.mem_toAddSubgroup.2 (Subring.subset_closure hx)

end TauCeti
