/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.IntermediateField.ExtendRight
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Finrank

/-!
# The tower `K⟮g⟯ ⊆ K(x) ⊆ K(W)` over an arbitrary generator

For a rational function `g`, the subfield `K⟮g⟯` of `K(x)` has a copy inside the function field
`K(W)` of a Weierstrass curve. This file computes the two degrees of the resulting tower in terms
of the single input `[K(x) : K⟮g⟯]`: the inner storey contributes that degree, the outer storey
contributes two, and an embedding of function fields carrying the affine coordinate to `g` has
image of index exactly `[K(x) : K⟮g⟯]`.

Everything here is generator-agnostic. A caller supplies `g` together with a theorem computing
`Module.finrank K⟮g⟯ (RatFunc K)`, and gets the whole tower back; `PowerTower.lean` does this for
`g = X ^ n`, where that degree is `n`.

## Main definitions

* `WeierstrassCurve.Affine.ratFuncAdjoinRange`: the copy of `K⟮g⟯` inside `K(W)`, with
  `ratFuncAdjoinRange_eq_map` and `mem_ratFuncAdjoinRange` as its interface and
  `algebraMap_mem_ratFuncAdjoinRange` for its generator.

## Main results

* `WeierstrassCurve.Affine.relfinrank_ratFuncAdjoinRange`: `[K(x) : K⟮g⟯]`, read inside `K(W)`.
* `WeierstrassCurve.Affine.finrank_ratFuncAdjoinRange`: `[K(W) : K⟮g⟯] = 2 · [K(x) : K⟮g⟯]`.
* `WeierstrassCurve.Affine.ratFuncAdjoinRange_eq_map_ratFuncRange` and
  `WeierstrassCurve.Affine.finrank_fieldRange_of_apply_X_eq`: for any embedding
  `f : K(W') → K(W)` of function fields sending the affine coordinate of `W'` to `g`, the copy of
  `K⟮g⟯` is the image of `K(x')`, and `[K(W) : f(K(W'))] = [K(x) : K⟮g⟯]`.

No result needs `W` to be elliptic: the Weierstrass equation alone gives the power basis, through
`finrank_ratFuncRange`.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 1**. The Frobenius and multiplication-by-`n`
degree computations are both specialisations of this tower.

## Provenance

This generalises `Affine/FunctionField/PowerTower.lean`, which carried the identical construction
and proofs for the single generator `X ^ n`; that file now derives its API from this one, and the
argument, naming scheme and proof shapes are its. The finite-field ancestor of both is the AINTLIB
`HasseWeil` project (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, pinned at
`513e83879e2f8cbc626eb9e04d660e92be16ccba`), `HasseWeil/FrobeniusIsogeny.lean`, private
declarations `frobFracRange`, `frobFracRange_le_frobRange`, `finrank_frobFracRange_functionField`
and `finrank_over_frobenius_image`, where the exponent is the cardinality of a finite field.
-/

public section

open Polynomial IntermediateField

open scoped RatFunc

namespace WeierstrassCurve.Affine

variable {K : Type*} [Field K] (W : WeierstrassCurve.Affine K)

/-- The image of the field `K⟮g⟯` generated by a rational function `g`, inside `K(W)`.

This is Mathlib's `IntermediateField.extendRight` at `IntermediateField.adjoin K {g}`, named for
this setting because the statements below would otherwise carry an 85-character term. -/
noncomputable def ratFuncAdjoinRange (g : RatFunc K) : IntermediateField K W.FunctionField :=
  (IntermediateField.adjoin K {g}).extendRight W.FunctionField

/-- `K⟮g⟯`'s copy in `K(W)` is the image of `K⟮g⟯` under the inclusion `K(x) ⊆ K(W)`. -/
-- Load-bearing rather than an unfolding convenience: `extendRight` is spelled with
-- `Algebra.algHom` while `ratFuncRange_eq_map` produces `IsScalarTower.toAlgHom`, so
-- `relfinrank_map_map` does not unify against the two without this, though the maps are one term.
theorem ratFuncAdjoinRange_eq_map (g : RatFunc K) :
    ratFuncAdjoinRange W g = (IntermediateField.adjoin K {g}).map
      (IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField) := by
  -- `extendRight` unfolds to exactly this `map`; what `rfl` closes is the last step,
  -- `Algebra.algHom = IsScalarTower.toAlgHom`, which is an alias rather than a new definition.
  rfl

/-- An element of `K(W)` lies in the copy of `K⟮g⟯` exactly when it is the image there of an
element of `K⟮g⟯`. -/
@[simp]
theorem mem_ratFuncAdjoinRange {g : RatFunc K} {z : W.FunctionField} :
    z ∈ ratFuncAdjoinRange W g ↔ ∃ r ∈ IntermediateField.adjoin K {g},
      IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField r = z := by
  rw [ratFuncAdjoinRange_eq_map]
  exact IntermediateField.mem_map _

/-- The generator: `g` itself lies in the copy of `K⟮g⟯`. -/
theorem algebraMap_mem_ratFuncAdjoinRange (g : RatFunc K) :
    algebraMap (RatFunc K) W.FunctionField g ∈ ratFuncAdjoinRange W g :=
  (mem_ratFuncAdjoinRange W).mpr ⟨g, IntermediateField.mem_adjoin_simple_self _ _, rfl⟩

/-- `K⟮g⟯` sits inside `K(x)`, both read inside `K(W)`. -/
theorem ratFuncAdjoinRange_le_ratFuncRange (g : RatFunc K) :
    ratFuncAdjoinRange W g ≤ ratFuncRange W := by
  rw [ratFuncAdjoinRange_eq_map, ratFuncRange_eq_map]
  exact IntermediateField.map_mono _ le_top

/-- **`[K(x) : K⟮g⟯]`, read inside `K(W)`**, is the degree it has inside `K(x)` itself. -/
@[simp]
theorem relfinrank_ratFuncAdjoinRange (g : RatFunc K) :
    relfinrank (ratFuncAdjoinRange W g) (ratFuncRange W) =
      Module.finrank (IntermediateField.adjoin K {g}) (RatFunc K) := by
  rw [ratFuncAdjoinRange_eq_map, ratFuncRange_eq_map, relfinrank_map_map, relfinrank_top_right]

/-- **`[K(W) : K⟮g⟯] = 2 · [K(x) : K⟮g⟯]`**: the inner storey contributes the degree of `g` and
the outer one contributes two. When `K(x)` is infinite-dimensional over `K⟮g⟯` both sides are `0`,
`Module.finrank`'s value there. -/
@[simp]
theorem finrank_ratFuncAdjoinRange (g : RatFunc K) :
    Module.finrank (ratFuncAdjoinRange W g) W.FunctionField =
      2 * Module.finrank (IntermediateField.adjoin K {g}) (RatFunc K) := by
  rw [← relfinrank_mul_finrank_top (ratFuncAdjoinRange_le_ratFuncRange W g),
    relfinrank_ratFuncAdjoinRange, finrank_ratFuncRange, Nat.mul_comm]

/-- If an intermediate field has relative degree two over `K⟮g⟯`, the degree of `K(W)` over it is
`[K(x) : K⟮g⟯]`. This is the final tower step of `finrank_fieldRange_of_apply_X_eq`. -/
private theorem finrank_of_relfinrank_ratFuncAdjoinRange {g : RatFunc K}
    {L : IntermediateField K W.FunctionField} (hle : ratFuncAdjoinRange W g ≤ L)
    (h : relfinrank (ratFuncAdjoinRange W g) L = 2) :
    Module.finrank L W.FunctionField =
      Module.finrank (IntermediateField.adjoin K {g}) (RatFunc K) := by
  have htower := relfinrank_mul_finrank_top hle
  rw [h, finrank_ratFuncAdjoinRange] at htower
  exact Nat.eq_of_mul_eq_mul_left two_pos htower

-- The map of a simple adjoin is the simple adjoin of the image. Naming it keeps the theorem
-- below from threading `IntermediateField.adjoin_map` and `Set.image_singleton` through a longer
-- rewrite chain.
private theorem map_adjoin_singleton {L M : Type*} [Field L] [Field M] [Algebra K L] [Algebra K M]
    (f : L →ₐ[K] M) (x : L) :
    (IntermediateField.adjoin K {x}).map f = IntermediateField.adjoin K {f x} := by
  rw [IntermediateField.adjoin_map, Set.image_singleton]

/-- **The copy of `K⟮g⟯` inside `K(W)` is the image of the rational function field of `W'`**, for
any embedding `f : K(W') → K(W)` of function fields carrying the affine coordinate of `W'` to `g`.
This is the field the degree tower below is anchored at, in its two descriptions. -/
theorem ratFuncAdjoinRange_eq_map_ratFuncRange {W' : WeierstrassCurve.Affine K} {g : RatFunc K}
    (f : W'.FunctionField →ₐ[K] W.FunctionField)
    (hf : f (algebraMap K[X] W'.FunctionField X) = algebraMap (RatFunc K) W.FunctionField g) :
    ratFuncAdjoinRange W g = (ratFuncRange W').map f := by
  rw [ratFuncAdjoinRange_eq_map, ratFuncRange_eq_map, IntermediateField.map_map,
    ← RatFunc.adjoin_X, map_adjoin_singleton, map_adjoin_singleton]
  simp only [AlgHom.coe_comp, Function.comp_apply, toAlgHom_ratFuncX, hf]
  rw [IsScalarTower.coe_toAlgHom']

/-- **`[K(W) : f(K(W'))] = [K(x) : K⟮g⟯]`** for an embedding `f : K(W') → K(W)` of function fields
carrying the affine coordinate of `W'` to `g`. Both `K(x)` and the image of `K(W')` lie between
`K⟮g⟯` and `K(W)`, of relative degrees `[K(x) : K⟮g⟯]` and `2` over it; since `[K(W) : K(x)] = 2`
as well, the two towers give `2 · [K(W) : f(K(W'))] = 2 · [K(x) : K⟮g⟯]`. -/
theorem finrank_fieldRange_of_apply_X_eq {W' : WeierstrassCurve.Affine K} {g : RatFunc K}
    (f : W'.FunctionField →ₐ[K] W.FunctionField)
    (hf : f (algebraMap K[X] W'.FunctionField X) = algebraMap (RatFunc K) W.FunctionField g) :
    Module.finrank f.fieldRange W.FunctionField =
      Module.finrank (IntermediateField.adjoin K {g}) (RatFunc K) := by
  have h := ratFuncAdjoinRange_eq_map_ratFuncRange W f hf
  refine finrank_of_relfinrank_ratFuncAdjoinRange W ?_ ?_
  · rw [h, AlgHom.fieldRange_eq_map]
    exact IntermediateField.map_mono _ le_top
  · rw [h, relfinrank_map_ratFuncRange_fieldRange]

end WeierstrassCurve.Affine

end
