/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Point.Coords

/-!
# The generic point of a Weierstrass curve

The affine coordinate ring `R[W]` of a Weierstrass curve `W` is generated by the two coordinate
functions, and their images in the function field `R(W)` satisfy the Weierstrass equation of `W`
base changed to `R(W)` — tautologically, since that equation is the defining relation of `R[W]`.
Over a field, and for an elliptic curve, the resulting solution is nonsingular, so it is a point of
`W⁄F(W)`: the **generic point** of `W`. It is the identity morphism of `W`, read as a point with
coordinates in the function field, and it is the object that turns statements about morphisms of
`W` into statements about the point group of a single base change.

## Main definitions

* `WeierstrassCurve.Affine.genericX` and `WeierstrassCurve.Affine.genericY`: the
  two coordinate functions, as elements of the function field.
* `WeierstrassCurve.Affine.genericPoint`: the point of `W⁄F(W)` they cut out.

## Main results

* `WeierstrassCurve.Affine.equation_genericX_genericY`: the two coordinate functions
  satisfy the Weierstrass equation of the base change. Stated over an arbitrary commutative ring:
  it is the defining relation of the coordinate ring and needs no ellipticity.
* `WeierstrassCurve.Affine.transcendental_genericX` and
  `WeierstrassCurve.Affine.genericX_ne_algebraMap`: the coordinate `x` is transcendental
  over the base field, so it takes no constant value.
* `WeierstrassCurve.Affine.instIsEllipticBaseChange`: an elliptic curve stays elliptic
  under base change. Mathlib has this for `W.map f` but not for `W⁄A`, which is the form the point
  group of a base change is stated over.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 0.5**, whose third milestone asks for the
"function-field pullbacks of the translations `τ_P`, with the action and composition laws". Those
pullbacks are evaluation at the translates of the generic point, built in
`TauCeti/AlgebraicGeometry/EllipticCurve/Affine/FunctionField/Translation.lean`; this file is the
point they translate.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2.

## Provenance

Not a port: none of the pinned sources introduces the generic point. The equation at the generic
point is the coordinate-ring relation `AdjoinRoot.mk_self`, pushed into the fraction field.
-/

public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace WeierstrassCurve.Affine

variable {R : Type*} [CommRing R] (W : _root_.WeierstrassCurve.Affine R)

/-- The affine coordinate `x` of `W`, as an element of the function field. -/
noncomputable def genericX : W.FunctionField :=
  algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W (C X))

/-- The affine coordinate `y` of `W`, as an element of the function field. -/
noncomputable def genericY : W.FunctionField :=
  algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W Y)

/-- The equation lemma for `genericX`, which the module boundary makes necessary. -/
theorem genericX_def :
    genericX W = algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W (C X)) := (rfl)

/-- The equation lemma for `genericY`, which the module boundary makes necessary. -/
theorem genericY_def :
    genericY W = algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W Y) := (rfl)

theorem genericX_eq_algebraMap : genericX W = algebraMap R[X] W.FunctionField X := by
  rw [genericX_def, IsScalarTower.algebraMap_apply R[X] W.CoordinateRing W.FunctionField,
    AdjoinRoot.algebraMap_eq]
  (rfl)

/-- **The two coordinate functions satisfy the Weierstrass equation of the base change to the
function field**: they are the coordinates of the generic point. -/
theorem equation_genericX_genericY :
    (W.map (algebraMap R W.FunctionField)).toAffine.Equation (genericX W) (genericY W) := by
  have key : (evalEvalRingHom (genericX W) (genericY W)).comp
      (mapRingHom (mapRingHom (algebraMap R W.FunctionField))) =
      (algebraMap W.CoordinateRing W.FunctionField).comp (CoordinateRing.mk W) := by
    apply Polynomial.ringHom_ext'
    · apply Polynomial.ringHom_ext'
      · ext r
        have hmk : CoordinateRing.mk W (C (C r)) = algebraMap R W.CoordinateRing r := by
          rw [IsScalarTower.algebraMap_apply R R[X] W.CoordinateRing, AdjoinRoot.algebraMap_eq]
          (rfl)
        simp only [RingHom.comp_apply, hmk,
          ← IsScalarTower.algebraMap_apply R W.CoordinateRing W.FunctionField]
        simp
      · simp [genericX_def]
    · simp [genericY_def]
  have h := RingHom.congr_fun key W.polynomial
  simp only [RingHom.comp_apply, AdjoinRoot.mk_self, map_zero] at h
  rw [Affine.Equation, Affine.map_polynomial]
  exact h

section Field

variable {F : Type*} [Field F] (W : _root_.WeierstrassCurve.Affine F)

/-- **The coordinate function `x` is transcendental over the base field.** -/
theorem transcendental_genericX : Transcendental F (genericX W) := by
  rw [genericX_eq_algebraMap]
  exact (transcendental_algebraMap_iff
    (FaithfulSMul.algebraMap_injective F[X] W.FunctionField)).2 (Polynomial.transcendental_X F)

/-- **The coordinate function `x` takes no constant value**, being transcendental. -/
theorem genericX_ne_algebraMap (x₁ : F) : genericX W ≠ algebraMap F W.FunctionField x₁ :=
  fun hc ↦ transcendental_genericX W (hc ▸ isAlgebraic_algebraMap _)

variable [W.IsElliptic]

/-- Mathlib records that a map of an elliptic curve stays elliptic, but not the base-change form
`W⁄A`, which is the one the point group is stated over. -/
instance instIsEllipticBaseChange {A : Type*} [CommRing A] [Algebra F A] : (W⁄A).IsElliptic :=
  inferInstanceAs ((W.map (algebraMap F A)).IsElliptic)

/-- The generic point is nonsingular. -/
theorem nonsingular_genericX_genericY :
    (W⁄W.FunctionField).toAffine.Nonsingular (genericX W) (genericY W) :=
  Affine.equation_iff_nonsingular.1 (equation_genericX_genericY W)

/-- **The generic point of `W`**: the tautological point of `W` with coordinates in its own
function field. -/
noncomputable def genericPoint : (W⁄W.FunctionField).toAffine.Point :=
  .some _ _ (nonsingular_genericX_genericY W)

/-- The equation lemma for `genericPoint`, which the module boundary makes necessary. -/
theorem genericPoint_eq_some : genericPoint W =
    .some (genericX W) (genericY W) (nonsingular_genericX_genericY W) := (rfl)

@[simp]
theorem xCoord_genericPoint : Point.xCoord (genericPoint W) = genericX W :=
  Point.xCoord_some _

@[simp]
theorem yCoord_genericPoint : Point.yCoord (genericPoint W) = genericY W :=
  Point.yCoord_some _

end Field

end WeierstrassCurve.Affine

end
