/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.AdjoinTower
public import TauCeti.FieldTheory.RatFunc.PowerTower

/-!
# Power subfields of the function field of a Weierstrass curve

For any field `K`, exponent `n`, and Weierstrass curve `W`, this file packages the tower
`K(x^n) ⊆ K(x) ⊆ K(W)` and computes `[K(W) : K(x^n)] = 2n`.

It is the generator `X ^ n` case of `AdjoinTower.lean`, which proves the same tower for an
arbitrary rational function; the single input this file supplies is
`TauCeti.RatFunc.finrank_adjoin_X_pow`, that `[K(x) : K⟮X ^ n⟯] = n`. Every declaration below is
that file's counterpart specialised, so the names and statements are unchanged for consumers.

At `n = 0`, the displayed degree formulas use `Module.finrank`'s value `0` for an
infinite-dimensional extension: `K(x^0) = K`, so both sides of each formula read `0`.

## Main results

* `WeierstrassCurve.Affine.ratFuncAdjoinXPowRange`: the copy of `K(x^n)` inside `K(W)`, with
  `ratFuncAdjoinXPowRange_eq_map` and `mem_ratFuncAdjoinXPowRange` as its interface and
  `algebraMap_X_pow_mem_ratFuncAdjoinXPowRange` for its generator.
* `WeierstrassCurve.Affine.finrank_ratFuncAdjoinXPowRange`: `[K(W) : K(x^n)] = 2 * n`.
* `WeierstrassCurve.Affine.ratFuncAdjoinXPowRange_eq_map_ratFuncRange` and
  `WeierstrassCurve.Affine.finrank_fieldRange_of_apply_X_eq_pow`: for any embedding
  `f : K(W') → K(W)` of function fields sending the affine coordinate of `W'` to `x ^ n`, the copy
  of `K(x^n)` is the image of `K(x')`, and `[K(W) : f(K(W'))] = n`. This is the whole tower
  comparison behind a degree of an inseparable isogeny; the absolute and the relative Frobenius
  each supply their own `hf` and read off their degree.

No result needs `W` to be elliptic: the Weierstrass equation alone gives the power basis.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 1**. The finite-field Frobenius and relative
Frobenius degree computations both use this tower.

## Provenance

The tower argument now lives in `Affine/FunctionField/AdjoinTower.lean`, generalised over its
generator; this file holds the `X ^ n` specialisation and its provenance is recorded there. Its
finite-field ancestor is the AINTLIB `HasseWeil` project (`github.com/CBirkbeck/AINTLIB`,
Apache-2.0, pinned by that roadmap at `dev/hasse-weil @ 513e83879e2f`),
`HasseWeil/FrobeniusIsogeny.lean`, where the exponent is the cardinality of a finite field and the
embedding is the `q`-power map. The rational-function input `TauCeti.RatFunc.finrank_adjoin_X_pow`
is recorded in `TauCeti/FieldTheory/RatFunc/PowerTower.lean`; the finite-field specialisation stays
in `Affine/FunctionField/FrobeniusTower.lean`.
-/

public section

open Polynomial WeierstrassCurve IntermediateField

open scoped RatFunc

namespace WeierstrassCurve.Affine

variable {K : Type*} [Field K] (W : WeierstrassCurve.Affine K)

/-- `x ^ n`, read through `K(x)` rather than through `K[X]`. The three tower lemmas below all
need this one coercion step, so it is named once rather than repeated. -/
private theorem algebraMap_X_pow_eq_algebraMap_ratFuncX_pow (n : ℕ) :
    algebraMap K[X] W.FunctionField X ^ n
      = algebraMap (RatFunc K) W.FunctionField ((RatFunc.X : RatFunc K) ^ n) := by
  rw [map_pow, ← toAlgHom_ratFuncX, IsScalarTower.coe_toAlgHom']

/-- The image of the field generated by `X ^ n` inside `K(W)`. This is
`ratFuncAdjoinRange` at the generator `X ^ n`; everything below is that file's tower read
through `TauCeti.RatFunc.finrank_adjoin_X_pow`, which supplies `[K(x) : K⟮X ^ n⟯] = n`. -/
noncomputable def ratFuncAdjoinXPowRange (n : ℕ) : IntermediateField K W.FunctionField :=
  ratFuncAdjoinRange W ((RatFunc.X : RatFunc K) ^ n)

/-- The defining equation of `ratFuncAdjoinXPowRange`, in the form used by
`IntermediateField.map` lemmas. -/
theorem ratFuncAdjoinXPowRange_eq_map (n : ℕ) :
    ratFuncAdjoinXPowRange W n = (IntermediateField.adjoin K {(RatFunc.X : RatFunc K) ^ n}).map
      (IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField) := by
  rw [ratFuncAdjoinXPowRange, ratFuncAdjoinRange_eq_map]

/-- An element of `K(W)` lies in the copy of `K(x^n)` exactly when it is the image there of an
element of `K(X^n)`. -/
@[simp]
theorem mem_ratFuncAdjoinXPowRange {n : ℕ} {z : W.FunctionField} :
    z ∈ ratFuncAdjoinXPowRange W n ↔ ∃ r ∈ IntermediateField.adjoin K {(RatFunc.X : RatFunc K) ^ n},
      IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField r = z := by
  rw [ratFuncAdjoinXPowRange]
  exact mem_ratFuncAdjoinRange W

/-- The generator: `x ^ n` lies in the copy of `K(x^n)`. -/
theorem algebraMap_X_pow_mem_ratFuncAdjoinXPowRange (n : ℕ) :
    algebraMap K[X] W.FunctionField X ^ n ∈ ratFuncAdjoinXPowRange W n := by
  rw [ratFuncAdjoinXPowRange, algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]
  exact algebraMap_mem_ratFuncAdjoinRange W _

/-- `K(x^n)` sits inside `K(x)`, both read inside `K(W)`. -/
theorem ratFuncAdjoinXPowRange_le_ratFuncRange (n : ℕ) :
    ratFuncAdjoinXPowRange W n ≤ ratFuncRange W :=
  ratFuncAdjoinRange_le_ratFuncRange W _

/-- **`[K(x) : K(x^n)] = n`**, read inside `K(W)`. At `n = 0`, this is the `finrank` value
`0` for the infinite-dimensional extension `K(x) / K`. -/
@[simp]
theorem relfinrank_ratFuncAdjoinXPowRange (n : ℕ) :
    relfinrank (ratFuncAdjoinXPowRange W n) (ratFuncRange W) = n := by
  rw [ratFuncAdjoinXPowRange, relfinrank_ratFuncAdjoinRange,
    TauCeti.RatFunc.finrank_adjoin_X_pow]

/-- **`[K(W) : K(x^n)] = 2n`.** At `n = 0`, both sides are `0`: the extension over
`K(x^0) = K` is infinite-dimensional, and `Module.finrank` reports `0`. -/
@[simp]
theorem finrank_ratFuncAdjoinXPowRange (n : ℕ) :
    Module.finrank (ratFuncAdjoinXPowRange W n) W.FunctionField = 2 * n := by
  rw [ratFuncAdjoinXPowRange, finrank_ratFuncAdjoinRange,
    TauCeti.RatFunc.finrank_adjoin_X_pow]

/-- **The copy of `K(x^n)` inside `K(W)` is the image of the rational function field of `W'`**,
for any embedding `f : K(W') → K(W)` of function fields carrying the affine coordinate of `W'` to
`x ^ n`. This is the field the degree tower below is anchored at, in its two descriptions. -/
theorem ratFuncAdjoinXPowRange_eq_map_ratFuncRange {W' : WeierstrassCurve.Affine K} {n : ℕ}
    (f : W'.FunctionField →ₐ[K] W.FunctionField)
    (hf : f (algebraMap K[X] W'.FunctionField X) = algebraMap K[X] W.FunctionField X ^ n) :
    ratFuncAdjoinXPowRange W n = (ratFuncRange W').map f := by
  refine ratFuncAdjoinRange_eq_map_ratFuncRange W f ?_
  rw [hf, algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]

/-- **`[K(W) : f(K(W'))] = n`** for an embedding `f : K(W') → K(W)` of function fields carrying the
affine coordinate of `W'` to `x ^ n`. Both `K(x)` and the image of `K(W')` lie between `K(x^n)` and
`K(W)`, of relative degrees `n` and `2` over it; since `[K(W) : K(x)] = 2` as well, the two towers
give `2 · [K(W) : f(K(W'))] = 2n`. -/
theorem finrank_fieldRange_of_apply_X_eq_pow {W' : WeierstrassCurve.Affine K} {n : ℕ}
    (f : W'.FunctionField →ₐ[K] W.FunctionField)
    (hf : f (algebraMap K[X] W'.FunctionField X) = algebraMap K[X] W.FunctionField X ^ n) :
    Module.finrank f.fieldRange W.FunctionField = n := by
  rw [finrank_fieldRange_of_apply_X_eq W f (g := (RatFunc.X : RatFunc K) ^ n)
      (by rw [hf, algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]),
    TauCeti.RatFunc.finrank_adjoin_X_pow]

end WeierstrassCurve.Affine

end
