/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.FixedField
public import TauCeti.NumberTheory.RamificationInertia.Galois
public import TauCeti.NumberTheory.NumberField.Frobenius.DecompositionGroup
public import TauCeti.NumberTheory.NumberField.Frobenius.Tower

/-!
# The prime below an unramified prime in the fixed field of its Frobenius

Let `σ` be an arithmetic Frobenius at a nonzero prime `Q` of `𝓞 L` unramified over `𝓞 K`, and let
`E = L ^ ⟨σ⟩`.  Then `Q ∩ 𝓞 E` has residue degree one over `𝓞 K`.

The two inertia degrees in the tower `K ⊆ E ⊆ L` at `Q` are both `orderOf σ`: over `𝓞 K` because a
Frobenius element has order the inertia degree, and over `𝓞 E` because `Gal(L/E)` is generated by
`σ` and fixes `Q`, so the whole group is the decomposition group. Multiplicativity of the inertia
degree in a tower then leaves the factor one for the intermediate prime.

Two consequences follow, and together the three are what a fixed-field fibre count needs at each
prime: `Q` is the *only* prime of `𝓞 L` above `Q ∩ 𝓞 E`, because `Gal(L/E)` acts transitively on
those primes and fixes `Q`; and the arithmetic Frobenius over `E` at `Q` restricts to `σ` itself,
with no power taken, which is `NumberField.restrictScalars_eq_of_inertiaDeg_eq_one` at residue
degree one.

The inertness needs only that `σ` fixes `Q`, not that it is a Frobenius, and is stated that way.

## Main results

* `Ideal.inertiaDeg_under_fixedField_eq_one_of_isArithFrobAt`: the prime below `Q` in the field
  fixed by a Frobenius at `Q` has residue degree one over `𝓞 K`.
* `Ideal.eq_of_liesOver_under_fixedField`: `Q` is the only prime of `𝓞 L` above it.
* `Ideal.restrictScalars_eq_of_isArithFrobAt_fixedField`: an arithmetic Frobenius over the fixed
  field at `Q` restricts to `σ` itself.

## References

Sharifi, *Algebraic Number Theory*, Theorem 7.2.2.  The corresponding step of the
Birkbeck--Brasca Chebotarev development,
[CBirkbeck/chebotarev-density](https://github.com/CBirkbeck/chebotarev-density) (Apache-2.0) at
commit `55a89985d47a3befcf6069aca1da250ff088b5c7`, is the private declaration
`inertiaDeg_under_E_eq_one_of_frobenius` in `CebotarevDensity/FixedFieldDensity.lean`.  There it is
one conjunct of a triple that also records the ramification index and the residue-field count, and
it carries `orderOf σ = Nat.card Gal(L/E)` as a hypothesis; that equality is a consequence of the
Galois correspondence and is derived here rather than assumed.
-/

public section

open IntermediateField

open scoped NumberField Pointwise

namespace Ideal

variable {K L : Type*} [Field K] [NumberField K] [Field L] [NumberField L]
  [Algebra K L] [IsGalois K L]

/-- **The prime below `Q` in the fixed field of a Frobenius at `Q` has degree one.**  If `σ` is an
arithmetic Frobenius at a nonzero prime `Q` of `𝓞 L` unramified over `𝓞 K`, then `Q ∩ 𝓞 (L ^ ⟨σ⟩)`
has residue degree one over `𝓞 K`. -/
theorem inertiaDeg_under_fixedField_eq_one_of_isArithFrobAt (Q : Ideal (𝓞 L)) [Q.IsPrime]
    (hQ : Q ≠ ⊥) [Algebra.IsUnramifiedAt (𝓞 K) Q] {σ : L ≃ₐ[K] L}
    (hσ : IsArithFrobAt (𝓞 K) σ Q) :
    (Q.under (𝓞 ↥(fixedField (Subgroup.zpowers σ)))).inertiaDeg (𝓞 K) = 1 := by
  set E := fixedField (Subgroup.zpowers σ) with hE
  have : IsScalarTower K ↥E L := E.isScalarTower_mid'
  have : IsGalois ↥E L := IsGalois.tower_top_intermediateField _
  have hK : Q.inertiaDeg (𝓞 K) = orderOf σ :=
    (orderOf_eq_inertiaDeg_of_isArithFrobAt Q hQ hσ).symm
  have htower : Q.inertiaDeg (𝓞 K)
      = (Q.under (𝓞 ↥E)).inertiaDeg (𝓞 K) * Q.inertiaDeg (𝓞 ↥E) :=
    inertiaDeg_tower (Q.under (𝓞 ↥E)) Q
  have hE' : Q.inertiaDeg (𝓞 ↥E) = orderOf σ := by
    have : Algebra.IsUnramifiedAt (𝓞 ↥E) Q :=
      Algebra.IsUnramifiedAt.of_restrictScalars (𝓞 K) Q
    rw [← card_stabilizer_eq_inertiaDeg_of_isUnramifiedAt Q hQ,
      NumberField.stabilizer_fixedField_zpowers_eq_top hσ.mem_stabilizer, Subgroup.card_top,
      IsGalois.card_aut_eq_finrank, finrank_fixedField_eq_card, Nat.card_zpowers]
  rw [hK, hE'] at htower
  exact (Nat.eq_of_mul_eq_mul_right (orderOf_pos σ) (by rw [one_mul]; exact htower)).symm

/-- **The prime is inert over the fixed field.**  If `σ` fixes the prime `Q` of `𝓞 L`, then `Q` is
the only prime of `𝓞 L` above `Q ∩ 𝓞 (L ^ ⟨σ⟩)`.

`Gal(L / L ^ ⟨σ⟩)` acts transitively on the primes above a prime of the fixed field, and it fixes
`Q`, so the orbit is a single point.  Nothing here needs `σ` to be a Frobenius. -/
theorem eq_of_liesOver_under_fixedField {σ : L ≃ₐ[K] L} {Q : Ideal (𝓞 L)} [Q.IsPrime]
    (hQ : σ • Q = Q) (Q' : Ideal (𝓞 L)) [Q'.IsPrime]
    [Q'.LiesOver (Q.under (𝓞 ↥(fixedField (Subgroup.zpowers σ))))] :
    Q' = Q := by
  have : IsScalarTower K ↥(fixedField (Subgroup.zpowers σ)) L :=
    (fixedField (Subgroup.zpowers σ)).isScalarTower_mid'
  have : IsGalois ↥(fixedField (Subgroup.zpowers σ)) L :=
    IsGalois.tower_top_intermediateField _
  have : IsGaloisGroup (L ≃ₐ[↥(fixedField (Subgroup.zpowers σ))] L)
      ↥(fixedField (Subgroup.zpowers σ)) L := IsGaloisGroup.of_isGalois _ L
  have : Q.LiesOver (Q.under (𝓞 ↥(fixedField (Subgroup.zpowers σ)))) :=
    Ideal.over_under (A := 𝓞 ↥(fixedField (Subgroup.zpowers σ))) (P := Q)
  obtain ⟨τ, hτ⟩ := Ideal.exists_smul_eq_of_isGaloisGroup
    (Q.under (𝓞 ↥(fixedField (Subgroup.zpowers σ)))) Q Q'
    (L ≃ₐ[↥(fixedField (Subgroup.zpowers σ))] L)
  rw [← hτ]
  exact MulAction.mem_stabilizer_iff.mp
    (NumberField.stabilizer_fixedField_zpowers_eq_top hQ ▸ Subgroup.mem_top τ)

/-- **Over the fixed field the Frobenius does not move.**  An arithmetic Frobenius over
`E = L ^ ⟨σ⟩` at `Q` restricts to `σ` itself, with no power taken.

This is `NumberField.restrictScalars_eq_of_inertiaDeg_eq_one` supplied with the residue degree
computed above; a fixed-field fibre count is what needs it. -/
theorem restrictScalars_eq_of_isArithFrobAt_fixedField (Q : Ideal (𝓞 L)) [Q.IsPrime] (hQ : Q ≠ ⊥)
    [Algebra.IsUnramifiedAt (𝓞 K) Q] {σ : L ≃ₐ[K] L} (hσ : IsArithFrobAt (𝓞 K) σ Q)
    {τ : L ≃ₐ[↥(fixedField (Subgroup.zpowers σ))] L}
    (hτ : IsArithFrobAt (𝓞 ↥(fixedField (Subgroup.zpowers σ))) τ Q) :
    AlgEquiv.restrictScalars K τ = σ := by
  have : IsScalarTower K ↥(fixedField (Subgroup.zpowers σ)) L :=
    (fixedField (Subgroup.zpowers σ)).isScalarTower_mid'
  have : IsGalois ↥(fixedField (Subgroup.zpowers σ)) L :=
    IsGalois.tower_top_intermediateField _
  exact NumberField.restrictScalars_eq_of_inertiaDeg_eq_one hσ hτ
    (inertiaDeg_under_fixedField_eq_one_of_isArithFrobAt Q hQ hσ)

end Ideal
