/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.FixedField
public import TauCeti.NumberTheory.NumberField.Frobenius.DecompositionGroup

/-!
# The decomposition group over the field fixed by a Frobenius

Let `Q` be a prime of `𝓞 L` and `σ` an arithmetic Frobenius at `Q` over `K`.  Over `K` the
decomposition group of `Q` is exactly `⟨σ⟩`, which is
`Ideal.zpowers_eq_stabilizer_of_isArithFrobAt`.  Over the intermediate field `L ^ ⟨σ⟩` the same
group is the *whole* Galois group: `Gal(L / L ^ ⟨σ⟩)` is generated by `σ` read over that field,
and `σ` fixes `Q`.

Only `σ` having finite order is needed; neither `L / K` Galois nor either field being a number
field enters, since being an arithmetic Frobenius at `Q` is taken as a hypothesis rather than
derived.

**What this does not give.** That `Q` is then the only prime of `𝓞 L` above its contraction to
`L ^ ⟨σ⟩`, and that the contraction has residue degree one over `Q ∩ 𝓞 K`, are the consequences a
fixed-field fibre count needs; both are separate statements and neither is proved here.

## Main results

* `Ideal.stabilizer_fixedField_zpowers_eq_top`: the decomposition group of `Q` inside
  `Gal(L / L ^ ⟨σ⟩)` is everything.
-/

public section

open IntermediateField NumberField

open scoped NumberField Pointwise

namespace Ideal

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- **The decomposition group over the fixed field is everything.** If `σ` is an arithmetic
Frobenius at `Q`, then every element of `Gal(L / L ^ ⟨σ⟩)` fixes `Q`.

The field `L ^ ⟨σ⟩` is the largest one over which `Q` stays inert in this sense, and it is the
field a fixed-field fibre count contracts through. -/
theorem stabilizer_fixedField_zpowers_eq_top (Q : Ideal (𝓞 L)) [Q.IsPrime] {σ : L ≃ₐ[K] L}
    [Finite (Subgroup.zpowers σ)] (hσ : IsArithFrobAt (𝓞 K) σ Q) :
    MulAction.stabilizer (L ≃ₐ[↥(fixedField (Subgroup.zpowers σ))] L) Q = ⊤ := by
  have hsmul : (AlgEquiv.toFixedFieldAlgEquiv σ) • Q = σ • Q := by
    rw [Ideal.pointwise_smul_def, Ideal.pointwise_smul_def]
    refine congrArg (Ideal.map · Q) (RingHom.ext fun x ↦ Subtype.ext ?_)
    change (AlgEquiv.toFixedFieldAlgEquiv σ) • (x : L) = σ • (x : L)
    rw [AlgEquiv.smul_def, AlgEquiv.smul_def, AlgEquiv.toFixedFieldAlgEquiv_apply]
  have hmem : AlgEquiv.toFixedFieldAlgEquiv σ ∈
      MulAction.stabilizer (L ≃ₐ[↥(fixedField (Subgroup.zpowers σ))] L) Q := by
    rw [MulAction.mem_stabilizer_iff, hsmul]
    exact hσ.mem_stabilizer
  refine top_le_iff.1 ?_
  rw [← AlgEquiv.zpowers_toFixedFieldAlgEquiv_eq_top σ]
  exact Subgroup.zpowers_le.2 hmem

end Ideal
