/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RingTheory.Huber.LocalizationTopology.Completion

/-!
# The plus ring `A_U⁺` of a rational localisation

For a rational subset `U = R(T/s)` of `Spa(A, A⁺)`, roadmap Layer 3.1 asks for `A_U⁺`: the integral
closure in `A_U = A⟨T/s⟩` of the image of the subring generated by `A⁺` and the fractions `t/s`.
This file defines it, in the three layers the construction actually needs.

## The three layers, and why there are three

```text
locPlusSubring            A⁺[t₁/s, …, tₙ/s]                        ⊆ Aₛ
locPlusIntegralClosure    its integral closure                     ⊆ Aₛ
completedPlusSubringBase  topological closure of the image         ⊆ A⟨T/s⟩
completedPlusSubring      the integral closure of that             ⊆ A⟨T/s⟩
```

The first two layers are purely algebraic and are stated with no topology on `A` at all.

The last step takes the integral closure **in the completion**, and that is a deliberate choice
rather than a restatement: integral closedness of `A_U⁺` is then true by construction. Defining it
instead as the image of `A⁺[T/s]^int`, or as its topological closure, would leave integral
closedness owing the completion-transfer theorem identifying the two constructions — Huber's
Lemma 2.4.3, cited by Wedhorn at 8.16 and 7.47(4) — which is not available here.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.locPlusSubring`: `A⁺[T/s]` inside `Aₛ`.
* `TauCeti.Huber.PairOfDefinition.locPlusIntegralClosure`: its integral closure in `Aₛ`.
* `TauCeti.Huber.PairOfDefinition.completedPlusSubringBase`: the topological closure of the image
  of that in `A⟨T/s⟩`.
* `TauCeti.Huber.PairOfDefinition.completedPlusSubring`: **`A_U⁺`**.

## Main results

* `TauCeti.Huber.PairOfDefinition.algebraMap_mem_locPlusSubring` and
  `TauCeti.Huber.PairOfDefinition.divBy_mem_locPlusSubring`: the two families of generators lie in
  `A⁺[T/s]`, which is what the roadmap's description of it as "generated by `A⁺` and the
  fractions" amounts to.
* `TauCeti.Huber.PairOfDefinition.locPlusSubring_le_locPlusIntegralClosure`.

That `(A_U, A_U⁺)` is a Huber pair — that `A_U⁺` is open and power-bounded — is **not** proved
here. It is the substance of the next step: `A⁺` is contained in `A°` but is not bounded, so the
boundedness route used for the `A₀`-based `locSubring` does not transfer, and the argument is
Wedhorn's rather than a corollary of what is already on `main`.

## Provenance

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, branch `dev/adic-spaces` at `37bbdaeb9`)
carries this construction in `projects/AdicSpaces/Adic spaces/Presheaf.lean` as
`RationalLocData.locPlusSubring`, `completedPlusSubringBase` and `completedPlusSubring`. The
three-layer shape and the reason for taking the final integral closure in the completion are
theirs; the statements here are written against TauCeti's `PairOfDefinition` API and its
`locUniformSpace` topology rather than ported, and no proof was copied.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], §8.2, 8.16 and 7.47(4).
-/

public section

open Pointwise Topology TauCeti.Localization

namespace TauCeti.Huber

namespace PairOfDefinition

section Algebraic

variable {A : Type*} [CommRing A] (Aplus : Subring A) (T : Finset A) (s : A)
  (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]

/-- `A⁺[t₁/s, …, tₙ/s]`: the subring of `Aₛ` generated by the image of `A⁺` together with the
fractions `t/s` for `t ∈ T`. This is the `A⁺`-analogue of `locSubring`, which is generated the
same way from a ring of definition `A₀`. -/
noncomputable def locPlusSubring : Subring S :=
  Subring.closure
    ((algebraMap A S) '' (Aplus : Set A) ∪ Set.range (fun t : T ↦ divBy (t : A) s))

/-- The image of `A⁺` lies in `A⁺[T/s]`. -/
theorem algebraMap_mem_locPlusSubring {a : A} (ha : a ∈ Aplus) :
    algebraMap A S a ∈ locPlusSubring Aplus T s S :=
  Subring.subset_closure (Set.mem_union_left _ ⟨a, ha, rfl⟩)

/-- Each fraction `t/s` lies in `A⁺[T/s]`. -/
theorem divBy_mem_locPlusSubring {t : A} (ht : t ∈ T) :
    divBy t s ∈ locPlusSubring Aplus T s S :=
  Subring.subset_closure (Set.mem_union_right _ ⟨⟨t, ht⟩, rfl⟩)

/-- The integral closure of `A⁺[T/s]` inside `Aₛ`. -/
noncomputable def locPlusIntegralClosure : Subring S :=
  (integralClosure ↥(locPlusSubring Aplus T s S) S).toSubring

/-- A subring is contained in its integral closure. -/
theorem locPlusSubring_le_locPlusIntegralClosure :
    locPlusSubring Aplus T s S ≤ locPlusIntegralClosure Aplus T s S :=
  fun x hx ↦ (integralClosure ↥(locPlusSubring Aplus T s S) S).algebraMap_mem ⟨x, hx⟩

end Algebraic

section Topological

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- The base of `A_U⁺`: the topological closure in `A⟨T/s⟩` of the image of the integral closure
of `A⁺[T/s]`. -/
noncomputable def completedPlusSubringBase (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Subring (UniformSpace.Completion S) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  ((locPlusIntegralClosure Aplus T s S).map
    UniformSpace.Completion.coeRingHom).topologicalClosure

/-- **`A_U⁺`**: the integral closure, inside `A⟨T/s⟩`, of `completedPlusSubringBase`.

Taking the integral closure *in the completion* is what makes integral closedness hold by
construction; defining `A_U⁺` instead as the closure of the image of `A⁺[T/s]^int` would leave that
owing Huber's Lemma 2.4.3, which identifies the two. -/
noncomputable def completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Subring (UniformSpace.Completion S) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  -- the `Subring ↥R → Algebra ↥R B` route is not instance-automatic, so name it here
  letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  (integralClosure ↥(completedPlusSubringBase P Aplus T s S hden)
    (UniformSpace.Completion S)).toSubring

end Topological

end PairOfDefinition

end TauCeti.Huber
