/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Conductor
public import Mathlib.RingTheory.DedekindDomain.Different

-- Roadmap source: `TauCetiRoadmap/NumberFieldArithmetic/README.md` @ `2172af4ad0d3`. This is a
-- prerequisite rather than a milestone in its own right: Layer 6.3's different-exponent formula
-- and Layer 8.3's worked examples both need the different of a monogenic extension in closed
-- form (for instance `v_P(𝔡) = 2` at `2` in `ℚ(i)`, where the wild lower bound is attained).

/-!
# The different of a monogenic extension

When `B` is generated over `A` by a single element `x` — the monogenic case — the different
ideal is generated by `f'(x)`, where `f` is the minimal polynomial of `x`:

`differentIdeal A B = Ideal.span {aeval x (derivative (minpoly A x))}`.

This is the computational handle on the different. Without it the different is only accessible
through the trace dual, which is not something one evaluates at a specific field.

## The conductor is what makes this work

Mathlib supplies the general identity

`conductor A x * differentIdeal A B = Ideal.span {aeval x (derivative (minpoly A x))}`
(`conductor_mul_differentIdeal`),

which holds for any `x` generating `L` over `K`, monogenic or not. The order conductor measures
exactly the failure of `A[x]` to be all of `B`, so the monogenic hypothesis is precisely the
statement that it is the unit ideal (`conductor_eq_top_of_adjoin_eq_top`). This file records the
resulting closed form; it reproves neither half.

Note the two adjoin hypotheses are genuinely different: `Algebra.adjoin K {x} = ⊤` in `L` says
`x` generates the field extension, while `Algebra.adjoin A {x} = ⊤` in `B` says it generates the
ring of integers. The first alone gives the conductor identity; only the second collapses it.

## Main results

* `TauCeti.differentIdeal_eq_span_aeval_derivative_minpoly`: the closed form.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter III, §2.
* J-P. Serre, *Local Fields*, Chapter III, §6.
-/

public section

open Polynomial

namespace TauCeti

variable (A K L B : Type*) [CommRing A] [Field K] [Field L] [CommRing B]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L]
  [IsDomain A] [IsFractionRing A K] [IsIntegralClosure B A L]
  [IsIntegrallyClosed A] [IsDedekindDomain B] [Module.IsTorsionFree A B]
  [FiniteDimensional K L] [Algebra.IsSeparable K L]

/-- **The different of a monogenic extension is generated by `f'(x)`.** The hypothesis `hx` says
`x` generates the field extension, and `hx'` that it generates the ring; the second is what makes
the order conductor the unit ideal and collapses Mathlib's `conductor_mul_differentIdeal`. -/
theorem differentIdeal_eq_span_aeval_derivative_minpoly (x : B)
    (hx : Algebra.adjoin K {algebraMap B L x} = ⊤) (hx' : Algebra.adjoin A {x} = ⊤) :
    differentIdeal A B = Ideal.span {aeval x (derivative (minpoly A x))} := by
  rw [← conductor_mul_differentIdeal A K L x hx, conductor_eq_top_of_adjoin_eq_top hx',
    Ideal.top_mul]

end TauCeti

end
