/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.Homeomorph
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Basis
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Perturbation

/-!
# Rational subsets under a localization homeomorphism

Let `S` be a localization of `A` at a submonoid `M`. Every finite family of elements of `S` has a
common denominator in `M`. Multiplying all the numerators and the denominator of a rational subset
by that common denominator does not change the subset, because the multiplier is a unit. Thus
every rational subset of `Spa(S, S⁺)` is cut out by elements coming from `A`.

This is the algebraic denominator-clearing part of Wedhorn Proposition 8.2(2), that a rational
subset of a rational subset is rational in the original adic spectrum. Combined with the
homeomorphism

```text
Spa(A(T/s), A(T/s)⁺) ≃ R(T/s),
```

it says that any rational subset on the left is the inverse image of a basic rational locus in
`Spa(A, A⁺)`. Over Huber rings that locus is moreover presented *admissibly*: the cleared
numerator family may be padded with a finite subset of `A` spanning an open ideal without moving
the locus, so the presentation in `A` is one of a rational subset — that is, a member of the
rational family `spaRationalFamily`. To obtain Proposition 8.2(2) in full, one must still pass
from `A(T/s)` to the completed localization `A⟨T/s⟩`.

## Main results

* `TauCeti.ValuationSpectrum.exists_comap_preimage_basicOpenFinset_eq`: a rational open over a
  localization is the pullback of one presented by elements of the source ring, whose numerator
  ideal extends to the ideal generated by the original numerators and denominator.
* `TauCeti.ValuationSpectrum.exists_mem_spaRationalFamily_spaComap_preimage_eq_of_isLocalization`:
  every member of the rational family of `Spa(S, S⁺)` is the preimage under `spaComap` of a
  member of the rational family of `Spa(A, A⁺)`.
* `TauCeti.ValuationSpectrum.exists_mem_spaRationalFamily_spaLocalizationHomeomorph_preimage_eq`:
  the same statement through the localization homeomorphism.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], arXiv:1910.05934v1, Proposition 8.2(2).
* For simultaneous denominator clearing in a localization, see Mathlib's
  `IsLocalization.commonDenomOfFinset`, `IsLocalization.finsetIntegerMultiple`, and
  `IsLocalization.finsetIntegerMultiple_image`.
-/

public section

namespace TauCeti.ValuationSpectrum

open TauCeti.Huber TauCeti.Huber.PairOfDefinition TauCeti.Localization

variable {A S : Type*} [CommRing A] [CommRing S] [Algebra A S]

private lemma algebraMap_integerMultiple_aux (M : Submonoid A) [IsLocalization M S] (T : Finset S)
    (x : T) : algebraMap A S (IsLocalization.integerMultiple M T id x) =
      (x : S) * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  rw [IsLocalization.map_integerMultiple, Submonoid.smul_def, Algebra.smul_def]
  exact mul_comm _ _

private lemma image_finsetIntegerMultiple_aux (M : Submonoid A) [IsLocalization M S] [DecidableEq A]
    [DecidableEq S] (T : Finset S) :
    (IsLocalization.finsetIntegerMultiple M T).image (algebraMap A S) =
      T.image fun x ↦ x * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  apply Finset.coe_injective
  rw [Finset.coe_image, Finset.coe_image, IsLocalization.finsetIntegerMultiple_image,
    ← Set.image_smul]
  exact Set.image_congr' fun x ↦ by rw [Submonoid.smul_def, Algebra.smul_def, mul_comm]

open scoped Pointwise in
private lemma map_span_finsetIntegerMultiple_aux (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] (T : Finset S) :
    Ideal.map (algebraMap A S) (Ideal.span (IsLocalization.finsetIntegerMultiple M T : Set A)) =
      Ideal.span (T : Set S) := by
  -- the cleared generators are the old ones scaled by the common denominator, a unit in `S`
  rw [Ideal.map_span, IsLocalization.finsetIntegerMultiple_image, Submonoid.smul_def,
    ← IsScalarTower.algebraMap_smul S]
  exact Submodule.span_smul_eq_of_isUnit _ _ (IsLocalization.map_units S _)

/-- **Clear denominators in a rational open of a localization.** If `S` is a localization of `A`
at a submonoid `M`, then every rational open `Spv(S)(U/q)` is the pullback of one presented by a
finite family in `A`, and that family generates in `S` the ideal generated by `U` together with
`q`.

No topological admissibility is asserted for the numerator family in `A`, and none is available
here: padding a numerator family to span an open ideal fixes the locus only inside the adic
spectrum, whereas this one lives in the whole valuation spectrum. It is the ideal identity that
carries admissibility over to the cleared presentation, in
`TauCeti.ValuationSpectrum.exists_mem_spaRationalFamily_spaComap_preimage_eq_of_isLocalization`. -/
theorem exists_comap_preimage_basicOpenFinset_eq (M : Submonoid A) [IsLocalization M S]
    (U : Finset S) (q : S) :
    ∃ (V : Finset A) (r : A),
      Ideal.map (algebraMap A S) (Ideal.span (V : Set A)) = Ideal.span (insert q (U : Set S)) ∧
        comap (algebraMap A S) ⁻¹' basicOpenFinset V r = basicOpenFinset U q := by
  classical
  refine ⟨IsLocalization.finsetIntegerMultiple M (insert q U),
    IsLocalization.integerMultiple M (insert q U) id ⟨q, Finset.mem_insert_self q U⟩, ?_, ?_⟩
  · rw [map_span_finsetIntegerMultiple_aux, Finset.coe_insert]
  · rw [comap_preimage_basicOpenFinset, image_finsetIntegerMultiple_aux,
      algebraMap_integerMultiple_aux,
      basicOpenFinset_image_mul_right _ _ _ (IsLocalization.map_units S _),
      basicOpenFinset_insert_self]

/-- **Clear denominators in a rational subset of a localization.** If `S` is a localization of
`A` at a submonoid `M`, both Huber rings, then every member of the rational family of
`Spa(S, S⁺)` is the preimage under `spaComap (algebraMap A S)` of a member of the rational family
of `Spa(A, A⁺)`; that is, `R(T/s) = R(V/r)` pulled back, with `V · A` open.

Denominator clearing produces a presentation in `A` of the underlying rational open, but says
nothing about its numerator ideal. Openness is recovered afterwards: the numerators are padded
by a finite subset of `A` spanning an open ideal, which moves neither locus. -/
theorem exists_mem_spaRationalFamily_spaComap_preimage_eq_of_isLocalization [TopologicalSpace A]
    [IsTopologicalRing A] [IsHuberRing A] [TopologicalSpace S] [IsTopologicalRing S]
    [IsHuberRing S] (M : Submonoid A) [IsLocalization M S] (Aplus : Subring A) (Bplus : Subring S)
    (hcont : Continuous (algebraMap A S)) (hplus : ∀ a ∈ Aplus, algebraMap A S a ∈ Bplus)
    {U : Set (spa Bplus)} (hU : U ∈ spaRationalFamily Bplus) :
    ∃ W ∈ spaRationalFamily Aplus,
      spaComap (algebraMap A S) hcont Aplus Bplus hplus ⁻¹' W = U := by
  classical
  obtain ⟨T, s, hT, rfl⟩ := mem_spaRationalFamily_iff.mp hU
  obtain ⟨V, r, hspan, hVr⟩ := exists_comap_preimage_basicOpenFinset_eq M T s
  rw [comap_preimage_basicOpenFinset] at hVr
  -- the cleared presentation has the same numerator ideal in `S` as `(insert s T, s)`, whose
  -- span is open because it contains the open span of `T`; so a finite `D ⊆ A` spanning an open
  -- ideal of `A` may be adjoined to the cleared numerators without moving the locus
  have hVopen : IsOpen (Ideal.span (V.image (algebraMap A S) : Set S) : Set S) := by
    rw [Finset.coe_image, ← Ideal.map_span, hspan]
    exact Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (Set.subset_insert s _)) hT
  obtain ⟨D, hD, hDeq⟩ := exists_isOpen_span_rationalSubset_union_image_eq hcont Bplus
    (V.image (algebraMap A S)) hVopen (algebraMap A S r)
  refine ⟨Subtype.val ⁻¹' rationalSubset Aplus (V ∪ D) r, mem_spaRationalFamily_iff.mpr
    ⟨V ∪ D, r, Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (by simp)) hD, rfl⟩, ?_⟩
  rw [spaComap_preimage_rationalSubset, Finset.image_union, hDeq, rationalSubset_def,
    rationalSubset_def, hVr]

private lemma algebraMap_mem_integralClosure_adjoin_divBy_aux (Aplus : Subring A) (T : Finset A)
    (s : A) [IsLocalization.Away s S] (a : A) (ha : a ∈ Aplus) :
    algebraMap A S a ∈ (integralClosure ↥(Algebra.adjoin Aplus (Set.range fun t : T ↦
      (divBy (t : A) s : S))) S).toSubring :=
  Subalgebra.algebraMap_mem _ (⟨_, Subalgebra.algebraMap_mem _ (⟨a, ha⟩ : Aplus)⟩ :
    ↥(Algebra.adjoin Aplus _))

/-- The homeomorphism of `spaLocalizationHomeomorph`, followed by the inclusion of `R(T/s)` into
`Spa(A, A⁺)`, is pullback along `A → A(T/s)`. -/
private lemma val_comp_spaLocalizationHomeomorph_aux [TopologicalSpace A] [IsTopologicalRing A]
    (P : PairOfDefinition A) (Aplus : Subring A) (hP : P.ringOfDefinition ≤ Aplus) (T : Finset A)
    (s : A) [IsLocalization.Away s S] (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    Subtype.val ∘ ⇑(spaLocalizationHomeomorph P Aplus hP T s S hden) =
      spaComap (algebraMap A S) (continuous_algebraMap_locTopology P T s S hden) Aplus _
        (algebraMap_mem_integralClosure_adjoin_divBy_aux Aplus T s) := by
  let _ := locTopology P T s S hden
  funext v
  apply Subtype.ext
  rw [spaComap_val]
  exact spaLocalizationHomeomorph_apply_val P Aplus hP T s S hden v

/-- **Rational subsets through the topological-localization homeomorphism.** Every member of the
rational family of `Spa(A(T/s), A(T/s)⁺)` is the inverse image, under the canonical homeomorphism
with `R(T/s)`, of the trace on `R(T/s)` of a member of the rational family of `Spa(A, A⁺)`.

This is the denominator-clearing part of Wedhorn Proposition 8.2(2). -/
theorem exists_mem_spaRationalFamily_spaLocalizationHomeomorph_preimage_eq [TopologicalSpace A]
    [IsTopologicalRing A] (P : PairOfDefinition A) (Aplus : Subring A)
    (hP : P.ringOfDefinition ≤ Aplus) (T : Finset A) (s : A) [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    ∀ U ∈ spaRationalFamily (integralClosure ↥(Algebra.adjoin Aplus
        (Set.range fun t : T ↦ (divBy (t : A) s : S))) S).toSubring,
      ∃ W ∈ spaRationalFamily Aplus,
        spaLocalizationHomeomorph P Aplus hP T s S hden ⁻¹' (Subtype.val ⁻¹' W) = U := by
  let _ := locTopology P T s S hden
  have _ := isTopologicalRing_locTopology P T s S hden
  have _ : IsHuberRing A := ⟨⟨P⟩⟩
  have _ := isHuberRing_locTopology P T s S hden
  intro U hU
  obtain ⟨W, hW, hWU⟩ := exists_mem_spaRationalFamily_spaComap_preimage_eq_of_isLocalization
    (Submonoid.powers s) Aplus _ (continuous_algebraMap_locTopology P T s S hden)
    (algebraMap_mem_integralClosure_adjoin_divBy_aux Aplus T s) hU
  refine ⟨W, hW, ?_⟩
  rw [← Set.preimage_comp, val_comp_spaLocalizationHomeomorph_aux]
  exact hWU

end TauCeti.ValuationSpectrum

end
