/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Membership in a subgroup of a cyclic group, by index

In a group generated by `g`, a power `g ^ n` lies in a subgroup `K` exactly when the index of `K`
divides `n`: the exponents landing in `K` are the multiples of `K.index`. When `K` has finite
index that makes `K.index` the least positive such exponent; when it does not, no positive exponent
lands in `K` at all, and both readings agree through the convention `index = 0`.

## Main results

* `Subgroup.zpow_mem_iff_index_dvd`: `g ^ n ∈ K ↔ (K.index : ℤ) ∣ n` for `n : ℤ`, with `g` a
  generator.
* `Subgroup.pow_mem_iff_index_dvd`: the same for a natural exponent.
-/

public section

namespace Subgroup

variable {G : Type*} [Group G] {g : G}

-- Source. Written for the Chebotarev roadmap's Layer 8.2, `TauCetiRoadmap/Chebotarev/README.md`
-- §8.2, which asks for the residue degree of an intermediate prime as the least positive power of
-- the absolute Frobenius landing in `⟨σ⟩`. This is that statement with the number theory removed:
-- inside an unramified decomposition group, which is cyclic and generated by the Frobenius, the
-- condition is membership of a power of a generator in a subgroup.

/-- **Membership in a subgroup of a cyclic group is divisibility of the index.** If `g` generates
`G`, then `g ^ n` lies in `K` exactly when `K.index` divides `n`.

This is the criterion a fibre-selection argument wants: it turns a membership test on powers of a
generator into arithmetic in `ℤ`, and identifies `K.index` as the least positive exponent landing
in `K`.

No finiteness is assumed. If `K` has infinite index its index is `0` by convention, and the
statement reads `g ^ n ∈ K ↔ n = 0`. -/
@[to_additive (attr := simp)
/-- **Membership in a subgroup of an additive cyclic group is divisibility of the index.** If `g`
generates `G`, then `n • g` lies in `K` exactly when `K.index` divides `n`. -/]
theorem zpow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℤ) :
    g ^ n ∈ K ↔ (K.index : ℤ) ∣ n := by
  have : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr ⟨g, hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  have hgen : zpowers (QuotientGroup.mk' K g) = ⊤ := by
    rw [← MonoidHom.map_zpowers, hg, ← MonoidHom.range_eq_map]
    exact MonoidHom.range_eq_top.mpr (QuotientGroup.mk'_surjective K)
  have horder : orderOf (QuotientGroup.mk' K g) = K.index :=
    (orderOf_eq_card_of_zpowers_eq_top hgen).trans K.index_eq_card.symm
  rw [← horder, orderOf_dvd_iff_zpow_eq_one, ← map_zpow, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]

/-- **The natural-exponent form.** `g ^ n ∈ K ↔ K.index ∣ n`, the case `n : ℕ` of
`zpow_mem_iff_index_dvd`. -/
@[to_additive (attr := simp)
/-- **The natural-exponent form.** `n • g ∈ K ↔ K.index ∣ n`. -/]
theorem pow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℕ) :
    g ^ n ∈ K ↔ K.index ∣ n := by
  rw [← zpow_natCast, zpow_mem_iff_index_dvd K hg, Int.natCast_dvd_natCast]

end Subgroup
