/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Membership in a subgroup of a cyclic group, by index

In a group generated by `g`, a power `g ^ n` lies in a subgroup `K` exactly when the index of `K`
divides `n`: the exponents landing in `K` are the multiples of `K.index`. When `K` has finite
index that makes `K.index` the least positive such exponent; when it does not, no positive exponent
lands in `K` at all, and both readings agree through the convention `index = 0`.

## Main results

* `Subgroup.pow_mem_iff_index_dvd`: `g ^ n ∈ K ↔ K.index ∣ n`, for `g` a generator.
* `Subgroup.index_le_of_pow_mem`: the minimality half on its own, for a positive exponent.
-/

@[expose] public section

namespace Subgroup

variable {G : Type*} [Group G] {g : G}

/-- **Membership in a subgroup of a cyclic group is divisibility of the index.** If `g` generates
`G`, then `g ^ n` lies in `K` exactly when `K.index` divides `n`.

Both directions come from the quotient: a group generated by one element is commutative, so every
subgroup is normal and `G ⧸ K` is a group, cyclic of order `K.index` and generated by the image of
`g`. The statement is then that the order of a generator is the cardinality.

No finiteness is assumed. If `K` has infinite index its index is `0` by convention, and the
statement reads `g ^ n ∈ K ↔ n = 0`, which is correct: the image of `g` then has infinite order in
`G ⧸ K`. -/
theorem pow_mem_iff_index_dvd (hg : zpowers g = ⊤) (K : Subgroup G) (n : ℕ) :
    g ^ n ∈ K ↔ K.index ∣ n := by
  have hcyc : IsCyclic G := ⟨g, fun x ↦ by rw [← mem_zpowers_iff, hg]; trivial⟩
  let _ : CommGroup G := hcyc.commGroup
  have hgen : zpowers (QuotientGroup.mk' K g) = ⊤ := by
    rw [← MonoidHom.map_zpowers, hg, ← MonoidHom.range_eq_map]
    exact MonoidHom.range_eq_top.mpr (QuotientGroup.mk'_surjective K)
  have horder : orderOf (QuotientGroup.mk' K g) = K.index := by
    rw [← Nat.card_zpowers, hgen, card_top, index_eq_card]
  rw [← horder, orderOf_dvd_iff_pow_eq_one, ← map_pow, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]

/-- **The index is the least positive exponent landing in `K`.** Together with
`pow_mem_iff_index_dvd` — which gives `g ^ K.index ∈ K` — this says `K.index` is the minimum of
`{n | 0 < n ∧ g ^ n ∈ K}` whenever that set is nonempty. -/
theorem index_le_of_pow_mem (hg : zpowers g = ⊤) (K : Subgroup G) {n : ℕ} (hn : 0 < n)
    (h : g ^ n ∈ K) : K.index ≤ n :=
  Nat.le_of_dvd hn ((pow_mem_iff_index_dvd hg K n).mp h)

end Subgroup
