/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Membership in a subgroup of a cyclic group, by index

In a group generated by `g`, a power `g ^ n` lies in a subgroup `K` exactly when the index of `K`
divides `n`: the exponents landing in `K` are the multiples of `K.index`. When `K` has finite
index that makes `K.index` the least positive such exponent; when it does not, no positive exponent
lands in `K` at all, and both readings agree through the convention `index = 0`.

## Main results

* `Subgroup.pow_mem_iff_index_dvd`: `g ^ n ∈ K ↔ K.index ∣ n`, for `g` a generator.
-/

@[expose] public section

namespace Subgroup

variable {G : Type*} [Group G] {g : G}

/-- **Membership in a subgroup of a cyclic group is divisibility of the index.** If `g` generates
`G`, then `g ^ n` lies in `K` exactly when `K.index` divides `n`.

This is the criterion a fibre-selection argument wants: it turns a membership test on powers of a
generator into arithmetic in `ℕ`, and identifies `K.index` as the least positive exponent landing
in `K`.

No finiteness is assumed. If `K` has infinite index its index is `0` by convention, and the
statement reads `g ^ n ∈ K ↔ n = 0`. -/
@[simp]
theorem pow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℕ) :
    g ^ n ∈ K ↔ K.index ∣ n := by
  have hcyc : IsCyclic G := ⟨g, fun x ↦ by rw [← mem_zpowers_iff, hg]; trivial⟩
  let _ : CommGroup G := hcyc.commGroup
  have hgen : zpowers (QuotientGroup.mk' K g) = ⊤ := by
    rw [← MonoidHom.map_zpowers, hg, ← MonoidHom.range_eq_map]
    exact MonoidHom.range_eq_top.mpr (QuotientGroup.mk'_surjective K)
  have horder : orderOf (QuotientGroup.mk' K g) = K.index := by
    rw [← Nat.card_zpowers, hgen, card_top, index_eq_card]
  rw [← horder, orderOf_dvd_iff_pow_eq_one, ← map_pow, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]

end Subgroup
