/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Monogenic
public import TauCeti.RingTheory.DedekindDomain.Different.Monogenic

-- Roadmap source: `TauCetiRoadmap/NumberFieldArithmetic/README.md` @ `2172af4ad0d3`. Prerequisite
-- for Layer 6.3 and the Layer 8.3 worked examples, specialised to number fields so that
-- `IsMonogenic` (Layer 7.3) can be used as the hypothesis directly.

/-!
# The different of a monogenic number field

Specialising `TauCeti.differentIdeal_eq_span_aeval_derivative_minpoly` to `ℤ ⊆ 𝓞 K`: when
`𝓞 K = ℤ[θ]`, the different of `K` is generated by `f'(θ)`, with `f` the minimal polynomial of
`θ` over `ℤ`.

The point of the specialisation is that the hypothesis becomes the single condition
`Algebra.adjoin ℤ {θ} = ⊤` — the defining condition of `TauCeti.NumberField.IsMonogenic`. The
field-generation hypothesis of the general statement is not a second assumption here: it follows,
by `TauCeti.NumberField.adjoin_rat_eq_top_of_adjoin_int_eq_top`.

So for a monogenic number field the different is computable from a minimal polynomial alone,
which is what the worked examples need — for instance `v_P(𝔡) = 2` at `2` in `ℚ(i)`, where
`𝓞 = ℤ[i]`, `f = X² + 1` and `f'(i) = 2i` generates `P²`.

## Main results

* `TauCeti.NumberField.differentIdeal_eq_span_aeval_derivative_minpoly`: the different of
  `𝓞 K` over `ℤ`, for an integral generator.
* `TauCeti.NumberField.exists_differentIdeal_eq_span_of_isMonogenic`: consequently a monogenic
  number field has such a generator.
-/

public section

open Polynomial

open scoped NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

/-- **The different of `ℤ[θ] = 𝓞 K` is generated by `f'(θ)`.** Only the integral generation
hypothesis is needed: the field generation it also requires follows from it. -/
theorem differentIdeal_eq_span_aeval_derivative_minpoly (θ : 𝓞 K)
    (hθ : Algebra.adjoin ℤ {θ} = ⊤) :
    differentIdeal ℤ (𝓞 K) = Ideal.span {aeval θ (derivative (minpoly ℤ θ))} :=
  TauCeti.differentIdeal_eq_span_aeval_derivative_minpoly ℤ ℚ K (𝓞 K) θ
    (adjoin_rat_eq_top_of_adjoin_int_eq_top hθ) hθ

/-- **A monogenic number field has a different generated by `f'(θ)`.** -/
theorem exists_differentIdeal_eq_span_of_isMonogenic (h : IsMonogenic K) :
    ∃ θ : 𝓞 K, differentIdeal ℤ (𝓞 K) = Ideal.span {aeval θ (derivative (minpoly ℤ θ))} := by
  obtain ⟨θ, hθ⟩ := isMonogenic_def.1 h
  exact ⟨θ, differentIdeal_eq_span_aeval_derivative_minpoly θ hθ⟩

end TauCeti.NumberField

end
