/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.DedekindDomain.AdicValuation
public import Mathlib.RingTheory.DedekindDomain.Factorization
public import TauCeti.RingTheory.ClassGroup.Basic

/-!
# The group of fractional ideals is free abelian on the primes

Let `R` be a Dedekind domain with fraction field `K`. The nonzero fractional ideals of `R` form a
group `(FractionalIdeal R⁰ K)ˣ`, every nonzero fractional ideal being invertible, and unique
factorization says that group is free abelian on the height one primes. Mathlib has the valuation
bookkeeping — `IsDedekindDomain.HeightOneSpectrum.count` and the factorization lemmas in
`Mathlib/RingTheory/DedekindDomain/Factorization.lean` — but does not package the isomorphism
itself.

## Main definitions and results

* `FractionalIdeal.count_injective`: a nonzero fractional ideal is determined by its valuations,
  read off Mathlib's `finprod_heightOneSpectrum_factorization'`.
* `FractionalIdeal.factorization`: the isomorphism
  `(FractionalIdeal R⁰ K)ˣ ≃* Multiplicative (HeightOneSpectrum R →₀ ℤ)`, sending a fractional
  ideal to its tuple of valuations.
* `IsDedekindDomain.HeightOneSpectrum.classGroupMk`: the class of a height one prime, together
  with `FractionalIdeal.mk_mem_closure_of_count_eq_zero` and
  `FractionalIdeal.mk0_mem_closure_of_count_eq`, which put a class in the subgroup generated by
  the `[v]` for `v` in a set of primes.
* `FractionalIdeal.valuation_eq_exp_neg_count`: `count` of a principal fractional ideal recovers
  the `v`-adic valuation.

The kernel of the principal-ideal map, which the closure lemmas use, is in
`TauCeti/RingTheory/ClassGroup/Basic.lean`.

This is the count/factorization machinery that the `S`-integer class group computation
`Cl(𝒪_S) ≃* Cl(R) ⧸ ⟨[v] : v ∈ S⟩` rests on, which in turn is what
`TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak Mordell–Weil.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/FractionalIdeal.lean`
at the roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll), the source the roadmap's
§Provenance names for the Layer 6 Mordell–Weil lane. Following this repository's convention for
adapted material, the upstream authorship is credited here rather than in the copyright header.
Ported with the source's blanket `import Mathlib` narrowed to the modules actually used and its
`@[expose]` dropped.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

variable {R : Type*} [CommRing R] {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

namespace FractionalIdeal

variable [IsDedekindDomain R]

/-- The prime `v` as a unit of the group of fractional ideals. -/
noncomputable def unitOfPrime (v : HeightOneSpectrum R) : (FractionalIdeal R⁰ K)ˣ :=
  FractionalIdeal.mk0 K ⟨v.asIdeal, mem_nonZeroDivisors_of_ne_zero v.ne_bot⟩

@[simp] lemma coe_unitOfPrime (v : HeightOneSpectrum R) :
    ((unitOfPrime v : (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) = v.asIdeal := by
  simp only [unitOfPrime, FractionalIdeal.coe_mk0]

/-- The finitely-supported tuple of valuations of a unit fractional ideal. -/
noncomputable def toFinsupp (I : (FractionalIdeal R⁰ K)ˣ) : HeightOneSpectrum R →₀ ℤ :=
  Finsupp.ofSupportFinite (fun v ↦ count K v (I : FractionalIdeal R⁰ K)) (by
    have := finite_factors (I : FractionalIdeal R⁰ K)
    simpa [Function.support, Filter.eventually_cofinite] using this)

@[simp] lemma toFinsupp_apply (I : (FractionalIdeal R⁰ K)ˣ) (v : HeightOneSpectrum R) :
    toFinsupp I v = count K v (I : FractionalIdeal R⁰ K) := by
  simp only [toFinsupp, Finsupp.ofSupportFinite_coe]

/-- The unit fractional ideal `∏ v ^ g v`. -/
noncomputable def ofFinsupp (g : HeightOneSpectrum R →₀ ℤ) : (FractionalIdeal R⁰ K)ˣ :=
  g.prod (fun v e ↦ unitOfPrime v ^ e)

lemma coe_ofFinsupp (g : HeightOneSpectrum R →₀ ℤ) :
    ((ofFinsupp g : (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K)
      = g.prod (fun v e ↦ (v.asIdeal : FractionalIdeal R⁰ K) ^ e) := by
  rw [ofFinsupp, ← Units.coeHom_apply, map_finsuppProd]
  simp only [Units.coeHom_apply, map_zpow, coe_unitOfPrime]

lemma count_ofFinsupp (g : HeightOneSpectrum R →₀ ℤ) (v : HeightOneSpectrum R) :
    count K v ((ofFinsupp g : (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) = g v := by
  rw [coe_ofFinsupp, count_finsuppProd]

/-- A unit fractional ideal is determined by its valuations. -/
lemma count_injective {I J : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v, count K v (I : FractionalIdeal R⁰ K) = count K v (J : FractionalIdeal R⁰ K)) :
    I = J := by
  apply Units.ext
  rw [← finprod_heightOneSpectrum_factorization' K (Units.ne_zero I),
    ← finprod_heightOneSpectrum_factorization' K (Units.ne_zero J)]
  exact finprod_congr fun v ↦ by rw [h v]

/-- **The group of nonzero fractional ideals of a Dedekind domain is free abelian on the height
one primes.** -/
noncomputable def factorization :
    (FractionalIdeal R⁰ K)ˣ ≃* Multiplicative (HeightOneSpectrum R →₀ ℤ) where
  toFun I := Multiplicative.ofAdd (toFinsupp I)
  invFun g := ofFinsupp (Multiplicative.toAdd g)
  left_inv I := count_injective fun v ↦ by rw [count_ofFinsupp, toAdd_ofAdd, toFinsupp_apply]
  right_inv g := by
    apply Multiplicative.toAdd.injective
    ext
    simp only [toAdd_ofAdd, toFinsupp_apply, count_ofFinsupp]
  map_mul' I J := by
    apply Multiplicative.toAdd.injective
    ext v
    simp only [toAdd_ofAdd, Finsupp.coe_add, Pi.add_apply, toFinsupp_apply, Units.val_mul,
      toAdd_mul]
    exact count_mul K v (Units.ne_zero I) (Units.ne_zero J)

@[simp] lemma factorization_apply (I : (FractionalIdeal R⁰ K)ˣ) (v : HeightOneSpectrum R) :
    Multiplicative.toAdd (factorization I) v = count K v (I : FractionalIdeal R⁰ K) := by
  change Multiplicative.toAdd (Multiplicative.ofAdd (toFinsupp I)) v = _
  rw [toAdd_ofAdd, toFinsupp_apply]

/-- Under `factorization`, a prime corresponds to a basis vector of the free abelian group. -/
@[simp]
lemma factorization_unitOfPrime (v : HeightOneSpectrum R) :
    factorization (unitOfPrime v : (FractionalIdeal R⁰ K)ˣ) =
      Multiplicative.ofAdd (Finsupp.single v 1) := by
  classical
  apply Multiplicative.toAdd.injective
  ext w
  rw [toAdd_ofAdd, factorization_apply, coe_unitOfPrime, Finsupp.single_apply,
    count_maximal K w v]

/-- The class of a height one prime in the class group. -/
noncomputable def _root_.IsDedekindDomain.HeightOneSpectrum.classGroupMk
    (v : HeightOneSpectrum R) : ClassGroup R :=
  ClassGroup.mk0 ⟨v.asIdeal, mem_nonZeroDivisors_of_ne_zero v.ne_bot⟩

lemma _root_.IsDedekindDomain.HeightOneSpectrum.classGroupMk_eq_mk_unitOfPrime (K : Type*)
    [Field K] [Algebra R K] [IsFractionRing R K] (v : HeightOneSpectrum R) :
    v.classGroupMk = ClassGroup.mk K (unitOfPrime v) := by
  simp only [HeightOneSpectrum.classGroupMk, unitOfPrime, ClassGroup.mk_mk0]

/-- If a unit fractional ideal has trivial valuation outside a set `T` of primes, its class lies
in the subgroup generated by the classes of the primes in `T`. -/
lemma mk_mem_closure_of_count_eq_zero {T : Set (HeightOneSpectrum R)}
    {I : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v ∉ T, count K v (I : FractionalIdeal R⁰ K) = 0) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hI : I = ofFinsupp (toFinsupp I) := (factorization.left_inv I).symm
  rw [hI, ofFinsupp, map_finsuppProd]
  refine Subgroup.prod_mem _ fun v hv ↦ ?_
  have hvT : v ∈ T := by
    by_contra hvn
    exact Finsupp.mem_support_iff.mp hv (by rw [toFinsupp_apply, h v hvn])
  change ClassGroup.mk K (unitOfPrime v ^ toFinsupp I v) ∈
    Subgroup.closure (HeightOneSpectrum.classGroupMk '' T)
  rw [map_zpow, ← v.classGroupMk_eq_mk_unitOfPrime K]
  exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_image_of_mem _ hvT)) _

/-- If the valuations of an ideal `J` agree with those of `x : Kˣ` outside a set `T` of primes,
then the class of `J` lies in the subgroup generated by the classes of the primes in `T`. -/
lemma mk0_mem_closure_of_count_eq {T : Set (HeightOneSpectrum R)} {J : (Ideal R)⁰} {x : Kˣ}
    (h : ∀ v ∉ T, count K v ((J : Ideal R) : FractionalIdeal R⁰ K) =
      count K v (spanSingleton R⁰ (x : K))) :
    ClassGroup.mk0 J ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hmk : ClassGroup.mk0 J =
      ClassGroup.mk K (FractionalIdeal.mk0 K J * (toPrincipalIdeal R K x)⁻¹) := by
    rw [map_mul, map_inv, ClassGroup.mk_toPrincipalIdeal, inv_one, mul_one, ClassGroup.mk_mk0]
  rw [hmk]
  refine mk_mem_closure_of_count_eq_zero fun v hv ↦ ?_
  rw [Units.val_mul, count_mul K v (Units.ne_zero _) (Units.ne_zero _),
    Units.val_inv_eq_inv_val, count_inv, FractionalIdeal.coe_mk0, coe_toPrincipalIdeal, h v hv]
  exact add_neg_cancel _

/-- The `v`-adic valuation of `x : K` is `exp (- count v (x))`: the `count` of the principal
fractional ideal generated by `x` recovers the adic valuation. -/
theorem valuation_eq_exp_neg_count (v : HeightOneSpectrum R) {x : K} (hx : x ≠ 0) :
    v.valuation K x = WithZero.exp (- count K v (spanSingleton R⁰ x)) := by
  have key (r : R) (hr : r ≠ 0) : v.valuation K (algebraMap R K r) =
      WithZero.exp (- count K v (spanSingleton R⁰ (algebraMap R K r))) := by
    rw [valuation_of_algebraMap, intValuation_apply, v.intValuationDef_if_neg hr,
      ← coeIdeal_span_singleton, count_coe K v (by simpa using hr)]
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := R) x
  have hb0 : (b : R) ≠ 0 := nonZeroDivisors.ne_zero hb
  have ha0 : a ≠ 0 := by rintro rfl; simp at hx
  have hsa : spanSingleton R⁰ (algebraMap R K a) ≠ 0 := by
    rwa [spanSingleton_ne_zero_iff, ne_eq, _root_.map_eq_zero_iff _ (IsFractionRing.injective R K)]
  have hsb : spanSingleton R⁰ (algebraMap R K (b : R)) ≠ 0 := by
    rwa [spanSingleton_ne_zero_iff, ne_eq, _root_.map_eq_zero_iff _ (IsFractionRing.injective R K)]
  have hcount : count K v (spanSingleton R⁰ (algebraMap R K a / algebraMap R K (b : R))) =
      count K v (spanSingleton R⁰ (algebraMap R K a)) -
        count K v (spanSingleton R⁰ (algebraMap R K (b : R))) := by
    rw [← spanSingleton_div_spanSingleton, div_eq_mul_inv, count_mul K v hsa (inv_ne_zero hsb),
      count_inv, sub_eq_add_neg]
  rw [map_div₀, key a ha0, key (b : R) hb0, hcount, div_eq_mul_inv, ← WithZero.exp_neg,
    ← WithZero.exp_add]
  congr 1
  ring

end FractionalIdeal

end
