/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.Witt.FundamentalIdeal
public import TauCeti.RingTheory.Ideal.AdditiveGenerators

/-!
# Pfister classes and powers of the fundamental ideal

For units `a₁, …, aₙ`, the `n`-fold Pfister form is the tensor product

`<<a₁, …, aₙ>> = <<a₁>> ⋯ <<aₙ>>`,

where `<<a>> = <1, -a>`. This file defines its isometry class and Witt class and proves that, for
every positive `n`, the additive group underlying `I(K)^n` is generated by the `n`-fold Pfister
classes. The explicit two- and three-fold corollaries are the forms used to define and control the
Clifford invariant.

The positivity condition is necessary: `I(K)^0 = W(K)`, while the sole zero-fold Pfister class is
`<1>`, and a Witt ring need not be additively cyclic.

## Main definitions

* `TauCeti.pfisterForm`: the isometry class of an iterated Pfister tensor product.
* `TauCeti.pfisterClass`: its Witt class.

## Main results

* `TauCeti.fundamentalIdeal_pow_eq_addClosure`: positive powers of the fundamental ideal are
  additively generated by Pfister classes.
* `TauCeti.fundamentalIdeal_sq_eq_addClosure` and
  `TauCeti.fundamentalIdeal_cube_eq_addClosure`: the cases needed for the Clifford invariant.

## References

* T. Y. Lam, *Introduction to Quadratic Forms over Fields* (2005), Chapter II, §1 and
  Chapter X, with the convention `<<a>> = <1, -a>`.
-/

public section

open scoped BigOperators Pointwise

namespace TauCeti

universe u

variable {K : Type u} [Field K] [Invertible (2 : K)]

/-- The isometry class of the `n`-fold Pfister form, using the convention
`<<a>> = <1, -a>`. Orthogonal sum is addition and tensor product is multiplication on
`RegularFormClass`; the empty product is therefore the zero-fold form `<1>`. -/
noncomputable def pfisterForm {n : ℕ} (a : Fin n → Kˣ) : RegularFormClass K :=
  ∏ i, (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -(a i)⟩)

/-- The Witt class of an `n`-fold Pfister form. -/
noncomputable def pfisterClass {n : ℕ} (a : Fin n → Kˣ) : WittRing K :=
  wittClass (pfisterForm a)

/-- The Witt class of a Pfister form is the product of its one-fold factors. -/
theorem pfisterClass_eq_prod {n : ℕ} (a : Fin n → Kˣ) :
    pfisterClass a = ∏ i, oneFoldPfisterClass (a i) := by
  rw [pfisterClass, pfisterForm, map_prod]
  apply Finset.prod_congr rfl
  intro i _
  rw [map_add, map_one, oneFoldPfisterClass_eq]

/-- Splitting off the first slot splits a Pfister form as a tensor product. -/
theorem pfisterForm_cons {n : ℕ} (a : Kˣ) (b : Fin n → Kˣ) :
    pfisterForm (Fin.cons a b) =
      (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩) * pfisterForm b := by
  rw [pfisterForm, Fin.prod_univ_succ]
  rfl

/-- The zero-fold Pfister form is the rank-one unit form. -/
@[simp]
theorem pfisterForm_zero (a : Fin 0 → Kˣ) : pfisterForm a = 1 := by
  simp [pfisterForm]

/-- A one-fold Pfister form is `<1, -a>`. -/
theorem pfisterForm_one (a : Kˣ) :
    pfisterForm ![a] = 1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩ := by
  simp [pfisterForm]

/-- A two-fold Pfister form is the tensor product `<1, -a> ⊗ <1, -b>`. -/
theorem pfisterForm_two (a b : Kˣ) :
    pfisterForm ![a, b] =
      (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩) *
        (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -b⟩) := by
  simp [pfisterForm, Fin.prod_univ_succ]

/-- An `n`-fold Pfister form has rank `2 ^ n`. -/
@[simp]
theorem RegularFormClass.rank_pfisterForm {n : ℕ} (a : Fin n → Kˣ) :
    RegularFormClass.rank (pfisterForm a) = 2 ^ n := by
  rw [pfisterForm, ← RegularFormClass.rankHom_apply, map_prod]
  simp [RegularFormClass.rankHom_apply, RegularFormClass.rank_mk]

/-- The zero-fold Pfister class is the unit of the Witt ring. -/
@[simp]
theorem pfisterClass_zero (a : Fin 0 → Kˣ) : pfisterClass a = 1 := by
  simp [pfisterClass, pfisterForm]

/-- Splitting off the first slot splits a Pfister class as a product. -/
theorem pfisterClass_cons {n : ℕ} (a : Kˣ) (b : Fin n → Kˣ) :
    pfisterClass (Fin.cons a b) = oneFoldPfisterClass a * pfisterClass b := by
  rw [pfisterClass, pfisterForm_cons, map_mul]
  rw [map_add, map_one, oneFoldPfisterClass_eq, pfisterClass]

/-- A one-fold Pfister class agrees with the existing class of `<1, -a>`. -/
@[simp]
theorem pfisterClass_one (a : Kˣ) : pfisterClass ![a] = oneFoldPfisterClass a := by
  rw [pfisterClass_eq_prod]
  simp

/-- The two-fold Pfister class is the product `<<a>> * <<b>>`. -/
theorem pfisterClass_two (a b : Kˣ) :
    pfisterClass ![a, b] = oneFoldPfisterClass a * oneFoldPfisterClass b := by
  rw [show ![a, b] = Fin.cons a ![b] by funext i; fin_cases i <;> rfl,
    pfisterClass_cons, pfisterClass_one]

/-- Every `n`-fold Pfister class belongs to `I(K)^n`. -/
theorem pfisterClass_mem_fundamentalIdeal_pow {n : ℕ} (a : Fin n → Kˣ) :
    pfisterClass a ∈ fundamentalIdeal K ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [← Fin.cons_self_tail a, pfisterClass_cons, pow_succ']
      exact Ideal.mul_mem_mul (oneFoldPfisterClass_mem_fundamentalIdeal (a 0)) (ih (Fin.tail a))

private theorem range_pfisterClass_succ (n : ℕ) :
    Set.range (pfisterClass (K := K) (n := n + 1)) =
      Set.range (pfisterClass (K := K) (n := n)) *
        Set.range (oneFoldPfisterClass (K := K)) := by
  ext x
  constructor
  · rintro ⟨a, rfl⟩
    refine ⟨pfisterClass (Fin.tail a), Set.mem_range_self _,
      oneFoldPfisterClass (a 0), Set.mem_range_self _, ?_⟩
    calc
      pfisterClass (Fin.tail a) * oneFoldPfisterClass (a 0) =
          oneFoldPfisterClass (a 0) * pfisterClass (Fin.tail a) := mul_comm _ _
      _ = pfisterClass a := by rw [← pfisterClass_cons, Fin.cons_self_tail]
  · rintro ⟨_, ⟨a, rfl⟩, _, ⟨b, rfl⟩, rfl⟩
    exact ⟨Fin.cons b a, by rw [pfisterClass_cons, mul_comm]⟩

private theorem range_pfisterClass_one :
    Set.range (pfisterClass (K := K) (n := 1)) =
      Set.range (oneFoldPfisterClass (K := K)) := by
  ext x
  constructor
  · rintro ⟨a, rfl⟩
    refine ⟨a 0, by rw [← pfisterClass_one (a 0)]; congr 1; funext i
                    have hi : i = 0 := Fin.eq_zero i
                    subst i
                    rfl⟩
  · rintro ⟨a, rfl⟩
    exact ⟨![a], pfisterClass_one a⟩

/-- For `0 < n`, the additive group underlying `I(K)^n` is generated by the `n`-fold Pfister
classes. The positivity hypothesis excludes the generally false assertion that `W(K) = I(K)^0`
is additively generated by the zero-fold class `<1>`. -/
theorem fundamentalIdeal_pow_eq_addClosure {n : ℕ} (hn : 0 < n) :
    (fundamentalIdeal K ^ n).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := n))) := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  induction m with
  | zero =>
      rw [pow_one, range_pfisterClass_one,
        fundamentalIdeal_toAddSubgroup_eq_closure_oneFoldPfisterClass]
  | succ m ih =>
      rw [pow_succ', Ideal.toAddSubgroup_mul_eq_closure_mul
        fundamentalIdeal_toAddSubgroup_eq_closure_oneFoldPfisterClass (ih (by omega)), mul_comm,
        ← range_pfisterClass_succ]

/-- The square of the fundamental ideal is additively generated by two-fold Pfister classes. -/
theorem fundamentalIdeal_sq_eq_addClosure :
    (fundamentalIdeal K ^ 2).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := 2))) :=
  fundamentalIdeal_pow_eq_addClosure (by omega)

/-- The cube of the fundamental ideal is additively generated by three-fold Pfister classes. -/
theorem fundamentalIdeal_cube_eq_addClosure :
    (fundamentalIdeal K ^ 3).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := 3))) :=
  fundamentalIdeal_pow_eq_addClosure (by omega)

end TauCeti
