/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.Witt.FundamentalIdeal
public import TauCeti.RingTheory.Ideal.Operations

/-!
# Pfister classes and powers of the fundamental ideal

For units `a₁, …, aₙ`, the `n`-fold Pfister form is the tensor product

`<<a₁, …, aₙ>> = <<a₁>> ⋯ <<aₙ>>`,

where `<<a>> = <1, -a>`. This file defines its isometry class and Witt class and proves that, for
every positive `n`, the additive group underlying `I(K)^n` is generated by the `n`-fold Pfister
classes. The explicit two- and three-fold corollaries are the forms used to define and control the
Clifford invariant.

The positivity condition is necessary: `I(K)^0 = W(K)`, while the sole zero-fold Pfister class is
`<1>`, and a Witt ring need not be additively cyclic.

## Main definitions

* `TauCeti.pfisterFormClass`: the isometry class of an iterated Pfister tensor product.
* `TauCeti.pfisterClass`: its Witt class.

## Main results

* `TauCeti.fundamentalIdeal_pow_toAddSubgroup_eq_closure_pfisterClass`: positive powers of the
  fundamental ideal are additively generated by Pfister classes.
* `TauCeti.fundamentalIdeal_sq_toAddSubgroup_eq_closure_pfisterClass` and
  `TauCeti.fundamentalIdeal_pow_three_toAddSubgroup_eq_closure_pfisterClass`: the cases needed for
  the Clifford invariant.

## References

* T. Y. Lam, *Introduction to Quadratic Forms over Fields* (2005), Chapter II, §1 and
  Chapter X, with the convention `<<a>> = <1, -a>`.
-/

public section

open scoped BigOperators Pointwise

namespace TauCeti

universe u

variable {K : Type u} [Field K] [Invertible (2 : K)]

/-- The isometry class of the `n`-fold Pfister form, using the convention
`<<a>> = <1, -a>`. Orthogonal sum is addition and tensor product is multiplication on
`RegularFormClass`; the empty product is therefore the zero-fold form `<1>`. -/
@[expose]
noncomputable def pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) : RegularFormClass K :=
  ∏ i, (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -(a i)⟩)

/-- The defining product for the isometry class of an `n`-fold Pfister form. -/
theorem pfisterFormClass_def {n : ℕ} (a : Fin n → Kˣ) :
    pfisterFormClass a =
      ∏ i, (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -(a i)⟩) := rfl

/-- The Witt class of an `n`-fold Pfister form. -/
@[expose]
noncomputable def pfisterClass {n : ℕ} (a : Fin n → Kˣ) : WittRing K :=
  wittClass (pfisterFormClass a)

/-- Taking the Witt class of a Pfister form class gives its Pfister class. -/
@[simp]
theorem wittClass_pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) :
    wittClass (pfisterFormClass a) = pfisterClass a := rfl

/-- The Witt class of a Pfister form is the product of its one-fold factors. -/
theorem pfisterClass_eq_prod {n : ℕ} (a : Fin n → Kˣ) :
    pfisterClass a = ∏ i, oneFoldPfisterClass (a i) := by
  rw [pfisterClass, pfisterFormClass_def, map_prod]
  apply Finset.prod_congr rfl
  intro i _
  rw [map_add, map_one, oneFoldPfisterClass_eq]

/-- Splitting off the first slot splits a Pfister form as a tensor product. -/
theorem pfisterFormClass_cons {n : ℕ} (a : Kˣ) (b : Fin n → Kˣ) :
    pfisterFormClass (Fin.cons a b) =
      (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩) * pfisterFormClass b := by
  simp [pfisterFormClass_def, Fin.prod_univ_succ]

/-- The zero-fold Pfister form is the rank-one unit form. -/
@[simp]
theorem pfisterFormClass_zero (a : Fin 0 → Kˣ) : pfisterFormClass a = 1 := by
  simp [pfisterFormClass_def]

omit [Invertible (2 : K)] in
private theorem pfisterFactor_eq (a : Kˣ) :
    1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩ =
      Quotient.mk (regularFormSetoid K) ⟨2, ![1, -a]⟩ := by
  rw [← RegularFormClass.mk_rankOne_one, RegularFormClass.mk_add_mk]
  congr 1
  let p : RegularFormPresentation K := ⟨1, fun _ => 1⟩
  let q : RegularFormPresentation K := ⟨1, fun _ => -a⟩
  change p.append q = ⟨2, ![1, -a]⟩
  have h : (p.append q).1 = 2 := by simp [p, q]
  refine RegularFormPresentation.ext h ?_
  intro i
  generalize hj : Fin.cast h i = j
  fin_cases j
  · have hi : i = Fin.cast h.symm 0 := by
      calc
        i = Fin.cast h.symm (Fin.cast h i) := (Fin.leftInverse_cast h i).symm
        _ = Fin.cast h.symm 0 := congrArg (Fin.cast h.symm) hj
    rw [hi]
    simpa [p, q] using RegularFormPresentation.append_apply_castAdd p q (0 : Fin 1)
  · have hi : i = Fin.cast h.symm 1 := by
      calc
        i = Fin.cast h.symm (Fin.cast h i) := (Fin.leftInverse_cast h i).symm
        _ = Fin.cast h.symm 1 := congrArg (Fin.cast h.symm) hj
    rw [hi]
    simpa [p, q] using RegularFormPresentation.append_apply_natAdd p q (0 : Fin 1)

/-- A one-fold Pfister form has diagonal weights `<1, -a>`. -/
theorem pfisterFormClass_one (a : Fin 1 → Kˣ) :
    pfisterFormClass a =
      Quotient.mk (regularFormSetoid K) ⟨2, ![1, -(a 0)]⟩ := by
  rw [pfisterFormClass_def, Fin.prod_univ_one, pfisterFactor_eq]

/-- A two-fold Pfister form has diagonal weights `<1, -a, -b, ab>`. -/
theorem pfisterFormClass_two (a b : Kˣ) :
    pfisterFormClass ![a, b] =
      Quotient.mk (regularFormSetoid K) ⟨4, ![1, -a, -b, a * b]⟩ := by
  rw [pfisterFormClass_def, Fin.prod_univ_two]
  rw [pfisterFactor_eq, pfisterFactor_eq, mul_comm, RegularFormClass.mk_mul_mk]
  congr 1
  let p : RegularFormPresentation K := ⟨2, ![1, -b]⟩
  let q : RegularFormPresentation K := ⟨2, ![1, -a]⟩
  change p.tmul q = ⟨4, ![1, -a, -b, a * b]⟩
  have h : (p.tmul q).1 = 4 := by simp [p, q]
  have hweight (j : Fin 4) (x y : Fin 2) (hxy : finProdFinEquiv (x, y) = j) :
      (p.tmul q).2 (Fin.cast h.symm j) = p.2 x * q.2 y := by
    rw [← hxy, ← RegularFormPresentation.tmul_apply p q x y]
  refine RegularFormPresentation.ext h ?_
  intro i
  generalize hj : Fin.cast h i = j
  have hi : i = Fin.cast h.symm j := by
    calc
      i = Fin.cast h.symm (Fin.cast h i) := (Fin.leftInverse_cast h i).symm
      _ = Fin.cast h.symm j := congrArg (Fin.cast h.symm) hj
  rw [hi]
  fin_cases j
  · simpa [p, q] using
      hweight 0 0 0 (by apply Fin.ext; rw [finProdFinEquiv_apply_val]; norm_num)
  · simpa [p, q] using
      hweight 1 0 1 (by apply Fin.ext; rw [finProdFinEquiv_apply_val]; norm_num)
  · simpa [p, q] using
      hweight 2 1 0 (by apply Fin.ext; rw [finProdFinEquiv_apply_val]; norm_num)
  · simpa [p, q, mul_comm] using
      hweight 3 1 1 (by apply Fin.ext; rw [finProdFinEquiv_apply_val]; norm_num)

/-- An `n`-fold Pfister form has rank `2 ^ n`. -/
@[simp]
theorem RegularFormClass.rank_pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) :
    RegularFormClass.rank (pfisterFormClass a) = 2 ^ n := by
  rw [pfisterFormClass_def, ← RegularFormClass.rankHom_apply, map_prod]
  simp [RegularFormClass.rankHom_apply, RegularFormClass.rank_mk]

/-- The zero-fold Pfister class is the unit of the Witt ring. -/
@[simp]
theorem pfisterClass_zero (a : Fin 0 → Kˣ) : pfisterClass a = 1 := by
  simp [pfisterClass]

/-- Splitting off the first slot splits a Pfister class as a product. -/
theorem pfisterClass_cons {n : ℕ} (a : Kˣ) (b : Fin n → Kˣ) :
    pfisterClass (Fin.cons a b) = oneFoldPfisterClass a * pfisterClass b := by
  rw [pfisterClass, pfisterFormClass_cons, map_mul]
  rw [map_add, map_one, oneFoldPfisterClass_eq, pfisterClass]

/-- A one-fold Pfister class agrees with the existing class of `<1, -a>`. -/
@[simp]
theorem pfisterClass_one (a : Fin 1 → Kˣ) :
    pfisterClass a = oneFoldPfisterClass (a 0) := by
  rw [pfisterClass_eq_prod]
  rw [Fin.prod_univ_one]

/-- The two-fold Pfister class is the product `<<a>> * <<b>>`. -/
theorem pfisterClass_two (a b : Kˣ) :
    pfisterClass ![a, b] = oneFoldPfisterClass a * oneFoldPfisterClass b := by
  simp [pfisterClass_eq_prod, Fin.prod_univ_two]

/-- Every `n`-fold Pfister class belongs to `I(K)^n`. -/
theorem pfisterClass_mem_fundamentalIdeal_pow {n : ℕ} (a : Fin n → Kˣ) :
    pfisterClass a ∈ fundamentalIdeal K ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [← Fin.cons_self_tail a, pfisterClass_cons, pow_succ']
      exact Ideal.mul_mem_mul (oneFoldPfisterClass_mem_fundamentalIdeal (a 0)) (ih (Fin.tail a))

private theorem range_pfisterClass_succ (n : ℕ) :
    Set.range (pfisterClass (K := K) (n := n + 1)) =
      Set.range (pfisterClass (K := K) (n := n)) *
        Set.range (oneFoldPfisterClass (K := K)) := by
  ext x
  constructor
  · rintro ⟨a, rfl⟩
    refine ⟨pfisterClass (Fin.tail a), Set.mem_range_self _,
      oneFoldPfisterClass (a 0), Set.mem_range_self _, ?_⟩
    calc
      pfisterClass (Fin.tail a) * oneFoldPfisterClass (a 0) =
          oneFoldPfisterClass (a 0) * pfisterClass (Fin.tail a) := mul_comm _ _
      _ = pfisterClass a := by rw [← pfisterClass_cons, Fin.cons_self_tail]
  · rintro ⟨_, ⟨a, rfl⟩, _, ⟨b, rfl⟩, rfl⟩
    exact ⟨Fin.cons b a, by rw [pfisterClass_cons, mul_comm]⟩

private theorem range_pfisterClass_one :
    Set.range (pfisterClass (K := K) (n := 1)) =
      Set.range (oneFoldPfisterClass (K := K)) := by
  ext x
  constructor
  · rintro ⟨a, rfl⟩
    exact ⟨a 0, (pfisterClass_one a).symm⟩
  · rintro ⟨a, rfl⟩
    exact ⟨![a], by simp⟩

/-- For `0 < n`, the additive group underlying `I(K)^n` is generated by the `n`-fold Pfister
classes. The positivity hypothesis excludes the generally false assertion that `W(K) = I(K)^0`
is additively generated by the zero-fold class `<1>`. -/
theorem fundamentalIdeal_pow_toAddSubgroup_eq_closure_pfisterClass {n : ℕ} (hn : 0 < n) :
    (fundamentalIdeal K ^ n).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := n))) := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  clear hn
  induction m with
  | zero =>
      rw [pow_one, range_pfisterClass_one,
        fundamentalIdeal_toAddSubgroup_eq_closure_oneFoldPfisterClass]
  | succ m ih =>
      rw [pow_succ', Ideal.toAddSubgroup_mul_eq_closure_mul
        fundamentalIdeal_toAddSubgroup_eq_closure_oneFoldPfisterClass ih,
        mul_comm (Set.range (oneFoldPfisterClass (K := K))) _, ← range_pfisterClass_succ]

/-- The square of the fundamental ideal is additively generated by two-fold Pfister classes. -/
theorem fundamentalIdeal_sq_toAddSubgroup_eq_closure_pfisterClass :
    (fundamentalIdeal K ^ 2).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := 2))) :=
  fundamentalIdeal_pow_toAddSubgroup_eq_closure_pfisterClass (by omega)

/-- The cube of the fundamental ideal is additively generated by three-fold Pfister classes. -/
theorem fundamentalIdeal_pow_three_toAddSubgroup_eq_closure_pfisterClass :
    (fundamentalIdeal K ^ 3).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := 3))) :=
  fundamentalIdeal_pow_toAddSubgroup_eq_closure_pfisterClass (by omega)

end TauCeti
