/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import TauCeti.Algebra.Order.Group.ConvexSubgroup
import Mathlib.Algebra.Order.Monoid.Unbundled.Pow

/-!
# Cofinal elements and the Archimedean characterization of convex subgroups

The cofinality theory of linearly ordered commutative groups following Wedhorn,
*Adic Spaces* (arXiv:1910.05934v1), §1.4: an element is cofinal for a convex subgroup
if its powers eventually fall below every member. This is the order-theoretic input
to the continuity criterion for valuations (Wedhorn §7.2) and the retraction
`r_I : Spv A → Spv(A, I)` of §7.1.2.

## Main definitions

* `TauCeti.IsCofinalElement H γ` : Powers of `γ` fall below every member
  of `H` (Wedhorn Definition 1.16). Unlike Mathlib's `IsCofinal`, which describes a
  *set* that is cofinal for the ambient order with respect to `≤`, this is a property of
  an *element* with respect to the strict order, following Wedhorn.

## Main results

* `TauCeti.isCofinalElement_iff_subset_closure` : For `γ < 1`, `γ` is
  cofinal for `H` iff the convex subgroup generated by `γ` contains `H`
  (Wedhorn Remark 1.19).
* `TauCeti.IsCofinalElement.mul_of_lt_of_mem` : Cofinal elements may be
  perturbed by members of any strictly smaller convex subgroup (Wedhorn
  Proposition 1.20).

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Definition 1.16, Remark 1.19,
  Proposition 1.20

Adapted from the AINTLIB development (Apache 2.0), file
`projects/AdicSpaces/Adic spaces/OrderedGroupConvex.lean` (the cofinality half; its
convex-subgroup half is the parent module), with the predicate restated over subgroups
as in Wedhorn's Definition 1.16.
-/

public section

namespace TauCeti

open ConvexSubgroup

variable {Γ : Type*} [CommGroup Γ] [LinearOrder Γ] [IsOrderedMonoid Γ]

/-! ### Cofinal elements -/

/-- An element `γ` is **cofinal** for the subgroup `H` if every member of `H`
eventually dominates the powers of `γ`: `∀ h ∈ H, ∃ n, γ ^ n < h`. This is the
`γ ∈ Γ` case of Wedhorn Definition 1.16, which takes `H` to be any subgroup and
lets the base range over `Γ ∪ {0}`; the adjoined base `0` is cofinal for every
subgroup trivially, and the case that matters for valuations — where a value may
vanish — is `TauCeti.Valuation.CofinalValue`, stated on the value group with zero.
Membership of `γ` in `H` is not required. Distinct from Mathlib's `IsCofinal`,
a property of sets with respect to `≤`. -/
def IsCofinalElement (H : Subgroup Γ) (γ : Γ) : Prop :=
  ∀ h ∈ H, ∃ n : ℕ, γ ^ n < h

omit [IsOrderedMonoid Γ] in
/-- The defining property of a cofinal element. -/
@[simp]
theorem isCofinalElement_def {H : Subgroup Γ} {γ : Γ} :
    IsCofinalElement H γ ↔ ∀ h ∈ H, ∃ n : ℕ, γ ^ n < h :=
  Iff.rfl

/-- No element `≥ 1` is cofinal for any subgroup (Wedhorn's remark after
Definition 1.16): a cofinal element lies strictly below `1`. -/
theorem IsCofinalElement.lt_one {H : Subgroup Γ} {γ : Γ}
    (hγ : IsCofinalElement H γ) : γ < 1 := by
  obtain ⟨n, hn⟩ := hγ 1 (one_mem H)
  by_contra h
  push Not at h
  exact absurd hn (not_lt.mpr (one_le_pow_of_one_le' h n))

/-- **Wedhorn Remark 1.19.** For `γ < 1`, the element `γ` is cofinal for `H` iff the
convex subgroup generated by `γ` contains `H`. -/
theorem isCofinalElement_iff_subset_closure {H : Subgroup Γ} {γ : Γ} (hγ1 : γ < 1) :
    IsCofinalElement H γ ↔ (H : Set Γ) ⊆ closure {γ} := by
  constructor
  · intro hγ h hh
    obtain ⟨n, hn⟩ := hγ h hh
    obtain ⟨m, hm⟩ := hγ h⁻¹ (inv_mem hh)
    rw [SetLike.mem_coe, mem_closure_singleton_of_le_one hγ1.le]
    refine ⟨max n m, ?_, ?_⟩
    · exact (pow_le_pow_right_of_le_one' hγ1.le (le_max_left n m)).trans hn.le
    · have h1 : h < (γ ^ m)⁻¹ := by
        have h2 := inv_lt_inv' hm
        rwa [inv_inv] at h2
      exact h1.le.trans (inv_le_inv' (pow_le_pow_right_of_le_one' hγ1.le (le_max_right n m)))
  · intro hsub h hh
    obtain ⟨n, hle, -⟩ := (mem_closure_singleton_of_le_one hγ1.le).mp (hsub hh)
    have hstep : γ ^ (n + 1) < γ ^ n := by
      calc γ ^ (n + 1) = γ * γ ^ n := by rw [pow_succ, mul_comm]
        _ < 1 * γ ^ n := mul_lt_mul_left hγ1 (γ ^ n)
        _ = γ ^ n := one_mul _
    exact ⟨n + 1, hstep.trans_le hle⟩

/-- A strictly smaller convex subgroup admits a member of the larger one above it. -/
private theorem exists_one_lt_of_lt {Γ' Δ : ConvexSubgroup Γ} (hlt : Δ < Γ') :
    ∃ z, z ∈ Γ' ∧ z ∉ Δ ∧ 1 < z := by
  obtain ⟨x, hxQ, hxD⟩ := SetLike.exists_of_lt hlt
  rcases lt_trichotomy x 1 with hl | he | hg
  · exact ⟨x⁻¹, inv_mem hxQ, fun e ↦ hxD (by simpa using inv_mem e), one_lt_inv'.mpr hl⟩
  · exact absurd (he ▸ one_mem Δ) hxD
  · exact ⟨x, hxQ, hxD, hg⟩

/-- **Wedhorn Proposition 1.20.** If `γ` is cofinal for the convex subgroup `Γ'` and
`Δ < Γ'` is a strictly smaller convex subgroup, then `δ * γ` is cofinal for `Γ'` for
every `δ ∈ Δ`. -/
theorem IsCofinalElement.mul_of_lt_of_mem {Γ' Δ : ConvexSubgroup Γ}
    {γ : Γ} (hγ : IsCofinalElement Γ'.toSubgroup γ) (hlt : Δ < Γ') {δ : Γ}
    (hδ : δ ∈ Δ) : IsCofinalElement Γ'.toSubgroup (δ * γ) := by
  intro h hh
  obtain ⟨z, hzQ, hzD, hz_gt⟩ := exists_one_lt_of_lt hlt
  obtain ⟨n, hn⟩ := hγ z⁻¹ (inv_mem hzQ)
  have hzi_lt : z⁻¹ < 1 := inv_lt_one'.mpr hz_gt
  have hγ_lt : γ < 1 := hγ.lt_one
  have hn1 : 1 ≤ n := by
    rcases Nat.eq_zero_or_pos n with rfl | hp
    · simp only [pow_zero] at hn
      exact absurd (hn.trans hzi_lt) (lt_irrefl _)
    · exact hp
  have hz_gt_D : ∀ d ∈ Δ, d < z := fun d hd ↦ by
    by_contra hge
    rw [not_lt] at hge
    exact hzD (Δ.convex (one_mem Δ) hd hz_gt.le hge)
  have hzγn : z * γ ^ n < 1 := by
    have h2 : γ ^ n * z < z⁻¹ * z := mul_lt_mul_left hn z
    rw [inv_mul_cancel] at h2
    rwa [mul_comm] at h2
  have hkey : (δ * γ) ^ (2 * n) < γ ^ n := by
    have hδ2n : δ ^ (2 * n) < z := hz_gt_D _ (Δ.toSubgroup.pow_mem hδ (2 * n))
    calc (δ * γ) ^ (2 * n) = δ ^ (2 * n) * γ ^ (2 * n) := mul_pow δ γ (2 * n)
      _ < z * γ ^ (2 * n) := mul_lt_mul_left hδ2n _
      _ = (z * γ ^ n) * γ ^ n := by rw [two_mul, pow_add, ← mul_assoc]
      _ < 1 * γ ^ n := mul_lt_mul_left hzγn _
      _ = γ ^ n := one_mul _
  obtain ⟨m, hm1, hm⟩ : ∃ m, 1 ≤ m ∧ γ ^ m < h := by
    obtain ⟨m0, hm0⟩ := hγ h hh
    rcases Nat.eq_zero_or_pos m0 with rfl | hp
    · refine ⟨1, le_refl _, ?_⟩
      rw [pow_one]
      rw [pow_zero] at hm0
      exact lt_trans hγ_lt hm0
    · exact ⟨m0, hp, hm0⟩
  refine ⟨2 * n * m, ?_⟩
  calc (δ * γ) ^ (2 * n * m) = ((δ * γ) ^ (2 * n)) ^ m := by rw [← pow_mul]
    _ < (γ ^ n) ^ m := pow_lt_pow_left' (Nat.one_le_iff_ne_zero.mp hm1) hkey
    _ = γ ^ (n * m) := by rw [← pow_mul]
    _ ≤ γ ^ m := pow_le_pow_right_of_le_one' hγ_lt.le (Nat.le_mul_of_pos_left m hn1)
    _ < h := hm

end TauCeti
