/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import TauCeti.Algebra.Order.Group.ConvexSubgroup
public import Mathlib.Algebra.Order.Archimedean.Basic
public import Mathlib.Algebra.Order.Monoid.Unbundled.Pow

/-!
# Cofinal elements and the Archimedean characterization of convex subgroups

The cofinality theory of linearly ordered commutative groups following Wedhorn,
*Adic Spaces* (arXiv:1910.05934v1), §1.4: an element is cofinal for a convex subgroup
if its powers eventually fall below every member. This is the order-theoretic input
to the continuity criterion for valuations (Wedhorn §7.2) and the retraction
`r_I : Spv A → Spv(A, I)` of §7.1.2.

## Main definitions

* `TauCeti.ConvexSubgroup.IsCofinalElement H γ` : Powers of `γ` fall below every member
  of `H` (Wedhorn Definition 1.16). Unlike Mathlib's `IsCofinal`, which describes a
  *set* that is cofinal for the ambient order with respect to `≤`, this is a property of
  an *element* with respect to the strict order, following Wedhorn.

## Main results

* `TauCeti.ConvexSubgroup.mem_closure_singleton` : The convex subgroup generated by a
  single element `1 ≤ y` consists of the elements bounded between inverse powers and
  powers of `y`.
* `TauCeti.ConvexSubgroup.isCofinalElement_iff_subset_closure` : For `γ < 1`, `γ` is
  cofinal for `H` iff the convex subgroup generated by `γ` contains `H`
  (Wedhorn Remark 1.19).
* `TauCeti.ConvexSubgroup.IsCofinalElement.mul_of_mem_of_lt` : Cofinal elements may be
  perturbed by members of any strictly smaller convex subgroup (Wedhorn
  Proposition 1.20).
* `TauCeti.ConvexSubgroup.mulArchimedean_iff_forall_eq_bot_or_eq_top` : A linearly
  ordered commutative group is `MulArchimedean` iff its only convex subgroups are `⊥`
  and `⊤`.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Definition 1.16, Remark 1.19,
  Proposition 1.20
-/

public section

namespace TauCeti.ConvexSubgroup

variable {Γ : Type*} [CommGroup Γ] [LinearOrder Γ] [IsOrderedMonoid Γ]

/-! ### The convex subgroup generated by one element -/

/-- The bounded-powers convex subgroup: the elements between inverse powers and powers
of `y`. This is the explicit form of `closure {y}`; see `mem_closure_singleton`. -/
private def boundedPowers (y : Γ) (hy : 1 ≤ y) : ConvexSubgroup Γ where
  toSubgroup :=
    { carrier := {h | ∃ n : ℕ, (y ^ n)⁻¹ ≤ h ∧ h ≤ y ^ n}
      mul_mem' := by
        rintro a b ⟨n₁, ha_lo, ha_hi⟩ ⟨n₂, hb_lo, hb_hi⟩
        refine ⟨n₁ + n₂, ?_, ?_⟩
        · rw [pow_add, mul_inv_rev, mul_comm]
          exact mul_le_mul' ha_lo hb_lo
        · exact (mul_le_mul' ha_hi hb_hi).trans (pow_add y n₁ n₂ ▸ le_refl _)
      one_mem' := ⟨0, by simp, by simp⟩
      inv_mem' := by
        rintro a ⟨n, ha_lo, ha_hi⟩
        exact ⟨n, inv_le_inv' ha_hi, inv_inv (y ^ n) ▸ inv_le_inv' ha_lo⟩ }
  ordConnected' := by
    constructor
    rintro a ⟨n₁, ha_lo, -⟩ b ⟨n₂, -, hb_hi⟩ x hx
    exact ⟨max n₁ n₂,
      (inv_le_inv' (pow_le_pow_right' hy (le_max_left _ _))).trans (ha_lo.trans hx.1),
      hx.2.trans (hb_hi.trans (pow_le_pow_right' hy (le_max_right _ _)))⟩

/-- The convex subgroup generated by a single element `1 ≤ y` consists of the elements
bounded between inverse powers and powers of `y`. Not a `simp` lemma: `mem_closure`
already normalizes membership in a convex closure. -/
theorem mem_closure_singleton {y : Γ} (hy : 1 ≤ y) {x : Γ} :
    x ∈ closure {y} ↔ ∃ n : ℕ, (y ^ n)⁻¹ ≤ x ∧ x ≤ y ^ n := by
  constructor
  · intro hx
    refine mem_closure.mp hx (boundedPowers y hy) fun z hz ↦ ?_
    rw [Set.mem_singleton_iff] at hz
    subst hz
    exact ⟨1, by simpa using (inv_le_one_of_one_le hy).trans hy, by simp⟩
  · rintro ⟨n, hlo, hhi⟩
    have hy_mem : y ∈ closure ({y} : Set Γ) := subset_closure _ rfl
    exact (closure {y}).convex (inv_mem ((closure {y}).toSubgroup.pow_mem hy_mem n))
      ((closure {y}).toSubgroup.pow_mem hy_mem n) hlo hhi

omit [IsOrderedMonoid Γ] in
/-- The convex subgroup generated by an element equals the one generated by its
inverse. -/
theorem closure_singleton_inv (y : Γ) : closure {y⁻¹} = closure ({y} : Set Γ) := by
  refine le_antisymm (closure_le.mpr ?_) (closure_le.mpr ?_)
  · intro z hz
    rw [Set.mem_singleton_iff] at hz
    rw [hz]
    exact inv_mem (subset_closure _ rfl)
  · intro z hz
    rw [Set.mem_singleton_iff] at hz
    rw [hz]
    exact inv_mem_iff.mp (subset_closure ({y⁻¹} : Set Γ) rfl)

/-! ### Cofinal elements -/

/-- An element `γ` is **cofinal** for the convex subgroup `H` if every member of `H`
eventually dominates the powers of `γ`: `∀ h ∈ H, ∃ n, γ ^ n < h` (Wedhorn
Definition 1.16, which quantifies over arbitrary `γ ∈ Γ` — membership in `H` is not
required). Distinct from Mathlib's `IsCofinal`, a property of sets with respect
to `≤`. -/
def IsCofinalElement (H : ConvexSubgroup Γ) (γ : Γ) : Prop :=
  ∀ h ∈ H, ∃ n : ℕ, γ ^ n < h

/-- No element `≥ 1` is cofinal for any convex subgroup (Wedhorn's remark after
Definition 1.16): a cofinal element lies strictly below `1`. -/
theorem IsCofinalElement.lt_one {H : ConvexSubgroup Γ} {γ : Γ}
    (hγ : IsCofinalElement H γ) : γ < 1 := by
  obtain ⟨n, hn⟩ := hγ 1 (one_mem H)
  by_contra h
  push Not at h
  exact absurd hn (not_lt.mpr (one_le_pow_of_one_le' h n))

/-- **Wedhorn Remark 1.19.** For `γ < 1`, the element `γ` is cofinal for `H` iff the
convex subgroup generated by `γ` contains `H`. -/
theorem isCofinalElement_iff_subset_closure {H : ConvexSubgroup Γ} {γ : Γ} (hγ1 : γ < 1) :
    IsCofinalElement H γ ↔ (H : Set Γ) ⊆ closure {γ} := by
  have hinv : (1 : Γ) ≤ γ⁻¹ := one_le_inv_of_le_one hγ1.le
  constructor
  · intro hγ h hh
    obtain ⟨n, hn⟩ := hγ h hh
    obtain ⟨m, hm⟩ := hγ h⁻¹ (inv_mem hh)
    rw [SetLike.mem_coe, ← closure_singleton_inv, mem_closure_singleton hinv]
    refine ⟨max n m, ?_, ?_⟩
    · calc ((γ⁻¹ ^ max n m)⁻¹ : Γ) = γ ^ max n m := by rw [inv_pow, inv_inv]
        _ ≤ γ ^ n := pow_le_pow_right_of_le_one' hγ1.le (le_max_left n m)
        _ ≤ h := hn.le
    · have h1 : h < (γ ^ m)⁻¹ := by
        have h2 := inv_lt_inv' hm
        rwa [inv_inv] at h2
      calc h ≤ (γ ^ m)⁻¹ := h1.le
        _ = γ⁻¹ ^ m := by rw [inv_pow]
        _ ≤ γ⁻¹ ^ max n m := pow_le_pow_right' hinv (le_max_right n m)
  · intro hsub h hh
    obtain ⟨n, hlo, -⟩ := (mem_closure_singleton hinv).mp
      (closure_singleton_inv γ ▸ hsub hh)
    have hle : γ ^ n ≤ h := by rwa [inv_pow, inv_inv] at hlo
    have hstep : γ ^ (n + 1) < γ ^ n := by
      calc γ ^ (n + 1) = γ * γ ^ n := by rw [pow_succ, mul_comm]
        _ < 1 * γ ^ n := mul_lt_mul_left hγ1 (γ ^ n)
        _ = γ ^ n := one_mul _
    exact ⟨n + 1, hstep.trans_le hle⟩

/-- A strictly smaller convex subgroup admits a member of the larger one above it. -/
private theorem exists_one_lt_of_lt {Γ' Δ : ConvexSubgroup Γ} (hlt : Δ < Γ') :
    ∃ z, z ∈ Γ' ∧ z ∉ Δ ∧ 1 < z := by
  obtain ⟨x, hxQ, hxD⟩ := SetLike.exists_of_lt hlt
  rcases lt_trichotomy x 1 with hl | he | hg
  · exact ⟨x⁻¹, inv_mem hxQ, fun e ↦ hxD (by simpa using inv_mem e), one_lt_inv'.mpr hl⟩
  · exact absurd (he ▸ one_mem Δ) hxD
  · exact ⟨x, hxQ, hxD, hg⟩

/-- **Wedhorn Proposition 1.20.** If `γ` is cofinal for the convex subgroup `Γ'` and
`Δ < Γ'` is a strictly smaller convex subgroup, then `δ * γ` is cofinal for `Γ'` for
every `δ ∈ Δ`. -/
theorem IsCofinalElement.mul_of_mem_of_lt {Γ' Δ : ConvexSubgroup Γ}
    {γ : Γ} (hγ : IsCofinalElement Γ' γ) (hlt : Δ < Γ') {δ : Γ} (hδ : δ ∈ Δ) :
    IsCofinalElement Γ' (δ * γ) := by
  intro h hh
  obtain ⟨z, hzQ, hzD, hz_gt⟩ := exists_one_lt_of_lt hlt
  obtain ⟨n, hn⟩ := hγ z⁻¹ (inv_mem hzQ)
  have hzi_lt : z⁻¹ < 1 := inv_lt_one'.mpr hz_gt
  have hγ_lt : γ < 1 := hγ.lt_one
  have hn1 : 1 ≤ n := by
    rcases Nat.eq_zero_or_pos n with rfl | hp
    · simp only [pow_zero] at hn
      exact absurd (hn.trans hzi_lt) (lt_irrefl _)
    · exact hp
  have hz_gt_D : ∀ d ∈ Δ, d < z := fun d hd ↦ by
    by_contra hge
    rw [not_lt] at hge
    exact hzD (Δ.convex (one_mem Δ) hd hz_gt.le hge)
  have hzγn : z * γ ^ n < 1 := by
    have h2 : γ ^ n * z < z⁻¹ * z := mul_lt_mul_left hn z
    rw [inv_mul_cancel] at h2
    rwa [mul_comm] at h2
  have hkey : (δ * γ) ^ (2 * n) < γ ^ n := by
    have hδ2n : δ ^ (2 * n) < z := hz_gt_D _ (Δ.toSubgroup.pow_mem hδ (2 * n))
    calc (δ * γ) ^ (2 * n) = δ ^ (2 * n) * γ ^ (2 * n) := mul_pow δ γ (2 * n)
      _ < z * γ ^ (2 * n) := mul_lt_mul_left hδ2n _
      _ = (z * γ ^ n) * γ ^ n := by rw [two_mul, pow_add, ← mul_assoc]
      _ < 1 * γ ^ n := mul_lt_mul_left hzγn _
      _ = γ ^ n := one_mul _
  obtain ⟨m, hm1, hm⟩ : ∃ m, 1 ≤ m ∧ γ ^ m < h := by
    obtain ⟨m0, hm0⟩ := hγ h hh
    rcases Nat.eq_zero_or_pos m0 with rfl | hp
    · refine ⟨1, le_refl _, ?_⟩
      rw [pow_one]
      rw [pow_zero] at hm0
      exact lt_trans hγ_lt hm0
    · exact ⟨m0, hp, hm0⟩
  refine ⟨2 * n * m, ?_⟩
  calc (δ * γ) ^ (2 * n * m) = ((δ * γ) ^ (2 * n)) ^ m := by rw [← pow_mul]
    _ < (γ ^ n) ^ m := pow_lt_pow_left' (Nat.one_le_iff_ne_zero.mp hm1) hkey
    _ = γ ^ (n * m) := by rw [← pow_mul]
    _ ≤ γ ^ m := pow_le_pow_right_of_le_one' hγ_lt.le (Nat.le_mul_of_pos_left m hn1)
    _ < h := hm

/-! ### The Archimedean characterization -/

/-- In a `MulArchimedean` group every convex subgroup is `⊥` or `⊤`. -/
theorem eq_bot_or_eq_top_of_mulArchimedean [MulArchimedean Γ] (H : ConvexSubgroup Γ) :
    H = ⊥ ∨ H = ⊤ := by
  by_contra hH
  push Not at hH
  obtain ⟨hbot, htop⟩ := hH
  obtain ⟨y, hy, hy1⟩ : ∃ y ∈ H, 1 < y := by
    obtain ⟨y, hy, hy1⟩ : ∃ y ∈ H, y ≠ 1 := by
      by_contra h
      push Not at h
      exact hbot (ext fun x ↦ ⟨fun hx ↦ mem_bot.mpr (h x hx), fun hx ↦ mem_bot.mp hx ▸ one_mem H⟩)
    rcases lt_or_gt_of_ne hy1 with h | h
    · exact ⟨y⁻¹, inv_mem hy, one_lt_inv'.mpr h⟩
    · exact ⟨y, hy, h⟩
  obtain ⟨x, hx, hx1⟩ : ∃ x, x ∉ H ∧ 1 < x := by
    obtain ⟨x, hxH⟩ : ∃ x, x ∉ H := by
      by_contra h
      push Not at h
      exact htop (ext fun x ↦ ⟨fun _ ↦ mem_top, fun _ ↦ h x⟩)
    rcases lt_or_gt_of_ne (show x ≠ 1 from fun h ↦ hxH (h ▸ one_mem H)) with h | h
    · exact ⟨x⁻¹, inv_mem_iff.not.mpr hxH, one_lt_inv'.mpr h⟩
    · exact ⟨x, hxH, h⟩
  obtain ⟨n, hn⟩ := MulArchimedean.arch x hy1
  exact hx (H.convex (one_mem H) (H.toSubgroup.pow_mem hy n) hx1.le hn)

/-- If every convex subgroup is `⊥` or `⊤`, the group is `MulArchimedean`. -/
theorem mulArchimedean_of_forall_eq_bot_or_eq_top
    (h : ∀ H : ConvexSubgroup Γ, H = ⊥ ∨ H = ⊤) : MulArchimedean Γ where
  arch x {y} hy := by
    by_contra hna
    push Not at hna
    have hy_mem : y ∈ closure ({y} : Set Γ) := subset_closure _ rfl
    have hx_nmem : x ∉ closure ({y} : Set Γ) := fun hx ↦ by
      obtain ⟨n, -, hle⟩ := (mem_closure_singleton hy.le).mp hx
      exact not_le.mpr (hna n) hle
    rcases h (closure {y}) with heq | heq
    · exact ne_of_gt hy (mem_bot.mp (heq ▸ hy_mem))
    · exact hx_nmem (heq ▸ mem_top)

/-- **The Archimedean characterization.** A linearly ordered commutative group is
`MulArchimedean` iff its only convex subgroups are `⊥` and `⊤`. -/
theorem mulArchimedean_iff_forall_eq_bot_or_eq_top :
    MulArchimedean Γ ↔ ∀ H : ConvexSubgroup Γ, H = ⊥ ∨ H = ⊤ :=
  ⟨fun _ ↦ eq_bot_or_eq_top_of_mulArchimedean, mulArchimedean_of_forall_eq_bot_or_eq_top⟩

end TauCeti.ConvexSubgroup
