/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.DirichletDensity
public import TauCeti.NumberTheory.Chebotarev.FrobeniusPrimeSet
import TauCeti.NumberTheory.Chebotarev.Density.Abelian
import TauCeti.NumberTheory.Chebotarev.Density.FixedField

/-!
# The Chebotarev density theorem

Let `L / K` be a finite Galois extension of number fields with group `G`, and let `C` be a
conjugacy class of `G`. The primes of `𝓞 K` whose Frobenius in `L` lies in `C` have Dirichlet
density `#C / #G`.

## Main results

* `NumberField.Chebotarev.hasDirichletDensity_frobeniusPrimeSet`: the Chebotarev density theorem,
  for Dirichlet density.

## Implementation notes

For `σ ∈ C` put `E = L ^ ⟨σ⟩`. The extension `L / E` is cyclic, generated by `σ`, so abelian
Chebotarev gives the relative Frobenius fibre of `σ` over `E` density `1 / orderOf σ`; the
fixed-field contraction carries this down to the density `#C / #G` over `K`.

## References

* R. Sharifi, *Algebraic Number Theory*, Theorem 7.2.2.
* J. Neukirch, *Algebraic Number Theory*, Chapter VII, §13.
-/

public section

open IntermediateField

namespace NumberField.Chebotarev

variable (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L]
  [IsGalois K L]

/-- **The Chebotarev density theorem.** For a finite Galois extension `L / K` of number fields
and a conjugacy class `C` of `Gal(L/K)`, the primes of `𝓞 K` whose Frobenius in `L` lies in `C`
have Dirichlet density `#C / #Gal(L/K)`. -/
theorem hasDirichletDensity_frobeniusPrimeSet (C : ConjClasses (L ≃ₐ[K] L)) :
    NumberField.Set.HasDirichletDensity (frobeniusPrimeSet K L C)
      ((Nat.card C.carrier : ℝ) / (Nat.card (L ≃ₐ[K] L) : ℝ)) := by
  obtain ⟨σ, rfl⟩ := ConjClasses.mk_surjective C
  refine hasDirichletDensity_frobeniusPrimeSet_of_fixedField _ σ ConjClasses.mem_carrier_mk ?_
  -- `Gal(L / L ^ ⟨σ⟩)` is generated by `σ`, so it is abelian.
  have hab (a b : L ≃ₐ[fixedField (Subgroup.zpowers σ)] L) : a * b = b * a := by
    have hmem (x : L ≃ₐ[fixedField (Subgroup.zpowers σ)] L) :
        x ∈ Subgroup.zpowers σ.toFixedFieldAlgEquiv :=
      AlgEquiv.zpowers_toFixedFieldAlgEquiv_eq_top σ ▸ Subgroup.mem_top x
    obtain ⟨i, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hmem a)
    obtain ⟨j, rfl⟩ := Subgroup.mem_zpowers_iff.mp (hmem b)
    exact zpow_mul_comm _ i j
  have h := hasDirichletDensity_abelianFrobenius _ L hab σ.toFixedFieldAlgEquiv
  rwa [AlgEquiv.card_algEquiv_fixedField_zpowers] at h

end NumberField.Chebotarev
