/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.Algebra.Order.Hom.MonoidWithZero
public import Mathlib.Algebra.Order.Hom.Units
public import Mathlib.RingTheory.Valuation.Basic
public import TauCeti.Algebra.Order.Group.ConvexSubgroup

/-!
# The characteristic subgroup of a valuation, cofinal values, and fullness

The characteristic subgroup `cΓ_v` of Wedhorn, *Adic Spaces* (arXiv:1910.05934v1), 4.13 —
the convex subgroup of the value group generated by the attained values `≥ 1` — together
with the two value conditions of the `Spv (A, I)` theory of §4.3 and §7.1 that are stated
against it. They share a file because the fullness condition `Γ_v = cΓ_v` is precisely a
statement about this subgroup, and the `Spv (A, I)` membership criterion of Lemma 7.4
combines it with cofinality. Both are formulated
on the **value group** of `v` — Mathlib's `ValueGroup₀ (.ofClass v)`, via the restricted
valuation `v.restrict` — not on the ambient codomain, so they are invariant under valuation
equivalence (`IsEquiv.cofinalValue_iff`, `IsEquiv.hasFullCharacteristicGroup_iff`) and can
be consumed on points of the valuation spectrum:

* a value `v a` is *cofinal* if its powers fall below every positive element of the value
  group — the condition on ideals of definition in Wedhorn Lemma 7.1;
* `v` *has full characteristic group* if every positive element of the value group is
  bounded between `(v a)⁻¹` and `v a` for some `a` — the elementwise
  reading of "`Γ_v = cΓ_v`", for the characteristic subgroup `cΓ_v` of Wedhorn 4.13.

These are the two disjuncts of the membership criterion for `Spv (A, I)`: Wedhorn
Lemma 7.4 proves `cΓ_v(I) = Γ_v` equivalent to "`v a` is cofinal for every `a ∈ I`, or
`Γ_v = cΓ_v`". The *microbial* condition of Wedhorn Definition 5.46 (existence of a
dependent height-one valuation) is a genuinely different notion and is deliberately not
formalised here.

## Main definitions

* `TauCeti.Valuation.CofinalValue v a` : Powers of `v a` fall below every positive element
  of the value group of `v`.
* `TauCeti.Valuation.characteristicGenerators v` and
  `TauCeti.Valuation.characteristicSubgroup v` : The attained values `≥ 1` and the convex
  subgroup `cΓ_v` they generate.
* `TauCeti.Valuation.HasFullCharacteristicGroup v` : Every positive element of the value
  group of `v` is bounded by attained values.
* `Valuation.IsEquiv.valueGroupOrderIso` : The order isomorphism of value groups induced by
  an equivalence of valuations, restricting Mathlib's `orderMonoidIso` to the unit groups.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, 4.13, Lemma 7.1, Lemma 7.4

The statements are adapted from the AINTLIB development (Apache 2.0), files
`projects/AdicSpaces/Adic spaces/SpvAI.lean` (the cofinal-value cluster) and
`projects/AdicSpaces/Adic spaces/CharacteristicSubgroup.lean` (the characteristic-group
cluster), reformulated on the value group.
-/

public section

namespace TauCeti.Valuation

open MonoidWithZeroHom

variable {A : Type*} [Ring A] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
  {Γ₀' : Type*} [LinearOrderedCommGroupWithZero Γ₀']

/-! ### Cofinal values -/

/-- A value `v a` is **cofinal** if for every positive `γ` in the value group of `v` some
power `(v a) ^ n` lies strictly below `γ` (Wedhorn Lemma 7.1: the condition satisfied by
the elements of an ideal of definition). -/
def CofinalValue (v : Valuation A Γ₀) (a : A) : Prop :=
  ∀ γ : ValueGroup₀ (.ofClass v), 0 < γ → ∃ n : ℕ, v.restrict a ^ n < γ

/-- The defining property of a cofinal value, on the value group of `v`. -/
@[simp]
theorem cofinalValue_iff {v : Valuation A Γ₀} {a : A} :
    CofinalValue v a ↔ ∀ γ : ValueGroup₀ (.ofClass v), 0 < γ → ∃ n : ℕ, v.restrict a ^ n < γ :=
  Iff.rfl

/-- A cofinal value is at most `1`: otherwise its powers stay above `1`. -/
theorem CofinalValue.le_one {v : Valuation A Γ₀} {a : A} (h : CofinalValue v a) :
    v a ≤ 1 := by
  by_contra h_gt
  push Not at h_gt
  have h_res : 1 < v.restrict a := by
    have := (v.restrict_lt_iff (x := 1) (y := a)).mpr (by simpa using h_gt)
    simpa using this
  obtain ⟨n, hn⟩ := h 1 zero_lt_one
  exact absurd hn (not_lt_of_ge (one_le_pow_of_one_le' h_res.le n))

/-- Cofinality is downward closed in the value: a smaller value is cofinal whenever a
larger one is (Wedhorn Lemma 7.1). -/
theorem CofinalValue.of_le {v : Valuation A Γ₀} {a b : A} (h : CofinalValue v a)
    (hba : v b ≤ v a) : CofinalValue v b := fun γ hγ ↦
  let ⟨n, hn⟩ := h γ hγ
  ⟨n, lt_of_le_of_lt (pow_le_pow_left' (v.restrict_le_iff.mpr hba) n) hn⟩

/-- Cofinality transports along an equivalence of valuations, through the ordered
isomorphism of their value groups. -/
theorem CofinalValue.of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) {a : A} (hv : CofinalValue v a) : CofinalValue w a := by
  intro γ hγ
  obtain ⟨n, hn⟩ := hv (h.orderMonoidIso.symm γ)
    (zero_lt_iff.mpr fun heq ↦ hγ.ne' (by simpa using congrArg h.orderMonoidIso heq))
  refine ⟨n, ?_⟩
  have := (map_lt_map_iff h.orderMonoidIso).mpr hn
  rw [map_pow, Valuation.IsEquiv.orderMonoidIso_spec] at this
  simpa using this

/-- Cofinality is invariant under valuation equivalence. -/
theorem _root_.Valuation.IsEquiv.cofinalValue_iff {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) {a : A} :
    CofinalValue v a ↔ CofinalValue w a :=
  ⟨fun hv ↦ hv.of_isEquiv h, fun hw ↦ hw.of_isEquiv h.symm⟩

/-! ### The full-characteristic-group condition -/

/-- A valuation **has full characteristic group** if every positive element of its value
group is bounded between `(v a)⁻¹` and `v a` for some `a` — the elementwise form of
"`Γ_v = cΓ_v`", for the characteristic subgroup `cΓ_v` of Wedhorn 4.13. Such a witness
automatically satisfies `1 ≤ v.restrict a`, since the two bounds force `x⁻¹ ≤ x`. This is
the second disjunct of Wedhorn Lemma 7.4(ii); it is weaker than the *microbial* condition
of Wedhorn Definition 5.46 (on a field it holds for every valuation). -/
def HasFullCharacteristicGroup (v : Valuation A Γ₀) : Prop :=
  ∀ γ : ValueGroup₀ (.ofClass v), 0 < γ →
    ∃ a : A, (v.restrict a)⁻¹ ≤ γ ∧ γ ≤ v.restrict a

/-- The defining property of the full-characteristic-group condition. -/
@[simp]
theorem hasFullCharacteristicGroup_iff {v : Valuation A Γ₀} :
    HasFullCharacteristicGroup v ↔
      ∀ γ : ValueGroup₀ (.ofClass v), 0 < γ →
        ∃ a : A, (v.restrict a)⁻¹ ≤ γ ∧ γ ≤ v.restrict a :=
  Iff.rfl

/-- A bounding witness is automatically at least `1`: the two bounds force
`x⁻¹ ≤ x` at a positive element. -/
private theorem one_le_of_inv_le_of_le {v : Valuation A Γ₀}
    {x γ : ValueGroup₀ (.ofClass v)} (hγ : 0 < γ)
    (h1 : x⁻¹ ≤ γ) (h2 : γ ≤ x) : 1 ≤ x := by
  by_contra hx
  push Not at hx
  have hx0 : 0 < x := hγ.trans_le h2
  have h3 : (1 : ValueGroup₀ (.ofClass v)) < x⁻¹ := (one_lt_inv₀ hx0).mpr hx
  exact absurd ((h1.trans h2).trans hx.le) (not_le.mpr h3)

/-- Strengthened elimination: a bounding witness for a positive `γ` can be taken with
`1 ≤ v.restrict a` alongside the two bounds. -/
theorem HasFullCharacteristicGroup.exists_one_le {v : Valuation A Γ₀}
    (h : HasFullCharacteristicGroup v) {γ : ValueGroup₀ (.ofClass v)} (hγ : 0 < γ) :
    ∃ a : A, 1 ≤ v.restrict a ∧ (v.restrict a)⁻¹ ≤ γ ∧ γ ≤ v.restrict a := by
  obtain ⟨a, h1, h2⟩ := h γ hγ
  exact ⟨a, one_le_of_inv_le_of_le hγ h1 h2, h1, h2⟩

/-- The full-characteristic-group condition transports along an equivalence of
valuations, through the ordered isomorphism of their value groups. -/
theorem HasFullCharacteristicGroup.of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) (hv : HasFullCharacteristicGroup v) : HasFullCharacteristicGroup w := by
  intro γ hγ
  obtain ⟨a, ha_lo, ha_hi⟩ := hv (h.orderMonoidIso.symm γ)
    (zero_lt_iff.mpr fun heq ↦ hγ.ne' (by simpa using congrArg h.orderMonoidIso heq))
  refine ⟨a, ?_, ?_⟩
  · have := (map_le_map_iff h.orderMonoidIso).mpr ha_lo
    rw [map_inv₀, Valuation.IsEquiv.orderMonoidIso_spec] at this
    simpa using this
  · have := (map_le_map_iff h.orderMonoidIso).mpr ha_hi
    rw [Valuation.IsEquiv.orderMonoidIso_spec] at this
    simpa using this

/-- The full-characteristic-group condition is invariant under valuation equivalence. -/
theorem _root_.Valuation.IsEquiv.hasFullCharacteristicGroup_iff {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) :
    HasFullCharacteristicGroup v ↔ HasFullCharacteristicGroup w :=
  ⟨fun hv ↦ hv.of_isEquiv h, fun hw ↦ hw.of_isEquiv h.symm⟩

/-- Under the full-characteristic-group condition, every positive element of the value
group dominates the inverse of some nonzero value: the existence statement used in the
`Γ_v = cΓ_v` case of Wedhorn Lemma 7.10. -/
theorem HasFullCharacteristicGroup.exists_inv_le {v : Valuation A Γ₀}
    (h : HasFullCharacteristicGroup v)
    {γ : ValueGroup₀ (.ofClass v)} (hγ : 0 < γ) :
    ∃ t : A, v.restrict t ≠ 0 ∧ (v.restrict t)⁻¹ ≤ γ := by
  obtain ⟨a, ha_inv_le, ha_le⟩ := h γ hγ
  exact ⟨a, (hγ.trans_le ha_le).ne', ha_inv_le⟩

/-! ### The characteristic subgroup -/

/-- The generators of the characteristic subgroup `cΓ_v` of Wedhorn 4.13: the values `≥ 1`
attained by `v`, as elements of the value group (Mathlib's `valueGroup.mk f r s`
represents `(f r)⁻¹ * f s`, so `valueGroup.mk (.ofClass v) 1 a` is the value `v a`). -/
def characteristicGenerators (v : Valuation A Γ₀) : Set (valueGroup (.ofClass v)) :=
  {γ | 1 ≤ γ ∧ ∃ a : A, v.restrict a = (γ : ValueGroup₀ (.ofClass v))}

/-- Membership in the generating set: the attained values `≥ 1`, in the `v.restrict` form
consumers hold. -/
@[simp]
theorem mem_characteristicGenerators {v : Valuation A Γ₀} {γ : valueGroup (.ofClass v)} :
    γ ∈ characteristicGenerators v ↔
      1 ≤ γ ∧ ∃ a : A, v.restrict a = (γ : ValueGroup₀ (.ofClass v)) :=
  Iff.rfl

/-- The **characteristic subgroup** `cΓ_v` of Wedhorn 4.13: the smallest convex subgroup of
the value group containing the values `≥ 1` attained by `v`. -/
noncomputable def characteristicSubgroup (v : Valuation A Γ₀) :
    TauCeti.ConvexSubgroup (valueGroup (.ofClass v)) :=
  TauCeti.ConvexSubgroup.closure (characteristicGenerators v)

/-- Universal property: `cΓ_v` lies inside a convex subgroup exactly when the attained
values `≥ 1` do. -/
@[simp]
theorem characteristicSubgroup_le_iff {v : Valuation A Γ₀}
    {H : TauCeti.ConvexSubgroup (valueGroup (.ofClass v))} :
    characteristicSubgroup v ≤ H ↔ characteristicGenerators v ⊆ H :=
  TauCeti.ConvexSubgroup.closure_le

/-- The generators lie in the characteristic subgroup they generate. -/
theorem characteristicGenerators_subset_characteristicSubgroup (v : Valuation A Γ₀) :
    characteristicGenerators v ⊆ characteristicSubgroup v :=
  TauCeti.ConvexSubgroup.subset_closure _

/-- **Introduction rule.** An attained value `≥ 1` lies in the characteristic subgroup,
stated for the ordinary restricted value. -/
theorem mem_characteristicSubgroup_of_restrict {v : Valuation A Γ₀} {a : A}
    {γ : valueGroup (.ofClass v)} (h1 : 1 ≤ γ)
    (ha : v.restrict a = (γ : ValueGroup₀ (.ofClass v))) :
    γ ∈ characteristicSubgroup v :=
  characteristicGenerators_subset_characteristicSubgroup v ⟨h1, a, ha⟩

/-- The `valueGroup.mk` restatement of the introduction rule, for consumers already holding
a representation of the value. -/
theorem valueGroup_mk_mem_characteristicSubgroup_of_one_le {v : Valuation A Γ₀} {a : A}
    (h : (MonoidWithZeroHom.ofClass v) a ≠ 0)
    (h1 : 1 ≤ valueGroup.mk (.ofClass v) 1 a (by simp) h) :
    valueGroup.mk (.ofClass v) 1 a (by simp) h ∈ characteristicSubgroup v :=
  mem_characteristicSubgroup_of_restrict h1 (v.restrict_eq_mk h)

/-! ### Transport along valuation equivalence -/

/-- The order isomorphism of **value groups** induced by an equivalence of valuations.
Mathlib's `IsEquiv.orderMonoidIso` is an isomorphism of the value monoids *with zero*, and
`ValueGroup₀ f = WithZero ↥(valueGroup f)`, so this is exactly the inverse of Mathlib's
`OrderMonoidIso.withZero`, which identifies order isomorphisms of two groups with those of
the groups with zero adjoined. -/
noncomputable def _root_.Valuation.IsEquiv.valueGroupOrderIso {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) :
    valueGroup (.ofClass v) ≃*o valueGroup (.ofClass w) :=
  OrderMonoidIso.withZero.symm h.orderMonoidIso

/-- The induced value-group isomorphism agrees with `orderMonoidIso` under the coercion. -/
@[simp]
theorem _root_.Valuation.IsEquiv.valueGroupOrderIso_coe {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) (γ : valueGroup (.ofClass v)) :
    ((h.valueGroupOrderIso γ : valueGroup (.ofClass w)) : ValueGroup₀ (.ofClass w))
      = h.orderMonoidIso (γ : ValueGroup₀ (.ofClass v)) :=
  (rfl)

/-- Equivalent valuations have corresponding characteristic generators. -/
theorem characteristicGenerators_map_of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) {γ : valueGroup (.ofClass v)} (hγ : γ ∈ characteristicGenerators v) :
    h.valueGroupOrderIso γ ∈ characteristicGenerators w := by
  obtain ⟨h1, a, ha⟩ := hγ
  refine ⟨?_, a, ?_⟩
  · simpa using h.valueGroupOrderIso.map_le_map_iff'.mpr h1
  · rw [h.valueGroupOrderIso_coe, ← ha, h.orderMonoidIso_spec]

/-- **Invariance under valuation equivalence.** The characteristic subgroup is carried into
the characteristic subgroup by the induced value-group isomorphism. Applying this to `h.symm`
gives the converse inclusion, so `cΓ_v` is a genuine invariant of the equivalence class and
may be used on points of the valuation spectrum. -/
theorem characteristicSubgroup_le_comap_of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) :
    characteristicSubgroup v ≤
      TauCeti.ConvexSubgroup.comap h.valueGroupOrderIso (characteristicSubgroup w) := by
  rw [characteristicSubgroup_le_iff]
  intro γ hγ
  exact TauCeti.ConvexSubgroup.mem_comap.mpr
    (characteristicGenerators_subset_characteristicSubgroup w
      (characteristicGenerators_map_of_isEquiv h hγ))

/-- Membership form of the invariance. -/
theorem mem_characteristicSubgroup_of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) {γ : valueGroup (.ofClass v)} (hγ : γ ∈ characteristicSubgroup v) :
    h.valueGroupOrderIso γ ∈ characteristicSubgroup w :=
  TauCeti.ConvexSubgroup.mem_comap.mp (characteristicSubgroup_le_comap_of_isEquiv h hγ)

end TauCeti.Valuation
