/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Valuation.Coarsen

/-!
# Microbial valuations

Wedhorn's Definition 5.46(v) calls a valuation *microbial* when some convex subgroup of its value
group has height-one quotient. This module records that condition and connects it to the
coarsening `Valuation.coarsenByUnits`, which is the vertical generization `v/H` of
Wedhorn's Remark 4.12(1): the subgroup a microbial valuation supplies is exactly the one to
coarsen by.

## Height one, without a height theory

"Height one" is not formalised as a number. A linearly ordered commutative group has height at
most one exactly when its only convex subgroups are `⊥` and `⊤`, and that is
`TauCeti.ConvexSubgroup.mulArchimedean_iff_forall_eq_bot_or_eq_top`; height *exactly* one adds
that the group is not trivial. So `MulArchimedean` together with `Nontrivial` is the height-one
condition, and no rank or height development is needed.

## Main definitions

* `Valuation.IsMicrobial` : Wedhorn 5.46(v), as a condition on the value monoid.

## Main results

* `Valuation.IsMicrobial.exists_coarsenByUnits` : over a microbial value monoid every
  valuation admits a vertical generization whose value units have height one — the subgroup handed
  over by the definition is the one `coarsenByUnits` consumes.

## Implementation notes

Declared in the root `Valuation` namespace, not in `TauCeti.Valuation`, matching
`TauCeti/RingTheory/Valuation/Coarsen.lean`. `Valuation` is a Mathlib type, so nesting it under
`TauCeti` shadows it and dot-notation on a valuation stops elaborating; the repository's
dot-notation guard rejects that.

The condition is stated over `Γ₀ˣ`, the units of the valuation's value monoid, rather than over
Wedhorn's `Γ_v = valueGroup (.ofClass v)`. That is what makes the witness directly usable:
`Valuation.coarsenByUnits` is indexed by `ConvexSubgroup Γ₀ˣ`, so the subgroup the definition
supplies is the one the coarsening takes, with no transport in between. Over a valuation whose
value monoid is generated by its values the two readings agree; where they do not, this is the
weaker condition, and a `Γ_v`-indexed variant would need the transport in
`TauCeti/RingTheory/Valuation/ValueGroupTransport.lean`.

The *characteristic* subgroup `cΓ_v` of Wedhorn 4.13 is a different notion and lives in
`TauCeti/RingTheory/Valuation/CharacteristicGroup.lean`, which says so explicitly.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Definition 5.46(v) and
  Remark 4.12(1).
-/

public section

namespace Valuation

open TauCeti

variable {R : Type*} [Ring R] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]

/-- **Wedhorn Definition 5.46(v)**, read on the value monoid: `Γ₀` is *microbial* when there is a
convex subgroup `H` of its units whose quotient has height one — nontrivial, and archimedean in
the sense that `⊥` and `⊤` are its only convex subgroups.

Stated of `Γ₀` rather than of a valuation because that is what it depends on: no valuation appears
in the condition. A valuation is microbial exactly when its value monoid is. -/
def IsMicrobial (Γ₀ : Type*) [LinearOrderedCommGroupWithZero Γ₀] : Prop :=
  ∃ H : ConvexSubgroup Γ₀ˣ,
    Nontrivial (Γ₀ˣ ⧸ H.toSubgroup) ∧ MulArchimedean (Γ₀ˣ ⧸ H.toSubgroup)

/-- **Over a microbial value monoid every valuation has a height-one vertical generization.** The
convex subgroup the definition supplies is exactly the one to coarsen by, so the generization is
`v.coarsenByUnits H` — Wedhorn's `v/H` of Remark 4.12(1) — and its value units are
`Γ₀ˣ ⧸ H.toSubgroup`, which the definition makes nontrivial and archimedean. -/
theorem IsMicrobial.exists_coarsenByUnits (h : IsMicrobial Γ₀) (v : Valuation R Γ₀) :
    ∃ (H : ConvexSubgroup Γ₀ˣ) (w : Valuation R (WithZero (Γ₀ˣ ⧸ H.toSubgroup))),
      w = v.coarsenByUnits H ∧ Nontrivial (Γ₀ˣ ⧸ H.toSubgroup) ∧
        MulArchimedean (Γ₀ˣ ⧸ H.toSubgroup) :=
  h.imp fun H hH => ⟨v.coarsenByUnits H, rfl, hH.1, hH.2⟩

end Valuation
