/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.Algebra.GroupWithZero.Range
public import Mathlib.RingTheory.Valuation.Basic

/-!
# Cofinal values and microbial valuations

Two conditions on the values of a valuation `v : Valuation A Γ₀` that control continuity
in the adic theory, following Wedhorn, *Adic Spaces* (arXiv:1910.05934v1), §4.3 and §7.1.
Both quantify over the **value group** `Γ_v` of `v` — the subgroup of `Γ₀ˣ` generated by
the nonzero values, `MonoidWithZeroHom.valueGroup (.ofClass v)` — not over the ambient
codomain, so they are invariant under enlarging `Γ₀`:

* a value `v a` is *cofinal* if its powers fall below every element of the value group —
  the condition on ideals of definition in Wedhorn Lemma 7.1;
* `v` is *microbial* if every element of the value group is bounded between `(v a)⁻¹` and
  `v a` for some `a` with `1 ≤ v a` — the elementwise reading of "the characteristic
  subgroup `cΓ_v` of Wedhorn 4.13 is the whole value group".

These are the two disjuncts of the membership criterion for `Spv (A, I)` in Wedhorn
Lemma 7.4, formalised with no topology on `A`.

## Main definitions

* `TauCeti.Valuation.CofinalValue v a` : Powers of `v a` fall below every element of the
  value group of `v`.
* `TauCeti.Valuation.IsMicrobial v` : Every element of the value group of `v` is bounded
  by attained values.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, 4.13, Lemma 7.1, Lemma 7.4

The statements are adapted from the AINTLIB development (Apache 2.0), files
`projects/AdicSpaces/Adic spaces/SpvAI.lean` (the cofinal-value cluster) and
`projects/AdicSpaces/Adic spaces/CharacteristicSubgroup.lean` (the microbial cluster),
requantified over the value group.
-/

public section

namespace TauCeti.Valuation

open MonoidWithZeroHom

/-! ### Cofinal values -/

section CofinalValue

variable {A : Type*} [Ring A] {Γ₀ : Type*} [LinearOrderedCommMonoidWithZero Γ₀]

/-- A value `v a` is **cofinal** if for every `γ` in the value group of `v` some power
`(v a) ^ n` lies strictly below `γ` (Wedhorn Lemma 7.1: the condition satisfied by the
elements of an ideal of definition). -/
def CofinalValue (v : Valuation A Γ₀) (a : A) : Prop :=
  ∀ γ ∈ valueGroup (.ofClass v), ∃ n : ℕ, v a ^ n < (γ : Γ₀ˣ)

/-- The defining property of a cofinal value, stated on value-group elements. -/
theorem cofinalValue_iff {v : Valuation A Γ₀} {a : A} :
    CofinalValue v a ↔ ∀ γ ∈ valueGroup (.ofClass v), ∃ n : ℕ, v a ^ n < (γ : Γ₀ˣ) :=
  Iff.rfl

/-- A cofinal value is at most `1`: otherwise its powers stay above `1`. -/
theorem CofinalValue.le_one {v : Valuation A Γ₀} {a : A} (h : CofinalValue v a) :
    v a ≤ 1 := by
  by_contra h_gt
  push Not at h_gt
  obtain ⟨n, hn⟩ := h 1 (one_mem _)
  exact absurd hn (by simpa using not_lt_of_ge (one_le_pow_of_one_le' h_gt.le n))

/-- Cofinality is downward closed in the value: a smaller value is cofinal whenever a
larger one is (Wedhorn Lemma 7.1). -/
theorem CofinalValue.of_le {v : Valuation A Γ₀} {a b : A} (h : CofinalValue v a)
    (hba : v b ≤ v a) : CofinalValue v b := fun γ hγ ↦
  let ⟨n, hn⟩ := h γ hγ
  ⟨n, lt_of_le_of_lt (pow_le_pow_left' hba n) hn⟩

end CofinalValue

/-! ### Microbial valuations -/

section IsMicrobial

variable {A : Type*} [Ring A] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]

/-- A valuation is **microbial** if every element of its value group is bounded between
`(v a)⁻¹` and `v a` for some `a` with `1 ≤ v a` — the elementwise form of "the
characteristic subgroup `cΓ_v` of Wedhorn 4.13 is the whole value group" (see the
discussion around Wedhorn Lemma 7.4). -/
def IsMicrobial (v : Valuation A Γ₀) : Prop :=
  ∀ γ ∈ valueGroup (.ofClass v), ∃ a : A, 1 ≤ v a ∧ (v a)⁻¹ ≤ (γ : Γ₀ˣ) ∧ (γ : Γ₀ˣ) ≤ v a

/-- The defining property of a microbial valuation, stated on value-group elements. -/
theorem isMicrobial_iff {v : Valuation A Γ₀} :
    IsMicrobial v ↔
      ∀ γ ∈ valueGroup (.ofClass v),
        ∃ a : A, 1 ≤ v a ∧ (v a)⁻¹ ≤ (γ : Γ₀ˣ) ∧ (γ : Γ₀ˣ) ≤ v a :=
  Iff.rfl

/-- For a microbial valuation, every element of the value group is dominated by the
inverse of some nonzero value: the existence statement used in the microbial case of
Wedhorn Lemma 7.10. -/
theorem IsMicrobial.exists_inv_le {v : Valuation A Γ₀} (h : IsMicrobial v) {γ : Γ₀ˣ}
    (hγ : γ ∈ valueGroup (.ofClass v)) : ∃ t : A, v t ≠ 0 ∧ (v t)⁻¹ ≤ (γ : Γ₀ˣ) := by
  obtain ⟨a, ha_ge_one, ha_inv_le, -⟩ := h γ hγ
  exact ⟨a, (zero_lt_one.trans_le ha_ge_one).ne', ha_inv_le⟩

end IsMicrobial

end TauCeti.Valuation
