/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

-- `Subgroup.prod` and `Subgroup.mem_prod` occur in the statement and its proof.
public import Mathlib.Algebra.Group.Subgroup.Basic
-- `Subgroup.zpowers` and `Subgroup.mem_zpowers_iff` describe the cyclic subgroup.
public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
-- `orderOf_dvd_iff_zpow_eq_one` converts between order divisibility and a power being trivial.
public import Mathlib.GroupTheory.OrderOfElement

/-!
# A cyclic subgroup of a product meeting the first factor trivially

The cyclic subgroup generated by a pair `(σ, τ)` in a product `G × H` meets the subgroup
`G × 1` trivially as soon as the order of `σ` divides the order of `τ`.  The reason is that a
power `(σ, τ) ^ k` lies in `G × 1` exactly when `τ ^ k = 1`, which forces `orderOf τ ∣ k` and
hence `orderOf σ ∣ k`, so the first coordinate is trivial too.

The divisibility hypothesis is the whole content: without it the two factors can conspire, as
`(σ, τ)` of order `orderOf σ` with `τ = 1` shows.

## Main results

* `Subgroup.zpowers_inf_prod_bot_of_orderOf_dvd`: `⟨(σ, τ)⟩ ⊓ (⊤ × ⊥) = ⊥` when
  `orderOf σ ∣ orderOf τ`.
-/

public section

namespace Subgroup

variable {G H : Type*} [Group G] [Group H]

/-- The cyclic subgroup generated by `(σ, τ)` meets `G × 1` trivially when the order of `σ`
divides the order of `τ`: a power of `(σ, τ)` landing in `G × 1` kills `τ`, hence kills `σ`.

No finiteness is needed.  When `τ` has infinite order the hypothesis forces `orderOf σ = 0` as
well, and both sides of the divisibility read `0`. -/
theorem zpowers_inf_prod_bot_of_orderOf_dvd (σ : G) (τ : H)
    (hστ : orderOf σ ∣ orderOf τ) :
    zpowers ((σ, τ) : G × H) ⊓ (⊤ : Subgroup G).prod (⊥ : Subgroup H) = ⊥ := by
  rw [eq_bot_iff]
  rintro ⟨g, h⟩ hmem
  rw [mem_inf, mem_prod, mem_bot] at hmem
  obtain ⟨⟨k, hk⟩, -, (hh : h = 1)⟩ := hmem
  have hτ : τ ^ k = 1 := by simpa [hh] using congrArg Prod.snd hk
  have hσ : σ ^ k = 1 :=
    orderOf_dvd_iff_zpow_eq_one.mp (hστ.natCast.trans (orderOf_dvd_iff_zpow_eq_one.mpr hτ))
  rw [mem_bot, Prod.mk_eq_one]
  exact ⟨by simpa [hσ] using (congrArg Prod.fst hk).symm, hh⟩

end Subgroup
