/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.Restricted.Flat
public import TauCeti.RingTheory.Flat.QuotientRegular
import Mathlib.RingTheory.Flat.Tensor

/-!
# The Laurent quotients `A⟨X⟩/(f - X)` and `A⟨X⟩/(1 - f X)` are flat

Wedhorn's Lemma 8.31(2): for a complete noetherian Tate ring `A` and `f ∈ A`, the rings
`A⟨X⟩/(f - X)` and `A⟨X⟩/(1 - f X)` are flat over `A`. They are the coordinate rings of the
Laurent rational subsets `{|f| ≤ 1}` and `{|f| ≥ 1}` of `Spa A` (Wedhorn, Example 6.38), which is
why Proposition 8.30 consumes them.

Wedhorn's proof: `A⟨X⟩/(g)` is flat as soon as multiplication by `g` is injective on `M⟨X⟩` for
every finitely generated `M` — the `Tor`-sequence claim that is
`Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective` — and for `g = 1 - f X` and
`g = f - X` that injectivity is a computation on the coefficients of `M⟨X⟩ = M ⊗[A] A⟨X⟩`
(Remark 8.29).

## Main results

* `TauCeti.Huber.flat_quotient_algebraMap_sub_restrictedX`: `A⟨X⟩/(f - X)` is flat over `A`.
* `TauCeti.Huber.flat_quotient_one_sub_algebraMap_mul_restrictedX`: `A⟨X⟩/(1 - f X)` is flat
  over `A`.
* `TauCeti.Huber.xShift`: multiplication by `X` on series with coefficients in a module, as the
  coefficient shift; `TauCeti.Huber.restrictedXShift` is its restriction to `M⟨X⟩`.

## Implementation notes

The comparison map intertwines `X • ·` on `M ⊗[A] A⟨X⟩` with the coefficient shift on `M⟨X⟩`
(`restrictedMvPowerSeriesBaseChange_comp_lTensor_mulLeft_restrictedX`), and scalars act as
scalars (`lTensor_mulLeft_algebraMap`). So `(1 - f X) • ·` and `(f - X) • ·` on `M ⊗[A] A⟨X⟩`
are `id - f • xShift` and `f • id - xShift` on coefficients. The first is injective by induction
on the coefficient index. The second is Wedhorn's argument: if `f • s = X s` then `f • s₀ = 0`
and `f • sⱼ₊₁ = sⱼ`, so every coefficient is a power of `f` times a later one; the chain of
submodules spanned by the initial coefficients stabilises because `M` is noetherian, the
stabilised submodule is generated by a single coefficient `sₗ`, and
`sₗ = f ^ (l + 1) • s₂ₗ₊₁ = a • f ^ (l + 1) • sₗ = 0`. Both are transported through the injective
comparison map to `(A ⧸ I) ⊗[A] A⟨X⟩`, which is what Mathlib's ideal criterion, through
`Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective`, asks for. No topology enters
beyond the module topology of `A ⧸ I` (`IsModuleTopology.instQuot`).

Exponents of one-variable series are identified with `ℕ` through `expEquiv`; the shift is
stated on `MvPowerSeries (Fin 1) M`, with no topology, and restricted afterwards.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Lemma 8.31 and Example 6.38.
-/

open Filter Topology
open scoped Uniformity

public section

namespace TauCeti.Huber
/-! ### One variable: the coefficient shift -/

section Shift

variable {A : Type*} [CommRing A]

/-- Exponents of one-variable series are natural numbers: `n ↦ n 0`, inverse `j ↦ single 0 j`. -/
private noncomputable def expEquiv : (Fin 1 →₀ ℕ) ≃ ℕ :=
  Finsupp.equivFunOnFinite.trans (Equiv.funUnique (Fin 1) ℕ)

@[simp] private theorem expEquiv_apply (n : Fin 1 →₀ ℕ) : expEquiv n = n 0 := (rfl)

@[simp] private theorem expEquiv_symm_apply (j : ℕ) : expEquiv.symm j = Finsupp.single 0 j :=
  Finsupp.unique_single (expEquiv.symm j)

variable {M : Type*} [AddCommGroup M] [Module A M]

variable (A) in
/-- **Multiplication by `X` on series with coefficients in a module**: the coefficient shift
`∑ mⱼ Xʲ ↦ ∑ mⱼ Xʲ⁺¹`. This is what `X • ·` on `M⟨X⟩ = M ⊗[A] A⟨X⟩` looks like on coefficients
(`restrictedMvPowerSeriesBaseChange_tmul_restrictedX_mul`). -/
noncomputable def xShift : MvPowerSeries (Fin 1) M →ₗ[A] MvPowerSeries (Fin 1) M where
  -- `MvPowerSeries (Fin 1) M` unfolds to the coefficient function type, but only
  -- definitionally; the ascription is what lets the lambda below elaborate against it.
  toFun s := show (Fin 1 →₀ ℕ) → M from
    fun n ↦ if n 0 = 0 then 0 else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))
  map_add' s t := by
    funext n
    -- Present the goal in `xShift`'s defining if-then-else form so `split_ifs` can fire. This
    -- is a definitional unfolding of the structure field, not an equation, so there is no
    -- lemma for `rw` to use; `change` is the step.
    change (if n 0 = 0 then (0 : M) else (s + t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))) =
      (if n 0 = 0 then (0 : M) else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))) +
        (if n 0 = 0 then (0 : M) else (t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1)))
    split_ifs
    · simp
    · rfl
  map_smul' a s := by
    funext n
    -- Same definitional unfolding as in `map_add'`.
    change (if n 0 = 0 then (0 : M) else (a • s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))) =
      a • (if n 0 = 0 then (0 : M) else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1)))
    split_ifs
    · simp
    · rfl

/-- The coefficients of `xShift A s`: it vanishes in degree `0`, and in every other
degree it takes the coefficient of `s` one degree down. -/
@[simp]
theorem xShift_apply (s : MvPowerSeries (Fin 1) M) (n : Fin 1 →₀ ℕ) :
    (xShift A s : (Fin 1 →₀ ℕ) → M) n =
      if n 0 = 0 then 0 else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1)) := (rfl)

/-- `xShift A s` has no constant term.

Not `@[simp]`: the general equation `xShift_apply` above is `@[simp]` and rewrites this
left-hand side first, so annotating the degree-`0` specialisation too would leave it out of
simp normal form. `simp` proves this statement on its own. -/
theorem xShift_apply_zero (s : MvPowerSeries (Fin 1) M) :
    (xShift A s : (Fin 1 →₀ ℕ) → M) 0 = 0 := by
  simp [xShift_apply]

/-- In degree `j + 1`, `xShift A s` takes the degree-`j` coefficient of `s`.

Deliberately not `@[simp]`: `Finsupp.single 0 (j + 1)` is not in simp normal form, since
`Finsupp.single_add` rewrites it to `Finsupp.single 0 j + Finsupp.single 0 1`, so the
annotation could never fire. The uses in this file rewrite with it explicitly. -/
theorem xShift_apply_single_succ (s : MvPowerSeries (Fin 1) M) (j : ℕ) :
    (xShift A s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (j + 1)) =
      (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) := by
  simp [xShift_apply]

/-- The shift preserves restrictedness: it reindexes the coefficients along `j ↦ j + 1`. -/
theorem IsRestricted.xShift [TopologicalSpace M] {s : MvPowerSeries (Fin 1) M}
    (hs : IsRestricted s) : IsRestricted (TauCeti.Huber.xShift A s) := by
  simp only [isRestricted_iff, Filter.ZeroAtFilter] at hs ⊢
  -- Move to sequences indexed by `ℕ` through `expEquiv`.
  have hs' : Tendsto (fun j : ℕ ↦ (s : (Fin 1 →₀ ℕ) → M) (expEquiv.symm j)) cofinite (nhds 0) :=
    hs.comp expEquiv.symm.injective.tendsto_cofinite
  have h2 : Tendsto (fun j : ℕ ↦ if j = 0 then (0 : M) else
      (s : (Fin 1 →₀ ℕ) → M) (expEquiv.symm (j - 1))) cofinite (nhds 0) := by
    rw [Nat.cofinite_eq_atTop] at hs' ⊢
    rw [← Filter.tendsto_add_atTop_iff_nat 1]
    simpa using hs'
  have key : (TauCeti.Huber.xShift A s : (Fin 1 →₀ ℕ) → M) =
      (fun j : ℕ ↦ if j = 0 then (0 : M) else (s : (Fin 1 →₀ ℕ) → M) (expEquiv.symm (j - 1))) ∘
        expEquiv := by
    funext n
    simp [xShift_apply]
  rw [key]
  exact h2.comp expEquiv.injective.tendsto_cofinite

end Shift

/-! ### Multiplication by `X` and by scalars, through the comparison map -/

section Compat

variable {A : Type*} [CommRing A] [TopologicalSpace A] [NonarchimedeanRing A]

/-- The variable `X` of `A⟨X⟩`, as an element of the restricted subring. -/
noncomputable def restrictedX : restrictedMvPowerSeriesSubring 1 A :=
  ⟨MvPowerSeries.X 0, mem_restrictedMvPowerSeriesSubring.mpr <| by
    rw [MvPowerSeries.X_def]
    exact isRestricted_monomial _ _⟩

/-- `restrictedX` is the power series `X` underneath. -/
@[simp]
theorem coe_restrictedX :
    ((restrictedX : restrictedMvPowerSeriesSubring 1 A) : MvPowerSeries (Fin 1) A) =
      MvPowerSeries.X 0 := (rfl)

variable {M : Type*} [AddCommGroup M] [Module A M] [TopologicalSpace M] [ContinuousAdd M]
  [ContinuousSMul A M]

/-- The coefficient shift on `M⟨X⟩`. -/
noncomputable def restrictedXShift :
    restrictedMvPowerSeriesSubmodule 1 A M →ₗ[A] restrictedMvPowerSeriesSubmodule 1 A M :=
  (xShift A).restrict fun _ hs ↦ mem_restrictedMvPowerSeriesSubmodule.mpr
    (mem_restrictedMvPowerSeriesSubmodule.mp hs).xShift

omit [NonarchimedeanRing A] in
/-- `restrictedXShift` acts as `xShift` on the underlying series. -/
@[simp]
theorem coe_restrictedXShift (s : restrictedMvPowerSeriesSubmodule 1 A M) :
    ((restrictedXShift s : restrictedMvPowerSeriesSubmodule 1 A M) : MvPowerSeries (Fin 1) M) =
      xShift A (s : MvPowerSeries (Fin 1) M) := (rfl)

/-- On a pure tensor, multiplying the series factor by `X` shifts the coefficients of the
comparison map's value. -/
theorem restrictedMvPowerSeriesBaseChange_tmul_restrictedX_mul (m : M)
    (b : restrictedMvPowerSeriesSubring 1 A) :
    restrictedMvPowerSeriesBaseChange (TensorProduct.tmul A m (restrictedX * b)) =
      restrictedXShift (restrictedMvPowerSeriesBaseChange (TensorProduct.tmul A m b)) := by
  apply restrictedMvPowerSeriesSubmodule_ext
  intro n
  obtain ⟨j, rfl⟩ : ∃ j, n = Finsupp.single 0 j := ⟨n 0, Finsupp.unique_single n⟩
  rw [coeff_restrictedMvPowerSeriesBaseChange_tmul, coe_restrictedXShift, Subring.coe_mul,
    coe_restrictedX]
  cases j with
  | zero => rw [Finsupp.single_zero, xShift_apply_zero, MvPowerSeries.coeff_zero_X_mul, zero_smul]
  | succ j =>
    rw [xShift_apply_single_succ, coeff_restrictedMvPowerSeriesBaseChange_tmul,
      -- `Finsupp.single_add` splits `single 0 (1 + j)`, so the exponent is commuted in
      -- place here rather than in a separate step.
      show j + 1 = 1 + j from Nat.add_comm j 1, Finsupp.single_add, MvPowerSeries.X_def,
      MvPowerSeries.coeff_add_monomial_mul, one_mul]

/-- The comparison map intertwines `X • ·` on `M ⊗[A] A⟨X⟩` with the coefficient shift. -/
theorem restrictedMvPowerSeriesBaseChange_comp_lTensor_mulLeft_restrictedX :
    (restrictedMvPowerSeriesBaseChange : TensorProduct A M (restrictedMvPowerSeriesSubring 1 A)
        →ₗ[A] restrictedMvPowerSeriesSubmodule 1 A M) ∘ₗ
      LinearMap.lTensor M (LinearMap.mulLeft A restrictedX) =
    restrictedXShift ∘ₗ restrictedMvPowerSeriesBaseChange :=
  TensorProduct.ext' fun m b ↦ by
    simp only [LinearMap.comp_apply, LinearMap.lTensor_tmul, LinearMap.mulLeft_apply]
    exact restrictedMvPowerSeriesBaseChange_tmul_restrictedX_mul m b

omit [TopologicalSpace M] [ContinuousAdd M] [ContinuousSMul A M] in
/-- Multiplying the series factor by a scalar is the scalar action on the tensor product. -/
theorem lTensor_mulLeft_algebraMap (f : A) :
    LinearMap.lTensor M
        (LinearMap.mulLeft A (algebraMap A (restrictedMvPowerSeriesSubring 1 A) f)) =
      f • LinearMap.id :=
  TensorProduct.ext' fun m b ↦ by
    simp [LinearMap.lTensor_tmul, LinearMap.mulLeft_apply, ← Algebra.smul_def,
      TensorProduct.tmul_smul]

/-- Through the comparison map, `X • ·` on `M ⊗[A] A⟨X⟩` is the coefficient shift on `M⟨X⟩`. -/
theorem restrictedMvPowerSeriesBaseChange_lTensor_mulLeft_restrictedX
    (z : TensorProduct A M (restrictedMvPowerSeriesSubring 1 A)) :
    restrictedMvPowerSeriesBaseChange (LinearMap.lTensor M (LinearMap.mulLeft A restrictedX) z) =
      restrictedXShift (restrictedMvPowerSeriesBaseChange z) :=
  LinearMap.congr_fun restrictedMvPowerSeriesBaseChange_comp_lTensor_mulLeft_restrictedX z

omit [TopologicalSpace M] [ContinuousAdd M] [ContinuousSMul A M] in
/-- `(1 - f X) • ·` on `M ⊗[A] A⟨X⟩`, in terms of `X • ·`. -/
theorem lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX (f : A) :
    LinearMap.lTensor M (LinearMap.mulLeft A
        (1 - algebraMap A (restrictedMvPowerSeriesSubring 1 A) f * restrictedX)) =
      LinearMap.id - f • LinearMap.lTensor M (LinearMap.mulLeft A restrictedX) :=
  TensorProduct.ext' fun m b ↦ by
    simp [LinearMap.lTensor_tmul, LinearMap.mulLeft_apply, sub_mul, ← Algebra.smul_def,
      TensorProduct.tmul_sub, TensorProduct.tmul_smul]

omit [TopologicalSpace M] [ContinuousAdd M] [ContinuousSMul A M] in
/-- `(f - X) • ·` on `M ⊗[A] A⟨X⟩`, in terms of `X • ·`. -/
theorem lTensor_mulLeft_algebraMap_sub_restrictedX (f : A) :
    LinearMap.lTensor M (LinearMap.mulLeft A
        (algebraMap A (restrictedMvPowerSeriesSubring 1 A) f - restrictedX)) =
      f • LinearMap.id - LinearMap.lTensor M (LinearMap.mulLeft A restrictedX) :=
  TensorProduct.ext' fun m b ↦ by
    simp [LinearMap.lTensor_tmul, LinearMap.mulLeft_apply, sub_mul, ← Algebra.smul_def,
      TensorProduct.tmul_sub, TensorProduct.tmul_smul]

end Compat

/-! ### Regularity of `1 - f X` and of `f - X` on `M⟨X⟩` -/

section Regular

variable {A : Type*} [CommRing A] {M : Type*} [AddCommGroup M] [Module A M]

/-- **Multiplication by `1 - f X` is injective on series with coefficients in any module.** -/
theorem id_sub_smul_xShift_injective (f : A) :
    Function.Injective (LinearMap.id - f • xShift A : MvPowerSeries (Fin 1) M →ₗ[A] _) := by
  rw [injective_iff_map_eq_zero]
  intro s hs
  have hs' : s = f • xShift A s := by
    simpa [sub_eq_zero] using hs
  have hc : ∀ j, (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) =
      f • (xShift A s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) := fun j ↦
    congrArg (fun t : MvPowerSeries (Fin 1) M ↦ (t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j)) hs'
  have hzero : ∀ j, (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) = 0 := by
    intro j
    induction j with
    | zero => simpa using hc 0
    | succ j ih => rw [hc (j + 1), xShift_apply_single_succ, ih, smul_zero]
  -- Equality of one-variable series is definitionally equality of their coefficient
  -- functions, which is what `funext` needs to see.
  change (s : (Fin 1 →₀ ℕ) → M) = 0
  funext n
  rw [Finsupp.unique_single n]
  exact hzero _

/-- From `f • c (j + 1) = c j`, every term of the sequence is `f ^ i` times a later one. -/
private theorem eq_pow_smul_of_smul_succ {f : A} {c : ℕ → M} (hsucc : ∀ j, f • c (j + 1) = c j) :
    ∀ i j, c j = f ^ i • c (j + i) := by
  intro i
  induction i with
  | zero => simp
  | succ i ih =>
    intro j
    rw [ih j, ← Nat.add_assoc, ← hsucc (j + i), ← mul_smul, ← pow_succ]

/-- **A sequence in a noetherian module killed by `f` at the start and shifted back by `f` at
each step vanishes.** This is the noetherian stabilisation in Wedhorn's proof of Lemma 8.31(2):
the submodules spanned by the initial terms increase, so they stabilise at some `l`; then `c l`
generates all of them and is divisible by an arbitrarily large power of `f`, so it vanishes. -/
private theorem eq_zero_of_smul_eq_zero_of_smul_succ [IsNoetherian A M] {f : A} {c : ℕ → M}
    (h0 : f • c 0 = 0) (hsucc : ∀ j, f • c (j + 1) = c j) (j : ℕ) : c j = 0 := by
  have hshift := eq_pow_smul_of_smul_succ hsucc
  have hpow : ∀ j, f ^ (j + 1) • c j = 0 := by
    intro j
    induction j with
    | zero => simpa using h0
    | succ j ih => rw [pow_succ, mul_smul, hsucc, ih]
  let S : ℕ →o Submodule A M :=
    ⟨fun l ↦ Submodule.span A (c '' Set.Iic l), fun _ _ h ↦
      Submodule.span_mono (Set.image_mono (Set.Iic_subset_Iic.mpr h))⟩
  obtain ⟨l, hl⟩ := monotone_stabilizes_iff_noetherian.mpr ‹IsNoetherian A M› S
  have hmul : ∀ i ≤ l, c i = f ^ (l - i) • c l := fun i hi ↦ by
    have := hshift (l - i) i
    rwa [Nat.add_sub_cancel' hi] at this
  have hSl : S l ≤ Submodule.span A {c l} := Submodule.span_le.mpr <| by
    rintro _ ⟨i, hi, rfl⟩
    rw [hmul i hi]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  have hmem : c (2 * l + 1) ∈ Submodule.span A {c l} := hSl <| by
    rw [hl (2 * l + 1) (by omega)]
    exact Submodule.subset_span ⟨2 * l + 1, Set.mem_Iic.mpr le_rfl, rfl⟩
  obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp hmem
  have hcl : c l = 0 := by
    have h1 : c l = f ^ (l + 1) • c (2 * l + 1) := by
      have := hshift (l + 1) l
      rwa [show l + (l + 1) = 2 * l + 1 by ring] at this
    rw [h1, ← ha, smul_comm, hpow, smul_zero]
  rcases le_or_gt j l with hj | hj
  · rw [hmul j hj, hcl, smul_zero]
  · have hS0 : S l = ⊥ := Submodule.span_eq_bot.mpr <| by
      rintro _ ⟨i, hi, rfl⟩
      rw [hmul i hi, hcl, smul_zero]
    have hjS : c j ∈ S j := Submodule.subset_span ⟨j, Set.mem_Iic.mpr le_rfl, rfl⟩
    rw [← hl j hj.le, hS0] at hjS
    exact (Submodule.mem_bot A).mp hjS

/-- **Multiplication by `f - X` is injective on series with coefficients in a noetherian
module.** -/
theorem smul_id_sub_xShift_injective [IsNoetherian A M] (f : A) :
    Function.Injective (f • LinearMap.id - xShift A : MvPowerSeries (Fin 1) M →ₗ[A] _) := by
  rw [injective_iff_map_eq_zero]
  intro s hs
  have hs' : f • s = xShift A s := by
    simpa [sub_eq_zero] using hs
  have hrec : ∀ j, f • (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) =
      (xShift A s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) := fun j ↦
    congrArg (fun t : MvPowerSeries (Fin 1) M ↦ (t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j)) hs'
  have hall := eq_zero_of_smul_eq_zero_of_smul_succ
    (c := fun j ↦ (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j)) (by simpa using hrec 0)
    fun j ↦ by have := hrec (j + 1); rwa [xShift_apply_single_succ] at this
  -- Equality of one-variable series is definitionally equality of their coefficient
  -- functions, which is what `funext` needs to see.
  change (s : (Fin 1 →₀ ℕ) → M) = 0
  funext n
  rw [Finsupp.unique_single n]
  exact hall _

end Regular

/-! ### Lemma 8.31(2) -/

section Laurent

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [CompleteSpace A]
  [(𝓤 A).IsCountablyGenerated] [T0Space A] [NonarchimedeanRing A] [IsTateRing A]
  [IsNoetherianRing A]
  {N : Type*} [AddCommGroup N] [Module A N] [Module.Finite A N] [TopologicalSpace N]
  [ContinuousAdd N] [IsModuleTopology A N]

/-- `1 - f X` acts injectively on `N ⊗[A] A⟨X⟩` for a finite `N` with its module topology. -/
theorem lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX_injective (f : A) :
    Function.Injective (LinearMap.lTensor N (LinearMap.mulLeft A
      (1 - algebraMap A (restrictedMvPowerSeriesSubring 1 A) f * restrictedX))) := by
  rw [lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX, injective_iff_map_eq_zero]
  intro z hz
  have h := congrArg
    (fun w : restrictedMvPowerSeriesSubmodule 1 A N ↦ (w : MvPowerSeries (Fin 1) N))
    (congrArg restrictedMvPowerSeriesBaseChange hz)
  simp only [LinearMap.sub_apply, LinearMap.id_apply, LinearMap.smul_apply, map_sub, map_smul,
    restrictedMvPowerSeriesBaseChange_lTensor_mulLeft_restrictedX, map_zero,
    Submodule.coe_sub, Submodule.coe_smul, coe_restrictedXShift, Submodule.coe_zero] at h
  have h' : ((restrictedMvPowerSeriesBaseChange z : restrictedMvPowerSeriesSubmodule 1 A N) :
      MvPowerSeries (Fin 1) N) = 0 :=
    (injective_iff_map_eq_zero _).mp (id_sub_smul_xShift_injective f) _ (by simpa using h)
  exact (restrictedMvPowerSeriesBaseChange_bijective (k := 1) (A := A) (M := N)).injective
    (by rw [map_zero]; exact Subtype.ext h')

/-- `f - X` acts injectively on `N ⊗[A] A⟨X⟩` for a finite `N` with its module topology. -/
theorem lTensor_mulLeft_algebraMap_sub_restrictedX_injective (f : A) :
    Function.Injective (LinearMap.lTensor N (LinearMap.mulLeft A
      (algebraMap A (restrictedMvPowerSeriesSubring 1 A) f - restrictedX))) := by
  rw [lTensor_mulLeft_algebraMap_sub_restrictedX, injective_iff_map_eq_zero]
  intro z hz
  have h := congrArg
    (fun w : restrictedMvPowerSeriesSubmodule 1 A N ↦ (w : MvPowerSeries (Fin 1) N))
    (congrArg restrictedMvPowerSeriesBaseChange hz)
  simp only [LinearMap.sub_apply, LinearMap.id_apply, LinearMap.smul_apply, map_sub, map_smul,
    restrictedMvPowerSeriesBaseChange_lTensor_mulLeft_restrictedX, map_zero,
    Submodule.coe_sub, Submodule.coe_smul, coe_restrictedXShift, Submodule.coe_zero] at h
  have h' : ((restrictedMvPowerSeriesBaseChange z : restrictedMvPowerSeriesSubmodule 1 A N) :
      MvPowerSeries (Fin 1) N) = 0 :=
    (injective_iff_map_eq_zero _).mp (smul_id_sub_xShift_injective f) _ (by simpa using h)
  exact (restrictedMvPowerSeriesBaseChange_bijective (k := 1) (A := A) (M := N)).injective
    (by rw [map_zero]; exact Subtype.ext h')

variable (A) in
/-- **`A⟨X⟩/(f - X)` is flat over a complete noetherian Tate ring** (Wedhorn, Lemma 8.31(2)). -/
theorem flat_quotient_algebraMap_sub_restrictedX (f : A) :
    Module.Flat A (restrictedMvPowerSeriesSubring 1 A ⧸
      Ideal.span {algebraMap A (restrictedMvPowerSeriesSubring 1 A) f - restrictedX}) := by
  have := flat_restrictedMvPowerSeriesSubring (k := 1) (A := A)
  exact Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective _ fun I _ ↦
    lTensor_mulLeft_algebraMap_sub_restrictedX_injective (N := A ⧸ I) f

variable (A) in
/-- **`A⟨X⟩/(1 - f X)` is flat over a complete noetherian Tate ring** (Wedhorn, Lemma 8.31(2)). -/
theorem flat_quotient_one_sub_algebraMap_mul_restrictedX (f : A) :
    Module.Flat A (restrictedMvPowerSeriesSubring 1 A ⧸
      Ideal.span {1 - algebraMap A (restrictedMvPowerSeriesSubring 1 A) f * restrictedX}) := by
  have := flat_restrictedMvPowerSeriesSubring (k := 1) (A := A)
  exact Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective _ fun I _ ↦
    lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX_injective (N := A ⧸ I) f

end Laurent

end TauCeti.Huber
